  # DynamoDB table for Role
  RolesTable:
    Properties:
      AttributeDefinitions:
        -
          AttributeName: role_id
          AttributeType: S
        -
          AttributeName: user_id
          AttributeType: S
        -
          AttributeName: application_id
          AttributeType: S
        -
          AttributeName: role_type
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: role_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        -
          IndexName: user-role-index
          KeySchema:
            -
              AttributeName: user_id
              KeyType: HASH
            -
              AttributeName: role_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        -
          IndexName: application-role-index
          KeySchema:
            -
              AttributeName: application_id
              KeyType: HASH
            -
              AttributeName: role_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        -
          IndexName: role-type-index
          KeySchema:
            -
              AttributeName: role_id
              KeyType: HASH
            -
              AttributeName: role_type
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TableName: !Sub "${CustomerId}-${ProjectId}-${Environment}-roles"
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId
    Type: AWS::DynamoDB::Table

  # Parameter Store for table name
  RolesTableNameParameter:
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-roles-table-name"
      Type: String
      Value: !Ref RolesTable
      Description: DynamoDB Role Table Name
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
    Type: AWS::SSM::Parameter

  # Parameter Store for table ARN
  RolesTableArnParameter:
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-roles-table-arn"
      Type: String
      Value: !GetAtt RolesTable.Arn
      Description: DynamoDB Role Table Arn
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
    Type: AWS::SSM::Parameter