  # DynamoDB table for User
  UsersTable:
    Properties:
      AttributeDefinitions:
        -
          AttributeName: user_id
          AttributeType: S
        -
          AttributeName: email
          AttributeType: S
        -
          AttributeName: cognito_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        -
          IndexName: email-index
          KeySchema:
            -
              AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        -
          IndexName: cognito_id-index
          KeySchema:
            -
              AttributeName: cognito_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TableName: !Sub "${CustomerId}-${ProjectId}-${Environment}-users"
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId
    Type: AWS::DynamoDB::Table

  # Parameter Store for table name
  UsersTableNameParameter:
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-users-table-name"
      Type: String
      Value: !Ref UsersTable
      Description: DynamoDB User Table Name
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
    Type: AWS::SSM::Parameter

  # Parameter Store for table ARN
  UsersTableArnParameter:
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-users-table-arn"
      Type: String
      Value: !GetAtt UsersTable.Arn
      Description: DynamoDB User Table Arn
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
    Type: AWS::SSM::Parameter