// DEV ENVIRONMENT WITH REAL CREDENTIALS
// This file was auto-generated by setup-dev-env.js
// DO NOT COMMIT THIS FILE - it contains real AWS credentials

export const environment = {
  appName: 'Integration Hub',
  production: false,
  debugMode: true,
  loggingLevel: 'debug',
  cognito: {
    userPoolId: 'us-east-1_8ch8unBaX',
    userPoolClientId: '6bbumeaaceom3v7vi2hghga2rb',
    qrCodeIssuer: 'orb-integration-hub-dev'
  },
  graphql: {
    url: 'https://f6nyocke7nbllnyp7nhqiuaivq.appsync-api.us-east-1.amazonaws.com/graphql',
    region: 'us-east-1',
    apiKey: 'da2-q3z4tcp5ljhyvnqerjrobajv3i'
  }
};
