// DEV ENVIRONMENT WITH REAL CREDENTIALS
// This file was auto-generated by setup-dev-env.js
// DO NOT COMMIT THIS FILE - it contains real AWS credentials

export const environment = {
  appName: 'Integration Hub',
  production: false,
  debugMode: true,
  loggingLevel: 'debug',
  cognito: {
    userPoolId: 'us-east-1_ZhrNI8FIz',
    userPoolClientId: 'vaab605uqihpsfu2dagi3p31j',
    qrCodeIssuer: 'orb-integration-hub-dev'
  },
  graphql: {
    url: 'https://zhdlbicpwffhvdoutc5yzz7gba.appsync-api.us-east-1.amazonaws.com/graphql',
    region: 'us-east-1'
  },
  sdkApi: {
    url: 'https://gywdksf7yzaopjdr3e5wv22sw4.appsync-api.us-east-1.amazonaws.com/graphql',
    apiKey: 'orb_dev_frontend_7a6016017035101444f7be27901064e3a3ffe56673ca7f57632067ddcb71e6d8',
    region: 'us-east-1'
  }
};
