name: deploy-packages

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to publish to'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
        default: dev
      skip_tests:
        description: 'Skip tests (not recommended)'
        required: false
        type: boolean
        default: false

jobs:
  detect-changes:
    name: Detect Package Changes
    runs-on: ubuntu-latest
    outputs:
      common-changed: ${{ steps.changes.outputs.common }}
      models-changed: ${{ steps.changes.outputs.models }}
      schemas-changed: ${{ steps.changes.outputs.schemas }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0