# AUTO-GENERATED by orb-schema-generator v2.0.3 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for ApplicationRoles
"""

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import List, Optional
from datetime import datetime

from ..enums.application_role_status_enum import ApplicationRoleStatus
from ..enums.application_role_type_enum import ApplicationRoleType


# CRUD Input Types
class ApplicationRolesCreateInput(BaseModel):
    """ApplicationRoles create input."""

    application_role_id: str = Field(..., description="Unique identifier for the application role definition (primary key)")
    application_id: str = Field(..., description="ID of the application this role belongs to (foreign key to Applications)")
    role_id: str = Field(..., description="Unique role identifier within the application")
    role_name: str = Field(..., description="Display name of the role (e.g., "Admin", "Editor", "Viewer")")
    role_type: ApplicationRoleType = Field(..., description="Type of the role")
    description: Optional[str] = Field(None, description="Optional description of what this role is for")
    status: ApplicationRoleStatus = Field(..., description="Current status of the role definition")
    created_at: datetime = Field(..., description="When the role was created")
    updated_at: datetime = Field(..., description="When the role was last updated")


class ApplicationRolesUpdateInput(BaseModel):
    """ApplicationRoles update input."""

    application_role_id: Optional[str] = Field(..., description="Unique identifier for the application role definition (primary key)")
    application_id: Optional[str] = Field(..., description="ID of the application this role belongs to (foreign key to Applications)")
    role_id: Optional[str] = Field(..., description="Unique role identifier within the application")
    role_name: Optional[str] = Field(..., description="Display name of the role (e.g., "Admin", "Editor", "Viewer")")
    role_type: Optional[ApplicationRoleType] = Field(..., description="Type of the role")
    description: Optional[str] = Field(None, description="Optional description of what this role is for")
    status: Optional[ApplicationRoleStatus] = Field(..., description="Current status of the role definition")
    created_at: Optional[datetime] = Field(..., description="When the role was created")
    updated_at: Optional[datetime] = Field(..., description="When the role was last updated")


class ApplicationRolesDeleteInput(BaseModel):
    """ApplicationRoles delete input."""

    application_role_id: str


class ApplicationRolesDisableInput(BaseModel):
    """ApplicationRoles disable input."""

    application_role_id: str
    disabled: bool



# Query Input Types
class ApplicationRolesQueryByApplicationRoleIdInput(BaseModel):
    """ApplicationRoles query by applicationRoleId."""

    application_role_id: str


class ApplicationRolesQueryByApplicationIdInput(BaseModel):
    """ApplicationRoles query by applicationId."""

    application_id: str


class ApplicationRolesQueryByRoleIdInput(BaseModel):
    """ApplicationRoles query by roleId."""

    role_id: str


# Main Model
class ApplicationRoles(BaseModel):
    """ApplicationRoles model."""

    model_config = ConfigDict(from_attributes=True)

    application_role_id: str = Field(..., description="Unique identifier for the application role definition (primary key)")
    application_id: str = Field(..., description="ID of the application this role belongs to (foreign key to Applications)")
    role_id: str = Field(..., description="Unique role identifier within the application")
    role_name: str = Field(..., description="Display name of the role (e.g., "Admin", "Editor", "Viewer")")
    role_type: ApplicationRoleType = Field(..., description="Type of the role")
    description: Optional[str] = Field(None, description="Optional description of what this role is for")
    status: ApplicationRoleStatus = Field(..., description="Current status of the role definition")
    created_at: datetime = Field(..., description="When the role was created")
    updated_at: datetime = Field(..., description="When the role was last updated")

    @field_validator("created_at", mode="before")
    @classmethod
    def parse_created_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

    @field_validator("updated_at", mode="before")
    @classmethod
    def parse_updated_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value


# Response Types
class ApplicationRolesCreateResponse(BaseModel):
    """ApplicationRoles create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationRoles] = None


class ApplicationRolesUpdateResponse(BaseModel):
    """ApplicationRoles update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationRoles] = None


class ApplicationRolesDeleteResponse(BaseModel):
    """ApplicationRoles delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationRoles] = None


class ApplicationRolesDisableResponse(BaseModel):
    """ApplicationRoles disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationRoles] = None


class ApplicationRolesGetResponse(BaseModel):
    """ApplicationRoles get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationRoles] = None


class ApplicationRolesListResponse(BaseModel):
    """ApplicationRoles list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[ApplicationRoles]] = None
    next_token: Optional[str] = None
