# AUTO-GENERATED by orb-schema-generator v1.1.0 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for ApplicationGroups
"""

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import List, Optional
from datetime import datetime

from ..enums.application_group_status_enum import ApplicationGroupStatus


# CRUD Input Types
class ApplicationGroupsCreateInput(BaseModel):
    """ApplicationGroups create input."""

    application_group_id: str = Field(
        ..., description="Unique identifier for the application group (primary key)"
    )
    application_id: str = Field(
        ..., description="ID of the application this group belongs to (foreign key to Applications)"
    )
    name: str = Field(..., description="Name of the group (unique within application)")
    description: Optional[str] = Field(None, description="Optional description of the group")
    status: ApplicationGroupStatus = Field(..., description="Current status of the group")
    member_count: Optional[int] = Field(
        0, description="Denormalized count of active members in this group"
    )
    created_at: datetime = Field(..., description="When the group was created")
    updated_at: datetime = Field(..., description="When the group was last updated")


class ApplicationGroupsUpdateInput(BaseModel):
    """ApplicationGroups update input."""

    application_group_id: Optional[str] = Field(
        ..., description="Unique identifier for the application group (primary key)"
    )
    application_id: Optional[str] = Field(
        ..., description="ID of the application this group belongs to (foreign key to Applications)"
    )
    name: Optional[str] = Field(..., description="Name of the group (unique within application)")
    description: Optional[str] = Field(None, description="Optional description of the group")
    status: Optional[ApplicationGroupStatus] = Field(..., description="Current status of the group")
    member_count: Optional[int] = Field(
        0, description="Denormalized count of active members in this group"
    )
    created_at: Optional[datetime] = Field(..., description="When the group was created")
    updated_at: Optional[datetime] = Field(..., description="When the group was last updated")


class ApplicationGroupsDeleteInput(BaseModel):
    """ApplicationGroups delete input."""

    application_group_id: str


class ApplicationGroupsDisableInput(BaseModel):
    """ApplicationGroups disable input."""

    application_group_id: str
    disabled: bool


# Query Input Types
class ApplicationGroupsQueryByApplicationGroupIdInput(BaseModel):
    """ApplicationGroups query by applicationGroupId."""

    application_group_id: str


class ApplicationGroupsQueryByApplicationIdInput(BaseModel):
    """ApplicationGroups query by applicationId."""

    application_id: str


# Main Model
class ApplicationGroups(BaseModel):
    """ApplicationGroups model."""

    model_config = ConfigDict(from_attributes=True)

    application_group_id: str = Field(
        ..., description="Unique identifier for the application group (primary key)"
    )
    application_id: str = Field(
        ..., description="ID of the application this group belongs to (foreign key to Applications)"
    )
    name: str = Field(..., description="Name of the group (unique within application)")
    description: Optional[str] = Field(None, description="Optional description of the group")
    status: ApplicationGroupStatus = Field(..., description="Current status of the group")
    member_count: Optional[int] = Field(
        0, description="Denormalized count of active members in this group"
    )
    created_at: datetime = Field(..., description="When the group was created")
    updated_at: datetime = Field(..., description="When the group was last updated")

    @field_validator("created_at", mode="before")
    @classmethod
    def parse_created_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

    @field_validator("updated_at", mode="before")
    @classmethod
    def parse_updated_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value


# Response Types
class ApplicationGroupsCreateResponse(BaseModel):
    """ApplicationGroups create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationGroups] = None


class ApplicationGroupsUpdateResponse(BaseModel):
    """ApplicationGroups update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationGroups] = None


class ApplicationGroupsDeleteResponse(BaseModel):
    """ApplicationGroups delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationGroups] = None


class ApplicationGroupsDisableResponse(BaseModel):
    """ApplicationGroups disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationGroups] = None


class ApplicationGroupsGetResponse(BaseModel):
    """ApplicationGroups get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationGroups] = None


class ApplicationGroupsListResponse(BaseModel):
    """ApplicationGroups list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[ApplicationGroups]] = None
    next_token: Optional[str] = None
