# AUTO-GENERATED by orb-schema-generator v2.0.3 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for ApplicationEnvironmentConfig
"""

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, Dict, List, Optional
from datetime import datetime

from ..enums.environment_enum import Environment


# CRUD Input Types
class ApplicationEnvironmentConfigCreateInput(BaseModel):
    """ApplicationEnvironmentConfig create input."""

    application_id: str = Field(..., description="ID of the application (partition key)")
    environment: Environment = Field(..., description="Environment this configuration applies to (sort key)")
    organization_id: str = Field(..., description="ID of the organization (denormalized for queries)")
    allowed_origins: Optional[List[str]] = Field(None, description="List of allowed CORS origins for publishable keys (max 10)")
    rate_limit_per_minute: float = Field(..., description="Maximum API requests per minute (default 60)")
    rate_limit_per_day: float = Field(..., description="Maximum API requests per day (default 10000)")
    webhook_url: Optional[str] = Field(None, description="HTTPS URL for webhook delivery")
    webhook_secret: Optional[str] = Field(None, description="HMAC secret for webhook signature (32 chars)")
    webhook_events: Optional[List[str]] = Field(None, description="List of event types to deliver via webhook")
    webhook_enabled: Optional[bool] = Field(None, description="Whether webhook delivery is enabled")
    webhook_max_retries: Optional[float] = Field(None, description="Maximum retry attempts for failed webhook delivery (default 3)")
    webhook_retry_delay_seconds: Optional[float] = Field(None, description="Delay between retry attempts in seconds (default 60)")
    feature_flags: Optional[Dict[str, Any]] = Field(None, description="Map of feature flag keys to values (boolean, string, or number)")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Custom key-value pairs for environment-specific data")
    created_at: datetime = Field(..., description="When the configuration was created")
    updated_at: datetime = Field(..., description="When the configuration was last updated")


class ApplicationEnvironmentConfigUpdateInput(BaseModel):
    """ApplicationEnvironmentConfig update input."""

    application_id: Optional[str] = Field(..., description="ID of the application (partition key)")
    environment: Optional[Environment] = Field(..., description="Environment this configuration applies to (sort key)")
    organization_id: Optional[str] = Field(..., description="ID of the organization (denormalized for queries)")
    allowed_origins: Optional[List[str]] = Field(None, description="List of allowed CORS origins for publishable keys (max 10)")
    rate_limit_per_minute: Optional[float] = Field(..., description="Maximum API requests per minute (default 60)")
    rate_limit_per_day: Optional[float] = Field(..., description="Maximum API requests per day (default 10000)")
    webhook_url: Optional[str] = Field(None, description="HTTPS URL for webhook delivery")
    webhook_secret: Optional[str] = Field(None, description="HMAC secret for webhook signature (32 chars)")
    webhook_events: Optional[List[str]] = Field(None, description="List of event types to deliver via webhook")
    webhook_enabled: Optional[bool] = Field(None, description="Whether webhook delivery is enabled")
    webhook_max_retries: Optional[float] = Field(None, description="Maximum retry attempts for failed webhook delivery (default 3)")
    webhook_retry_delay_seconds: Optional[float] = Field(None, description="Delay between retry attempts in seconds (default 60)")
    feature_flags: Optional[Dict[str, Any]] = Field(None, description="Map of feature flag keys to values (boolean, string, or number)")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Custom key-value pairs for environment-specific data")
    created_at: Optional[datetime] = Field(..., description="When the configuration was created")
    updated_at: Optional[datetime] = Field(..., description="When the configuration was last updated")


class ApplicationEnvironmentConfigDeleteInput(BaseModel):
    """ApplicationEnvironmentConfig delete input."""

    application_id: str
    environment: str


class ApplicationEnvironmentConfigDisableInput(BaseModel):
    """ApplicationEnvironmentConfig disable input."""

    application_id: str
    environment: str
    disabled: bool



# Query Input Types
class ApplicationEnvironmentConfigQueryByApplicationIdInput(BaseModel):
    """ApplicationEnvironmentConfig query by applicationId."""

    application_id: str


class ApplicationEnvironmentConfigQueryByEnvironmentInput(BaseModel):
    """ApplicationEnvironmentConfig query by environment."""

    environment: str


class ApplicationEnvironmentConfigQueryByOrganizationIdInput(BaseModel):
    """ApplicationEnvironmentConfig query by organizationId."""

    organization_id: str


class ApplicationEnvironmentConfigQueryByBothInput(BaseModel):
    """ApplicationEnvironmentConfig query by both keys."""

    application_id: str
    environment: str


# Main Model
class ApplicationEnvironmentConfig(BaseModel):
    """ApplicationEnvironmentConfig model."""

    model_config = ConfigDict(from_attributes=True)

    application_id: str = Field(..., description="ID of the application (partition key)")
    environment: Environment = Field(..., description="Environment this configuration applies to (sort key)")
    organization_id: str = Field(..., description="ID of the organization (denormalized for queries)")
    allowed_origins: Optional[List[str]] = Field(None, description="List of allowed CORS origins for publishable keys (max 10)")
    rate_limit_per_minute: float = Field(..., description="Maximum API requests per minute (default 60)")
    rate_limit_per_day: float = Field(..., description="Maximum API requests per day (default 10000)")
    webhook_url: Optional[str] = Field(None, description="HTTPS URL for webhook delivery")
    webhook_secret: Optional[str] = Field(None, description="HMAC secret for webhook signature (32 chars)")
    webhook_events: Optional[List[str]] = Field(None, description="List of event types to deliver via webhook")
    webhook_enabled: Optional[bool] = Field(None, description="Whether webhook delivery is enabled")
    webhook_max_retries: Optional[float] = Field(None, description="Maximum retry attempts for failed webhook delivery (default 3)")
    webhook_retry_delay_seconds: Optional[float] = Field(None, description="Delay between retry attempts in seconds (default 60)")
    feature_flags: Optional[Dict[str, Any]] = Field(None, description="Map of feature flag keys to values (boolean, string, or number)")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Custom key-value pairs for environment-specific data")
    created_at: datetime = Field(..., description="When the configuration was created")
    updated_at: datetime = Field(..., description="When the configuration was last updated")

    @field_validator("webhook_enabled", mode="before")
    @classmethod
    def parse_webhook_enabled(cls, value):
        """Parse boolean value."""
        if value is None:
            return None
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            if value.lower() == "true":
                return True
            if value.lower() == "false":
                return False
        return bool(value)

    @field_validator("created_at", mode="before")
    @classmethod
    def parse_created_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

    @field_validator("updated_at", mode="before")
    @classmethod
    def parse_updated_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value


# Response Types
class ApplicationEnvironmentConfigCreateResponse(BaseModel):
    """ApplicationEnvironmentConfig create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationEnvironmentConfig] = None


class ApplicationEnvironmentConfigUpdateResponse(BaseModel):
    """ApplicationEnvironmentConfig update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationEnvironmentConfig] = None


class ApplicationEnvironmentConfigDeleteResponse(BaseModel):
    """ApplicationEnvironmentConfig delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationEnvironmentConfig] = None


class ApplicationEnvironmentConfigDisableResponse(BaseModel):
    """ApplicationEnvironmentConfig disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationEnvironmentConfig] = None


class ApplicationEnvironmentConfigGetResponse(BaseModel):
    """ApplicationEnvironmentConfig get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationEnvironmentConfig] = None


class ApplicationEnvironmentConfigListResponse(BaseModel):
    """ApplicationEnvironmentConfig list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[ApplicationEnvironmentConfig]] = None
    next_token: Optional[str] = None
