# AUTO-GENERATED by orb-schema-generator v1.3.0 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for Applications
"""

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import List, Optional
from datetime import datetime

from ..enums.application_status_enum import ApplicationStatus


# CRUD Input Types
class ApplicationsCreateInput(BaseModel):
    """Applications create input."""

    application_id: str = Field(..., description="Unique identifier for the application (primary key)")
    name: str = Field(..., description="Name of the application")
    description: Optional[str] = Field(None, description="Brief description of the application")
    organization_id: str = Field(..., description="ID of the organization this application belongs to (foreign key to Organizations)")
    owner_id: str = Field(..., description="ID of the user who owns the application (foreign key to Users)")
    status: ApplicationStatus = Field(..., description="Current status of the application")
    created_at: datetime = Field(..., description="When the application was created")
    updated_at: datetime = Field(..., description="When the application was last updated")
    api_key: str = Field(..., description="Current active API key for the application")
    api_key_next: Optional[str] = Field(None, description="Next API key for rotation (dual key system)")
    environments: List[str] = Field(..., description="List of available environments for this application (max 5 for starter plan)")
    group_count: Optional[float] = Field(None, description="Count of ACTIVE application groups (denormalized for display)")
    user_count: Optional[float] = Field(None, description="Count of ACTIVE application group users (denormalized for display)")
    role_count: Optional[float] = Field(None, description="Count of ACTIVE direct user role assignments (denormalized for display)")


class ApplicationsUpdateInput(BaseModel):
    """Applications update input."""

    application_id: Optional[str] = Field(..., description="Unique identifier for the application (primary key)")
    name: Optional[str] = Field(..., description="Name of the application")
    description: Optional[str] = Field(None, description="Brief description of the application")
    organization_id: Optional[str] = Field(..., description="ID of the organization this application belongs to (foreign key to Organizations)")
    owner_id: Optional[str] = Field(..., description="ID of the user who owns the application (foreign key to Users)")
    status: Optional[ApplicationStatus] = Field(..., description="Current status of the application")
    created_at: Optional[datetime] = Field(..., description="When the application was created")
    updated_at: Optional[datetime] = Field(..., description="When the application was last updated")
    api_key: Optional[str] = Field(..., description="Current active API key for the application")
    api_key_next: Optional[str] = Field(None, description="Next API key for rotation (dual key system)")
    environments: Optional[List[str]] = Field(..., description="List of available environments for this application (max 5 for starter plan)")
    group_count: Optional[float] = Field(None, description="Count of ACTIVE application groups (denormalized for display)")
    user_count: Optional[float] = Field(None, description="Count of ACTIVE application group users (denormalized for display)")
    role_count: Optional[float] = Field(None, description="Count of ACTIVE direct user role assignments (denormalized for display)")


class ApplicationsDeleteInput(BaseModel):
    """Applications delete input."""

    application_id: str


class ApplicationsDisableInput(BaseModel):
    """Applications disable input."""

    application_id: str
    disabled: bool



# Query Input Types
class ApplicationsQueryByApplicationIdInput(BaseModel):
    """Applications query by applicationId."""

    application_id: str


class ApplicationsQueryByOrganizationIdInput(BaseModel):
    """Applications query by organizationId."""

    organization_id: str


# Main Model
class Applications(BaseModel):
    """Applications model."""

    model_config = ConfigDict(from_attributes=True)

    application_id: str = Field(..., description="Unique identifier for the application (primary key)")
    name: str = Field(..., description="Name of the application")
    description: Optional[str] = Field(None, description="Brief description of the application")
    organization_id: str = Field(..., description="ID of the organization this application belongs to (foreign key to Organizations)")
    owner_id: str = Field(..., description="ID of the user who owns the application (foreign key to Users)")
    status: ApplicationStatus = Field(..., description="Current status of the application")
    created_at: datetime = Field(..., description="When the application was created")
    updated_at: datetime = Field(..., description="When the application was last updated")
    api_key: str = Field(..., description="Current active API key for the application")
    api_key_next: Optional[str] = Field(None, description="Next API key for rotation (dual key system)")
    environments: List[str] = Field(..., description="List of available environments for this application (max 5 for starter plan)")
    group_count: Optional[float] = Field(None, description="Count of ACTIVE application groups (denormalized for display)")
    user_count: Optional[float] = Field(None, description="Count of ACTIVE application group users (denormalized for display)")
    role_count: Optional[float] = Field(None, description="Count of ACTIVE direct user role assignments (denormalized for display)")

    @field_validator("created_at", mode="before")
    @classmethod
    def parse_created_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

    @field_validator("updated_at", mode="before")
    @classmethod
    def parse_updated_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value


# Response Types
class ApplicationsCreateResponse(BaseModel):
    """Applications create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[Applications] = None


class ApplicationsUpdateResponse(BaseModel):
    """Applications update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[Applications] = None


class ApplicationsDeleteResponse(BaseModel):
    """Applications delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[Applications] = None


class ApplicationsDisableResponse(BaseModel):
    """Applications disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[Applications] = None


class ApplicationsGetResponse(BaseModel):
    """Applications get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[Applications] = None


class ApplicationsListResponse(BaseModel):
    """Applications list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[Applications]] = None
    next_token: Optional[str] = None
