# AUTO-GENERATED by orb-schema-generator v3.2.7 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for ApplicationUserStatus
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional


# Main Model
class ApplicationUserStatus(BaseModel):
    """ApplicationUserStatus model."""

    model_config = ConfigDict(from_attributes=True)

    value: str = Field(..., description="Registry item value")


# Response Types
class ApplicationUserStatusCreateResponse(BaseModel):
    """ApplicationUserStatus create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationUserStatus] = None


class ApplicationUserStatusUpdateResponse(BaseModel):
    """ApplicationUserStatus update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationUserStatus] = None


class ApplicationUserStatusDeleteResponse(BaseModel):
    """ApplicationUserStatus delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationUserStatus] = None


class ApplicationUserStatusDisableResponse(BaseModel):
    """ApplicationUserStatus disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationUserStatus] = None


class ApplicationUserStatusGetResponse(BaseModel):
    """ApplicationUserStatus get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[ApplicationUserStatus] = None


class ApplicationUserStatusListResponse(BaseModel):
    """ApplicationUserStatus list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[ApplicationUserStatus]] = None
    next_token: Optional[str] = None
