# AUTO-GENERATED by orb-schema-generator v0.16.0 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for ApplicationUsers
"""

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import List, Optional
from datetime import datetime

from ..enums.application_user_status_enum import ApplicationUserStatus

# CRUD Input Types
class ApplicationUsersCreateInput(BaseModel):
    """ApplicationUsers create input."""

    application_user_id: str = Field(..., description="Unique identifier for the application user membership (primary key)")
    user_id: str = Field(..., description="ID of the user (foreign key to Users)")
    application_id: str = Field(..., description="ID of the application (foreign key to Applications)")
    status: ApplicationUserStatus = Field(..., description="Current status of the user in the application")
    created_at: datetime = Field(..., description="When the user was added to the application")
    updated_at: datetime = Field(..., description="When the membership was last updated")


class ApplicationUsersUpdateInput(BaseModel):
    """ApplicationUsers update input."""

    application_user_id: Optional[str] = Field(..., description="Unique identifier for the application user membership (primary key)")
    user_id: Optional[str] = Field(..., description="ID of the user (foreign key to Users)")
    application_id: Optional[str] = Field(..., description="ID of the application (foreign key to Applications)")
    status: Optional[ApplicationUserStatus] = Field(..., description="Current status of the user in the application")
    created_at: Optional[datetime] = Field(..., description="When the user was added to the application")
    updated_at: Optional[datetime] = Field(..., description="When the membership was last updated")


class ApplicationUsersDeleteInput(BaseModel):
    """ApplicationUsers delete input."""

    application_user_id: str


class ApplicationUsersDisableInput(BaseModel):
    """ApplicationUsers disable input."""

    application_user_id: str
    disabled: bool


# Query Input Types
class ApplicationUsersQueryByApplicationUserIdInput(BaseModel):
    """ApplicationUsers query by applicationUserId."""

    application_user_id: str


class ApplicationUsersQueryByUserIdInput(BaseModel):
    """ApplicationUsers query by userId."""

    user_id: str


class ApplicationUsersQueryByApplicationIdInput(BaseModel):
    """ApplicationUsers query by applicationId."""

    application_id: str


# Main Model
class ApplicationUsers(BaseModel):
    """ApplicationUsers model."""

    model_config = ConfigDict(from_attributes=True)

    application_user_id: str = Field(..., description="Unique identifier for the application user membership (primary key)")
    user_id: str = Field(..., description="ID of the user (foreign key to Users)")
    application_id: str = Field(..., description="ID of the application (foreign key to Applications)")
    status: ApplicationUserStatus = Field(..., description="Current status of the user in the application")
    created_at: datetime = Field(..., description="When the user was added to the application")
    updated_at: datetime = Field(..., description="When the membership was last updated")

    @field_validator("created_at", mode="before")
    @classmethod
    def parse_created_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

    @field_validator("updated_at", mode="before")
    @classmethod
    def parse_updated_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

# Response Types
class ApplicationUsersResponse(BaseModel):
    """ApplicationUsers response."""

    StatusCode: int
    Message: Optional[str] = None
    Data: Optional[ApplicationUsers] = None


class ApplicationUsersListResponse(BaseModel):
    """ApplicationUsers list response."""

    StatusCode: int
    Message: Optional[str] = None
    Data: Optional[List[ApplicationUsers]] = None


# CRUD Response Aliases
ApplicationUsersCreateResponse = ApplicationUsersResponse
ApplicationUsersUpdateResponse = ApplicationUsersResponse
ApplicationUsersDeleteResponse = ApplicationUsersResponse
ApplicationUsersDisableResponse = ApplicationUsersResponse