# AUTO-GENERATED by orb-schema-generator v1.3.0 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for CheckEmailExists
"""

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import List, Optional


# Main Model
class CheckEmailExists(BaseModel):
    """CheckEmailExists model."""

    model_config = ConfigDict(from_attributes=True)

    email: str = Field(..., description="Email address to check for existence")
    exists: Optional[bool] = Field(None, description="Whether the email exists in the system (response only)")
    cognito_status: Optional[str] = Field(None, description="Cognito user status (UNCONFIRMED, CONFIRMED, FORCE_CHANGE_PASSWORD, etc.)")
    cognito_sub: Optional[str] = Field(None, description="Cognito user ID (sub) if user exists in Cognito")

    @field_validator("exists", mode="before")
    @classmethod
    def parse_exists(cls, value):
        """Parse boolean value."""
        if value is None:
            return None
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            if value.lower() == "true":
                return True
            if value.lower() == "false":
                return False
        return bool(value)


# Response Types
class CheckEmailExistsCreateResponse(BaseModel):
    """CheckEmailExists create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[CheckEmailExists] = None


class CheckEmailExistsUpdateResponse(BaseModel):
    """CheckEmailExists update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[CheckEmailExists] = None


class CheckEmailExistsDeleteResponse(BaseModel):
    """CheckEmailExists delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[CheckEmailExists] = None


class CheckEmailExistsDisableResponse(BaseModel):
    """CheckEmailExists disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[CheckEmailExists] = None


class CheckEmailExistsGetResponse(BaseModel):
    """CheckEmailExists get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[CheckEmailExists] = None


class CheckEmailExistsListResponse(BaseModel):
    """CheckEmailExists list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[CheckEmailExists]] = None
    next_token: Optional[str] = None
