# AUTO-GENERATED by orb-schema-generator v0.16.0 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for CheckEmailExists
"""

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import List, Optional

# Main Model
class CheckEmailExists(BaseModel):
    """CheckEmailExists model."""

    model_config = ConfigDict(from_attributes=True)

    email: str = Field(..., description="Email address to check for existence")
    exists: bool = Field(..., description="Whether the email exists in the system")

    @field_validator("exists", mode="before")
    @classmethod
    def parse_exists(cls, value):
        """Parse boolean value."""
        if value is None:
            return None
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            if value.lower() == "true":
                return True
            if value.lower() == "false":
                return False
        return bool(value)

# Response Types
class CheckEmailExistsResponse(BaseModel):
    """CheckEmailExists response."""

    StatusCode: int
    Message: Optional[str] = None
    Data: Optional[CheckEmailExists] = None


class CheckEmailExistsListResponse(BaseModel):
    """CheckEmailExists list response."""

    StatusCode: int
    Message: Optional[str] = None
    Data: Optional[List[CheckEmailExists]] = None


# CRUD Response Aliases
CheckEmailExistsCreateResponse = CheckEmailExistsResponse
CheckEmailExistsUpdateResponse = CheckEmailExistsResponse
CheckEmailExistsDeleteResponse = CheckEmailExistsResponse
CheckEmailExistsDisableResponse = CheckEmailExistsResponse