# AUTO-GENERATED by orb-schema-generator v2.0.3 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for GetCurrentUser
"""

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import List, Optional
from datetime import datetime

from ..enums.user_status_enum import UserStatus


# Main Model
class GetCurrentUser(BaseModel):
    """GetCurrentUser model."""

    model_config = ConfigDict(from_attributes=True)

    user_id: Optional[str] = Field(None, description="User ID (same as cognitoSub)")
    cognito_id: Optional[str] = Field(None, description="Cognito username")
    cognito_sub: Optional[str] = Field(None, description="Cognito user sub (UUID)")
    email: Optional[str] = Field(None, description="User's email address")
    first_name: Optional[str] = Field(None, description="User's first name")
    last_name: Optional[str] = Field(None, description="User's last name")
    status: Optional[UserStatus] = Field(None, description="Current user status")
    phone_number: Optional[str] = Field(None, description="User's phone number")
    groups: Optional[List[str]] = Field(None, description="Cognito groups the user belongs to")
    email_verified: Optional[bool] = Field(None, description="Whether email is verified")
    phone_verified: Optional[bool] = Field(None, description="Whether phone is verified")
    mfa_enabled: Optional[bool] = Field(None, description="Whether MFA is enabled")
    mfa_setup_complete: Optional[bool] = Field(None, description="Whether MFA setup is complete")
    created_at: Optional[datetime] = Field(None, description="Record creation timestamp")
    updated_at: Optional[datetime] = Field(None, description="Record update timestamp")

    @field_validator("email_verified", mode="before")
    @classmethod
    def parse_email_verified(cls, value):
        """Parse boolean value."""
        if value is None:
            return None
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            if value.lower() == "true":
                return True
            if value.lower() == "false":
                return False
        return bool(value)

    @field_validator("phone_verified", mode="before")
    @classmethod
    def parse_phone_verified(cls, value):
        """Parse boolean value."""
        if value is None:
            return None
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            if value.lower() == "true":
                return True
            if value.lower() == "false":
                return False
        return bool(value)

    @field_validator("mfa_enabled", mode="before")
    @classmethod
    def parse_mfa_enabled(cls, value):
        """Parse boolean value."""
        if value is None:
            return None
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            if value.lower() == "true":
                return True
            if value.lower() == "false":
                return False
        return bool(value)

    @field_validator("mfa_setup_complete", mode="before")
    @classmethod
    def parse_mfa_setup_complete(cls, value):
        """Parse boolean value."""
        if value is None:
            return None
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            if value.lower() == "true":
                return True
            if value.lower() == "false":
                return False
        return bool(value)

    @field_validator("created_at", mode="before")
    @classmethod
    def parse_created_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

    @field_validator("updated_at", mode="before")
    @classmethod
    def parse_updated_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value


# Response Types
class GetCurrentUserCreateResponse(BaseModel):
    """GetCurrentUser create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[GetCurrentUser] = None


class GetCurrentUserUpdateResponse(BaseModel):
    """GetCurrentUser update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[GetCurrentUser] = None


class GetCurrentUserDeleteResponse(BaseModel):
    """GetCurrentUser delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[GetCurrentUser] = None


class GetCurrentUserDisableResponse(BaseModel):
    """GetCurrentUser disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[GetCurrentUser] = None


class GetCurrentUserGetResponse(BaseModel):
    """GetCurrentUser get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[GetCurrentUser] = None


class GetCurrentUserListResponse(BaseModel):
    """GetCurrentUser list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[GetCurrentUser]] = None
    next_token: Optional[str] = None
