# AUTO-GENERATED by orb-schema-generator v1.0.1 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for MfaSetupDetails
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional


# Main Model
class MfaSetupDetails(BaseModel):
    """MfaSetupDetails model."""

    model_config = ConfigDict(from_attributes=True)

    qr_code: str = Field(..., description="The QR code value or label for the authenticator app")
    secret_key: str = Field(..., description="The secret key for TOTP setup")
    setup_uri: Optional[str] = Field(None, description="The setup URI for the authenticator app (optional, as string)")


# Response Types
class MfaSetupDetailsCreateResponse(BaseModel):
    """MfaSetupDetails create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[MfaSetupDetails] = None


class MfaSetupDetailsUpdateResponse(BaseModel):
    """MfaSetupDetails update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[MfaSetupDetails] = None


class MfaSetupDetailsDeleteResponse(BaseModel):
    """MfaSetupDetails delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[MfaSetupDetails] = None


class MfaSetupDetailsDisableResponse(BaseModel):
    """MfaSetupDetails disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[MfaSetupDetails] = None


class MfaSetupDetailsGetResponse(BaseModel):
    """MfaSetupDetails get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[MfaSetupDetails] = None


class MfaSetupDetailsListResponse(BaseModel):
    """MfaSetupDetails list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[MfaSetupDetails]] = None
    next_token: Optional[str] = None
