# AUTO-GENERATED by orb-schema-generator v3.2.7 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for NotificationType
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional


# Main Model
class NotificationType(BaseModel):
    """NotificationType model."""

    model_config = ConfigDict(from_attributes=True)

    value: str = Field(..., description="Registry item value")


# Response Types
class NotificationTypeCreateResponse(BaseModel):
    """NotificationType create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[NotificationType] = None


class NotificationTypeUpdateResponse(BaseModel):
    """NotificationType update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[NotificationType] = None


class NotificationTypeDeleteResponse(BaseModel):
    """NotificationType delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[NotificationType] = None


class NotificationTypeDisableResponse(BaseModel):
    """NotificationType disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[NotificationType] = None


class NotificationTypeGetResponse(BaseModel):
    """NotificationType get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[NotificationType] = None


class NotificationTypeListResponse(BaseModel):
    """NotificationType list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[NotificationType]] = None
    next_token: Optional[str] = None
