# AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for OrganizationUsers
"""

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import List, Optional
from datetime import datetime

from ..enums.organization_user_role_enum import OrganizationUserRole
from ..enums.organization_user_status_enum import OrganizationUserStatus


# Main Model
class OrganizationUsers(BaseModel):
    """OrganizationUsers model."""

    model_config = ConfigDict(from_attributes=True)

    user_id: str = Field(..., description="ID of the user (foreign key to Users table)")
    organization_id: str = Field(..., description="ID of the organization (foreign key to Organizations table)")
    role: OrganizationUserRole = Field(..., description="Role of the user within the organization")
    status: OrganizationUserStatus = Field(..., description="Status of the user's membership")
    invited_by: Optional[str] = Field(None, description="ID of the user who invited this member")
    invited_at: Optional[datetime] = Field(None, description="When the invitation was sent")
    joined_at: Optional[datetime] = Field(None, description="When the user accepted and joined")
    created_at: datetime = Field(..., description="When the membership record was created")
    updated_at: datetime = Field(..., description="When the membership record was last updated")

    @field_validator("invited_at", mode="before")
    @classmethod
    def parse_invited_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

    @field_validator("joined_at", mode="before")
    @classmethod
    def parse_joined_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

    @field_validator("created_at", mode="before")
    @classmethod
    def parse_created_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

    @field_validator("updated_at", mode="before")
    @classmethod
    def parse_updated_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value


# Response Types
class OrganizationUsersCreateResponse(BaseModel):
    """OrganizationUsers create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationUsers] = None


class OrganizationUsersUpdateResponse(BaseModel):
    """OrganizationUsers update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationUsers] = None


class OrganizationUsersDeleteResponse(BaseModel):
    """OrganizationUsers delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationUsers] = None


class OrganizationUsersDisableResponse(BaseModel):
    """OrganizationUsers disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationUsers] = None


class OrganizationUsersGetResponse(BaseModel):
    """OrganizationUsers get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationUsers] = None


class OrganizationUsersListResponse(BaseModel):
    """OrganizationUsers list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[OrganizationUsers]] = None
    next_token: Optional[str] = None
