# AUTO-GENERATED by orb-schema-generator v3.2.7 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for OrganizationUserStatus
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional


# Main Model
class OrganizationUserStatus(BaseModel):
    """OrganizationUserStatus model."""

    model_config = ConfigDict(from_attributes=True)

    value: str = Field(..., description="Registry item value")


# Response Types
class OrganizationUserStatusCreateResponse(BaseModel):
    """OrganizationUserStatus create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationUserStatus] = None


class OrganizationUserStatusUpdateResponse(BaseModel):
    """OrganizationUserStatus update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationUserStatus] = None


class OrganizationUserStatusDeleteResponse(BaseModel):
    """OrganizationUserStatus delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationUserStatus] = None


class OrganizationUserStatusDisableResponse(BaseModel):
    """OrganizationUserStatus disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationUserStatus] = None


class OrganizationUserStatusGetResponse(BaseModel):
    """OrganizationUserStatus get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationUserStatus] = None


class OrganizationUserStatusListResponse(BaseModel):
    """OrganizationUserStatus list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[OrganizationUserStatus]] = None
    next_token: Optional[str] = None
