# AUTO-GENERATED by orb-schema-generator v3.2.7 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for OrganizationUserRole
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional


# Main Model
class OrganizationUserRole(BaseModel):
    """OrganizationUserRole model."""

    model_config = ConfigDict(from_attributes=True)

    value: str = Field(..., description="Registry item value")


# Response Types
class OrganizationUserRoleCreateResponse(BaseModel):
    """OrganizationUserRole create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationUserRole] = None


class OrganizationUserRoleUpdateResponse(BaseModel):
    """OrganizationUserRole update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationUserRole] = None


class OrganizationUserRoleDeleteResponse(BaseModel):
    """OrganizationUserRole delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationUserRole] = None


class OrganizationUserRoleDisableResponse(BaseModel):
    """OrganizationUserRole disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationUserRole] = None


class OrganizationUserRoleGetResponse(BaseModel):
    """OrganizationUserRole get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationUserRole] = None


class OrganizationUserRoleListResponse(BaseModel):
    """OrganizationUserRole list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[OrganizationUserRole]] = None
    next_token: Optional[str] = None
