# AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for OrganizationStatus
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional


# Main Model
class OrganizationStatus(BaseModel):
    """OrganizationStatus model."""

    model_config = ConfigDict(from_attributes=True)

    value: str = Field(..., description="Registry item value")


# Response Types
class OrganizationStatusCreateResponse(BaseModel):
    """OrganizationStatus create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationStatus] = None


class OrganizationStatusUpdateResponse(BaseModel):
    """OrganizationStatus update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationStatus] = None


class OrganizationStatusDeleteResponse(BaseModel):
    """OrganizationStatus delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationStatus] = None


class OrganizationStatusDisableResponse(BaseModel):
    """OrganizationStatus disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationStatus] = None


class OrganizationStatusGetResponse(BaseModel):
    """OrganizationStatus get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OrganizationStatus] = None


class OrganizationStatusListResponse(BaseModel):
    """OrganizationStatus list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[OrganizationStatus]] = None
    next_token: Optional[str] = None
