# AUTO-GENERATED by orb-schema-generator v3.2.7 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for OwnershipTransferRequests
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional

from ..enums.ownership_transfer_status_enum import OwnershipTransferStatus


# Main Model
class OwnershipTransferRequests(BaseModel):
    """OwnershipTransferRequests model."""

    model_config = ConfigDict(from_attributes=True)

    transfer_id: str = Field(..., description="Unique identifier for the transfer request")
    organization_id: str = Field(..., description="ID of the organization being transferred")
    current_owner_id: str = Field(..., description="ID of the current owner initiating the transfer")
    new_owner_id: str = Field(..., description="ID of the user receiving ownership")
    status: OwnershipTransferStatus = Field(..., description="Current status of the transfer request")
    reason: Optional[str] = Field(None, description="Reason for the ownership transfer")
    expires_at: str = Field(..., description="When the transfer request expires (ISO 8601 format)")
    completed_at: Optional[str] = Field(None, description="When the transfer was completed")
    cancelled_at: Optional[str] = Field(None, description="When the transfer was cancelled")
    created_at: str = Field(..., description="When the transfer request was created (ISO 8601 format)")
    updated_at: str = Field(..., description="When the transfer request was last updated")


# Response Types
class OwnershipTransferRequestsCreateResponse(BaseModel):
    """OwnershipTransferRequests create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OwnershipTransferRequests] = None


class OwnershipTransferRequestsUpdateResponse(BaseModel):
    """OwnershipTransferRequests update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OwnershipTransferRequests] = None


class OwnershipTransferRequestsDeleteResponse(BaseModel):
    """OwnershipTransferRequests delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OwnershipTransferRequests] = None


class OwnershipTransferRequestsDisableResponse(BaseModel):
    """OwnershipTransferRequests disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OwnershipTransferRequests] = None


class OwnershipTransferRequestsGetResponse(BaseModel):
    """OwnershipTransferRequests get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OwnershipTransferRequests] = None


class OwnershipTransferRequestsListResponse(BaseModel):
    """OwnershipTransferRequests list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[OwnershipTransferRequests]] = None
    next_token: Optional[str] = None
