# AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for OwnershipTransferStatus
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional


# Main Model
class OwnershipTransferStatus(BaseModel):
    """OwnershipTransferStatus model."""

    model_config = ConfigDict(from_attributes=True)

    value: str = Field(..., description="Registry item value")


# Response Types
class OwnershipTransferStatusCreateResponse(BaseModel):
    """OwnershipTransferStatus create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OwnershipTransferStatus] = None


class OwnershipTransferStatusUpdateResponse(BaseModel):
    """OwnershipTransferStatus update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OwnershipTransferStatus] = None


class OwnershipTransferStatusDeleteResponse(BaseModel):
    """OwnershipTransferStatus delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OwnershipTransferStatus] = None


class OwnershipTransferStatusDisableResponse(BaseModel):
    """OwnershipTransferStatus disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OwnershipTransferStatus] = None


class OwnershipTransferStatusGetResponse(BaseModel):
    """OwnershipTransferStatus get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[OwnershipTransferStatus] = None


class OwnershipTransferStatusListResponse(BaseModel):
    """OwnershipTransferStatus list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[OwnershipTransferStatus]] = None
    next_token: Optional[str] = None
