# AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for PrivacyRequestType
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional


# Main Model
class PrivacyRequestType(BaseModel):
    """PrivacyRequestType model."""

    model_config = ConfigDict(from_attributes=True)

    value: str = Field(..., description="Registry item value")


# Response Types
class PrivacyRequestTypeCreateResponse(BaseModel):
    """PrivacyRequestType create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[PrivacyRequestType] = None


class PrivacyRequestTypeUpdateResponse(BaseModel):
    """PrivacyRequestType update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[PrivacyRequestType] = None


class PrivacyRequestTypeDeleteResponse(BaseModel):
    """PrivacyRequestType delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[PrivacyRequestType] = None


class PrivacyRequestTypeDisableResponse(BaseModel):
    """PrivacyRequestType disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[PrivacyRequestType] = None


class PrivacyRequestTypeGetResponse(BaseModel):
    """PrivacyRequestType get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[PrivacyRequestType] = None


class PrivacyRequestTypeListResponse(BaseModel):
    """PrivacyRequestType list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[PrivacyRequestType]] = None
    next_token: Optional[str] = None
