# AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for PrivacyRequests
"""

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import List, Optional
from datetime import datetime

from ..enums.legal_basis_enum import LegalBasis
from ..enums.privacy_request_status_enum import PrivacyRequestStatus
from ..enums.privacy_request_type_enum import PrivacyRequestType


# Main Model
class PrivacyRequests(BaseModel):
    """PrivacyRequests model."""

    model_config = ConfigDict(from_attributes=True)

    request_id: str = Field(..., description="Unique identifier for the privacy request")
    organization_id: str = Field(..., description="ID of the organization handling the request")
    request_type: PrivacyRequestType = Field(..., description="Type of privacy request (DATA_ACCESS, DATA_DELETION, etc.)")
    status: PrivacyRequestStatus = Field(..., description="Current status of the request")
    data_subject_email: str = Field(..., description="Email of the data subject making the request")
    data_subject_name: Optional[str] = Field(None, description="Name of the data subject")
    legal_basis: LegalBasis = Field(..., description="Legal basis for the request (GDPR Article, CCPA Right, etc.)")
    description: Optional[str] = Field(None, description="Additional details about the request")
    received_at: datetime = Field(..., description="When the request was received")
    deadline: datetime = Field(..., description="Deadline for completing the request")
    completed_at: Optional[datetime] = Field(None, description="When the request was completed")
    assigned_to: Optional[str] = Field(None, description="ID of the employee assigned to handle the request")
    notes: Optional[str] = Field(None, description="Internal notes about the request")
    created_at: datetime = Field(..., description="When the record was created")
    updated_at: datetime = Field(..., description="When the record was last updated")

    @field_validator("received_at", mode="before")
    @classmethod
    def parse_received_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

    @field_validator("deadline", mode="before")
    @classmethod
    def parse_deadline(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

    @field_validator("completed_at", mode="before")
    @classmethod
    def parse_completed_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

    @field_validator("created_at", mode="before")
    @classmethod
    def parse_created_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

    @field_validator("updated_at", mode="before")
    @classmethod
    def parse_updated_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value


# Response Types
class PrivacyRequestsCreateResponse(BaseModel):
    """PrivacyRequests create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[PrivacyRequests] = None


class PrivacyRequestsUpdateResponse(BaseModel):
    """PrivacyRequests update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[PrivacyRequests] = None


class PrivacyRequestsDeleteResponse(BaseModel):
    """PrivacyRequests delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[PrivacyRequests] = None


class PrivacyRequestsDisableResponse(BaseModel):
    """PrivacyRequests disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[PrivacyRequests] = None


class PrivacyRequestsGetResponse(BaseModel):
    """PrivacyRequests get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[PrivacyRequests] = None


class PrivacyRequestsListResponse(BaseModel):
    """PrivacyRequests list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[PrivacyRequests]] = None
    next_token: Optional[str] = None
