# AUTO-GENERATED by orb-schema-generator v0.18.1 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for Roles
"""

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import List, Optional
from datetime import datetime

from ..enums.role_status_enum import RoleStatus
from ..enums.role_type_enum import RoleType

# CRUD Input Types
class RolesCreateInput(BaseModel):
    """Roles create input."""

    role_id: str = Field(..., description="Unique identifier for the role (primary key)")
    user_id: Optional[str] = Field(None, description="(Deprecated) ID of the user this role belongs to. Use ApplicationRoles for user-role mapping.")
    role_type: RoleType = Field(..., description="Type of the role")
    status: RoleStatus = Field(..., description="Current status of the role")
    created_at: datetime = Field(..., description="When the role was created")
    updated_at: datetime = Field(..., description="When the role was last updated")


class RolesUpdateInput(BaseModel):
    """Roles update input."""

    role_id: Optional[str] = Field(..., description="Unique identifier for the role (primary key)")
    user_id: Optional[str] = Field(None, description="(Deprecated) ID of the user this role belongs to. Use ApplicationRoles for user-role mapping.")
    role_type: Optional[RoleType] = Field(..., description="Type of the role")
    status: Optional[RoleStatus] = Field(..., description="Current status of the role")
    created_at: Optional[datetime] = Field(..., description="When the role was created")
    updated_at: Optional[datetime] = Field(..., description="When the role was last updated")


class RolesDeleteInput(BaseModel):
    """Roles delete input."""

    role_id: str


class RolesDisableInput(BaseModel):
    """Roles disable input."""

    role_id: str
    disabled: bool


# Query Input Types
class RolesQueryByRoleIdInput(BaseModel):
    """Roles query by roleId."""

    role_id: str


class RolesQueryByUserIdInput(BaseModel):
    """Roles query by userId."""

    user_id: str


# Main Model
class Roles(BaseModel):
    """Roles model."""

    model_config = ConfigDict(from_attributes=True)

    role_id: str = Field(..., description="Unique identifier for the role (primary key)")
    user_id: Optional[str] = Field(None, description="(Deprecated) ID of the user this role belongs to. Use ApplicationRoles for user-role mapping.")
    role_type: RoleType = Field(..., description="Type of the role")
    status: RoleStatus = Field(..., description="Current status of the role")
    created_at: datetime = Field(..., description="When the role was created")
    updated_at: datetime = Field(..., description="When the role was last updated")

    @field_validator("created_at", mode="before")
    @classmethod
    def parse_created_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

    @field_validator("updated_at", mode="before")
    @classmethod
    def parse_updated_at(cls, value):
        """Parse timestamp to epoch seconds."""
        if value is None:
            return None
        if isinstance(value, int):
            return value
        if isinstance(value, float):
            return int(value)
        if isinstance(value, datetime):
            return int(value.timestamp())
        if isinstance(value, str):
            try:
                dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return int(dt.timestamp())
            except (ValueError, TypeError):
                pass
        return value

# Response Types
class RolesResponse(BaseModel):
    """Roles response."""

    StatusCode: int
    Message: Optional[str] = None
    Data: Optional[Roles] = None


class RolesListResponse(BaseModel):
    """Roles list response."""

    StatusCode: int
    Message: Optional[str] = None
    Data: Optional[List[Roles]] = None


# CRUD Response Aliases
RolesCreateResponse = RolesResponse
RolesUpdateResponse = RolesResponse
RolesDeleteResponse = RolesResponse
RolesDisableResponse = RolesResponse