# AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for SchemaType
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional


# Main Model
class SchemaType(BaseModel):
    """SchemaType model."""

    model_config = ConfigDict(from_attributes=True)

    value: str = Field(..., description="Registry item value")


# Response Types
class SchemaTypeCreateResponse(BaseModel):
    """SchemaType create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[SchemaType] = None


class SchemaTypeUpdateResponse(BaseModel):
    """SchemaType update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[SchemaType] = None


class SchemaTypeDeleteResponse(BaseModel):
    """SchemaType delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[SchemaType] = None


class SchemaTypeDisableResponse(BaseModel):
    """SchemaType disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[SchemaType] = None


class SchemaTypeGetResponse(BaseModel):
    """SchemaType get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[SchemaType] = None


class SchemaTypeListResponse(BaseModel):
    """SchemaType list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[SchemaType]] = None
    next_token: Optional[str] = None
