# AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for UserGroup
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional


# Main Model
class UserGroup(BaseModel):
    """UserGroup model."""

    model_config = ConfigDict(from_attributes=True)

    value: str = Field(..., description="Registry item value")


# Response Types
class UserGroupCreateResponse(BaseModel):
    """UserGroup create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[UserGroup] = None


class UserGroupUpdateResponse(BaseModel):
    """UserGroup update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[UserGroup] = None


class UserGroupDeleteResponse(BaseModel):
    """UserGroup delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[UserGroup] = None


class UserGroupDisableResponse(BaseModel):
    """UserGroup disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[UserGroup] = None


class UserGroupGetResponse(BaseModel):
    """UserGroup get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[UserGroup] = None


class UserGroupListResponse(BaseModel):
    """UserGroup list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[UserGroup]] = None
    next_token: Optional[str] = None
