# AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python models for WebhookEventType
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional


# Main Model
class WebhookEventType(BaseModel):
    """WebhookEventType model."""

    model_config = ConfigDict(from_attributes=True)

    value: str = Field(..., description="Registry item value")


# Response Types
class WebhookEventTypeCreateResponse(BaseModel):
    """WebhookEventType create response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[WebhookEventType] = None


class WebhookEventTypeUpdateResponse(BaseModel):
    """WebhookEventType update response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[WebhookEventType] = None


class WebhookEventTypeDeleteResponse(BaseModel):
    """WebhookEventType delete response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[WebhookEventType] = None


class WebhookEventTypeDisableResponse(BaseModel):
    """WebhookEventType disable response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[WebhookEventType] = None


class WebhookEventTypeGetResponse(BaseModel):
    """WebhookEventType get response."""

    code: int
    success: bool
    message: Optional[str] = None
    item: Optional[WebhookEventType] = None


class WebhookEventTypeListResponse(BaseModel):
    """WebhookEventType list response."""

    code: int
    success: bool
    message: Optional[str] = None
    items: Optional[List[WebhookEventType]] = None
    next_token: Optional[str] = None
