# Auto-generated by generate.py. Do not edit manually.
ENTITY_TABLE_ENV = {
    "ApplicationUsers": "APPLICATIONUSERS_TABLE",
    "ApplicationRoles": "APPLICATIONROLES_TABLE",
    "Roles": "ROLES_TABLE",
    "Applications": "APPLICATIONS_TABLE",
    "Users": "USERS_TABLE",
}
