// Auto-generated GraphQL operations for ApplicationRoles
// Do not edit manually. Generated by generate.py

export const ApplicationrolesQueryByApplicationId = /* GraphQL */ `

  query ApplicationrolesQueryByApplicationId($input: ApplicationrolesQueryByApplicationIdInput!) {
    ApplicationrolesQueryByApplicationId(input: $input) {
      StatusCode
      Message
      Data {
        ...fields
      }
    }
  }

`;
 