// Auto-generated GraphQL operations for ApplicationUsers
// Do not edit manually. Generated by generate.py



  
    export const ApplicationUsersCreateMutation = /* GraphQL */ `
    mutation ApplicationUsersCreate($input: ApplicationUsersCreateInput!) {
  ApplicationUsersCreate(input: $input) {
    StatusCode
    Message
    Data {
      applicationUserId
      userId
      applicationId
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    
  

  
    export const ApplicationUsersUpdateMutation = /* GraphQL */ `
    mutation ApplicationUsersUpdate($input: ApplicationUsersUpdateInput!) {
  ApplicationUsersUpdate(input: $input) {
    StatusCode
    Message
    Data {
      applicationUserId
      userId
      applicationId
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    
  

  
    export const ApplicationUsersDeleteMutation = /* GraphQL */ `
    mutation ApplicationUsersDelete($id: ID!) {
  ApplicationUsersDelete(id: $id) {
    StatusCode
    Message
    Data {
      applicationUserId
      userId
      applicationId
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    
  

  
    export const ApplicationUsersDisableMutation = /* GraphQL */ `
    mutation ApplicationUsersDisable($id: ID!) {
  ApplicationUsersDisable(id: $id) {
    StatusCode
    Message
    Data {
      applicationUserId
      userId
      applicationId
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    
  

  
    export const ApplicationUsersQueryByApplicationUserId = /* GraphQL */ `
    query ApplicationUsersQueryByApplicationUserId($input: ApplicationUsersQueryByApplicationUserIdInput!) {
  ApplicationUsersQueryByApplicationUserId(input: $input) {
    StatusCode
    Message
    Data {
      applicationUserId
      userId
      applicationId
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    
  

  
    export const ApplicationUsersQueryByUserId = /* GraphQL */ `
    query ApplicationUsersQueryByUserId($input: ApplicationUsersQueryByUserIdInput!) {
  ApplicationUsersQueryByUserId(input: $input) {
    StatusCode
    Message
    Data {
      applicationUserId
      userId
      applicationId
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    
  

  
    export const ApplicationUsersQueryByApplicationId = /* GraphQL */ `
    query ApplicationUsersQueryByApplicationId($input: ApplicationUsersQueryByApplicationIdInput!) {
  ApplicationUsersQueryByApplicationId(input: $input) {
    StatusCode
    Message
    Data {
      applicationUserId
      userId
      applicationId
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    
  


// For each secondary index, generate a query operation

  
  

  
  
 