// Auto-generated GraphQL operations for Applications
// Do not edit manually. Generated by generate.py

export const ApplicationsCreateMutation = /* GraphQL */ `
mutation ApplicationsCreate($input: ApplicationsCreateInput!) {
  ApplicationsCreate(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const ApplicationsUpdateMutation = /* GraphQL */ `
mutation ApplicationsUpdate($input: ApplicationsUpdateInput!) {
  ApplicationsUpdate(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const ApplicationsDeleteMutation = /* GraphQL */ `
mutation ApplicationsDelete($input: ApplicationsDeleteInput!) {
  ApplicationsDelete(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const ApplicationsQueryByApplicationId = /* GraphQL */ `
query ApplicationsQueryByApplicationId($input: ApplicationsQueryByApplicationIdInput!) {
  ApplicationsQueryByApplicationId(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
 