// Auto-generated GraphQL operations for ApplicationRoles
// Do not edit manually. Generated by generate.py

export const ApplicationRolesCreateMutation = /* GraphQL */ `
mutation ApplicationRolesCreate($input: ApplicationRolesCreateInput!) {
  ApplicationRolesCreate(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const ApplicationRolesUpdateMutation = /* GraphQL */ `
mutation ApplicationRolesUpdate($input: ApplicationRolesUpdateInput!) {
  ApplicationRolesUpdate(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const ApplicationRolesDeleteMutation = /* GraphQL */ `
mutation ApplicationRolesDelete($id: ID!) {
  ApplicationRolesDelete(id: $id) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const ApplicationRolesQueryByApplicationId = /* GraphQL */ `
query ApplicationRolesQueryByApplicationId($input: ApplicationRolesQueryByApplicationIdInput!) {
  ApplicationRolesQueryByApplicationId(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const ApplicationRolesQueryByRoleId = /* GraphQL */ `
query ApplicationRolesQueryByRoleId($input: ApplicationRolesQueryByRoleIdInput!) {
  ApplicationRolesQueryByRoleId(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;

// For each secondary index, generate a query operation
export const ApplicationRolesQueryByRoleId = /* GraphQL */ `
query ApplicationRolesQueryByRoleId($input: ApplicationRolesQueryByRoleIdInput!) {
  ApplicationRolesQueryByRoleId(input: $input) {
    StatusCode
    Message
    Data {
      // ...fields
    }
  }
}
`;
 