// Auto-generated GraphQL operations for ApplicationUsers
// Do not edit manually. Generated by generate.py

export const ApplicationUsersCreateMutation = /* GraphQL */ `
mutation ApplicationUsersCreate($input: ApplicationUsersCreateInput!) {
  ApplicationUsersCreate(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const ApplicationUsersUpdateMutation = /* GraphQL */ `
mutation ApplicationUsersUpdate($input: ApplicationUsersUpdateInput!) {
  ApplicationUsersUpdate(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const ApplicationUsersDeleteMutation = /* GraphQL */ `
mutation ApplicationUsersDelete($input: ApplicationUsersDeleteInput!) {
  ApplicationUsersDelete(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const ApplicationUsersQueryByApplicationId = /* GraphQL */ `
query ApplicationUsersQueryByApplicationId($input: ApplicationUsersQueryByApplicationIdInput!) {
  ApplicationUsersQueryByApplicationId(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
 