// Auto-generated GraphQL operations for OwnershipTransferRequests (Lambda-backed)
// Do not edit manually. Generated by generate.py




export const OwnershipTransferRequestsCreateMutation = /* GraphQL */ `
mutation OwnershipTransferRequestsCreate($input: OwnershipTransferRequestsCreateInput!) {
  OwnershipTransferRequestsCreate(input: $input) {
    StatusCode
    Message
    Data {
      transferId
      currentOwnerId
      newOwnerId
      organizationId
      status
      requiredBillingPlan
      monthlyCost
      paymentValidationToken
      createdAt
      expiresAt
      updatedAt
      completedAt
      failureReason
      billingTransitionDetails
      fraudAssessment
      notificationsSent
    }
  }
}
`;





export const OwnershipTransferRequestsUpdateMutation = /* GraphQL */ `
mutation OwnershipTransferRequestsUpdate($input: OwnershipTransferRequestsUpdateInput!) {
  OwnershipTransferRequestsUpdate(input: $input) {
    StatusCode
    Message
    Data {
      transferId
      currentOwnerId
      newOwnerId
      organizationId
      status
      requiredBillingPlan
      monthlyCost
      paymentValidationToken
      createdAt
      expiresAt
      updatedAt
      completedAt
      failureReason
      billingTransitionDetails
      fraudAssessment
      notificationsSent
    }
  }
}
`;





export const OwnershipTransferRequestsDeleteMutation = /* GraphQL */ `
mutation OwnershipTransferRequestsDelete($id: ID!) {
  OwnershipTransferRequestsDelete(id: $id) {
    StatusCode
    Message
    Data {
      transferId
      currentOwnerId
      newOwnerId
      organizationId
      status
      requiredBillingPlan
      monthlyCost
      paymentValidationToken
      createdAt
      expiresAt
      updatedAt
      completedAt
      failureReason
      billingTransitionDetails
      fraudAssessment
      notificationsSent
    }
  }
}
`;





export const OwnershipTransferRequestsDisableMutation = /* GraphQL */ `
mutation OwnershipTransferRequestsDisable($id: ID!) {
  OwnershipTransferRequestsDisable(id: $id) {
    StatusCode
    Message
    Data {
      transferId
      currentOwnerId
      newOwnerId
      organizationId
      status
      requiredBillingPlan
      monthlyCost
      paymentValidationToken
      createdAt
      expiresAt
      updatedAt
      completedAt
      failureReason
      billingTransitionDetails
      fraudAssessment
      notificationsSent
    }
  }
}
`;





export const OwnershipTransferRequestsQueryByTransferId = /* GraphQL */ `
query OwnershipTransferRequestsQueryByTransferId($input: OwnershipTransferRequestsQueryByTransferIdInput!) {
  OwnershipTransferRequestsQueryByTransferId(input: $input) {
    StatusCode
    Message
    Data {
      transferId
      currentOwnerId
      newOwnerId
      organizationId
      status
      requiredBillingPlan
      monthlyCost
      paymentValidationToken
      createdAt
      expiresAt
      updatedAt
      completedAt
      failureReason
      billingTransitionDetails
      fraudAssessment
      notificationsSent
    }
  }
}
`;





export const OwnershipTransferRequestsQueryByCurrentOwnerId = /* GraphQL */ `
query OwnershipTransferRequestsQueryByCurrentOwnerId($input: OwnershipTransferRequestsQueryByCurrentOwnerIdInput!) {
  OwnershipTransferRequestsQueryByCurrentOwnerId(input: $input) {
    StatusCode
    Message
    Data {
      transferId
      currentOwnerId
      newOwnerId
      organizationId
      status
      requiredBillingPlan
      monthlyCost
      paymentValidationToken
      createdAt
      expiresAt
      updatedAt
      completedAt
      failureReason
      billingTransitionDetails
      fraudAssessment
      notificationsSent
    }
  }
}
`;





export const OwnershipTransferRequestsQueryByCurrentOwnerIdAndCreatedAt = /* GraphQL */ `
query OwnershipTransferRequestsQueryByCurrentOwnerIdAndCreatedAt($input: OwnershipTransferRequestsQueryByCurrentOwnerIdAndCreatedAtInput!) {
  OwnershipTransferRequestsQueryByCurrentOwnerIdAndCreatedAt(input: $input) {
    StatusCode
    Message
    Data {
      transferId
      currentOwnerId
      newOwnerId
      organizationId
      status
      requiredBillingPlan
      monthlyCost
      paymentValidationToken
      createdAt
      expiresAt
      updatedAt
      completedAt
      failureReason
      billingTransitionDetails
      fraudAssessment
      notificationsSent
    }
  }
}
`;





export const OwnershipTransferRequestsQueryByNewOwnerId = /* GraphQL */ `
query OwnershipTransferRequestsQueryByNewOwnerId($input: OwnershipTransferRequestsQueryByNewOwnerIdInput!) {
  OwnershipTransferRequestsQueryByNewOwnerId(input: $input) {
    StatusCode
    Message
    Data {
      transferId
      currentOwnerId
      newOwnerId
      organizationId
      status
      requiredBillingPlan
      monthlyCost
      paymentValidationToken
      createdAt
      expiresAt
      updatedAt
      completedAt
      failureReason
      billingTransitionDetails
      fraudAssessment
      notificationsSent
    }
  }
}
`;





export const OwnershipTransferRequestsQueryByNewOwnerIdAndCreatedAt = /* GraphQL */ `
query OwnershipTransferRequestsQueryByNewOwnerIdAndCreatedAt($input: OwnershipTransferRequestsQueryByNewOwnerIdAndCreatedAtInput!) {
  OwnershipTransferRequestsQueryByNewOwnerIdAndCreatedAt(input: $input) {
    StatusCode
    Message
    Data {
      transferId
      currentOwnerId
      newOwnerId
      organizationId
      status
      requiredBillingPlan
      monthlyCost
      paymentValidationToken
      createdAt
      expiresAt
      updatedAt
      completedAt
      failureReason
      billingTransitionDetails
      fraudAssessment
      notificationsSent
    }
  }
}
`;





export const OwnershipTransferRequestsQueryByStatus = /* GraphQL */ `
query OwnershipTransferRequestsQueryByStatus($input: OwnershipTransferRequestsQueryByStatusInput!) {
  OwnershipTransferRequestsQueryByStatus(input: $input) {
    StatusCode
    Message
    Data {
      transferId
      currentOwnerId
      newOwnerId
      organizationId
      status
      requiredBillingPlan
      monthlyCost
      paymentValidationToken
      createdAt
      expiresAt
      updatedAt
      completedAt
      failureReason
      billingTransitionDetails
      fraudAssessment
      notificationsSent
    }
  }
}
`;





export const OwnershipTransferRequestsQueryByStatusAndCreatedAt = /* GraphQL */ `
query OwnershipTransferRequestsQueryByStatusAndCreatedAt($input: OwnershipTransferRequestsQueryByStatusAndCreatedAtInput!) {
  OwnershipTransferRequestsQueryByStatusAndCreatedAt(input: $input) {
    StatusCode
    Message
    Data {
      transferId
      currentOwnerId
      newOwnerId
      organizationId
      status
      requiredBillingPlan
      monthlyCost
      paymentValidationToken
      createdAt
      expiresAt
      updatedAt
      completedAt
      failureReason
      billingTransitionDetails
      fraudAssessment
      notificationsSent
    }
  }
}
`;





export const OwnershipTransferRequestsQueryByStatusAndExpiresAt = /* GraphQL */ `
query OwnershipTransferRequestsQueryByStatusAndExpiresAt($input: OwnershipTransferRequestsQueryByStatusAndExpiresAtInput!) {
  OwnershipTransferRequestsQueryByStatusAndExpiresAt(input: $input) {
    StatusCode
    Message
    Data {
      transferId
      currentOwnerId
      newOwnerId
      organizationId
      status
      requiredBillingPlan
      monthlyCost
      paymentValidationToken
      createdAt
      expiresAt
      updatedAt
      completedAt
      failureReason
      billingTransitionDetails
      fraudAssessment
      notificationsSent
    }
  }
}
`;





// The operations above already include all queries generated by the schema