// Auto-generated GraphQL operations for PrivacyRequests (Lambda-backed)
// Do not edit manually. Generated by generate.py

export const PrivacyRequestsCreateMutation = /* GraphQL */ `
mutation PrivacyRequestsCreate($input: PrivacyRequestsCreateInput!) {
  PrivacyRequestsCreate(input: $input) {
    StatusCode
    Message
    Data {
      requestId
      requestType
      dataSubjectEmail
      legalBasis
      organizationId
      requesterId
      status
      receivedAt
      deadline
      completedAt
      estimatedCompletion
      automatedProcessing
      accessReport
      deletionResult
      portableData
      rejectionReason
      errorDetails
      complianceNotes
      createdAt
      updatedAt
    }
  }
}
`;

export const PrivacyRequestsUpdateMutation = /* GraphQL */ `
mutation PrivacyRequestsUpdate($input: PrivacyRequestsUpdateInput!) {
  PrivacyRequestsUpdate(input: $input) {
    StatusCode
    Message
    Data {
      requestId
      requestType
      dataSubjectEmail
      legalBasis
      organizationId
      requesterId
      status
      receivedAt
      deadline
      completedAt
      estimatedCompletion
      automatedProcessing
      accessReport
      deletionResult
      portableData
      rejectionReason
      errorDetails
      complianceNotes
      createdAt
      updatedAt
    }
  }
}
`;

export const PrivacyRequestsDeleteMutation = /* GraphQL */ `
mutation PrivacyRequestsDelete($id: ID!) {
  PrivacyRequestsDelete(id: $id) {
    StatusCode
    Message
    Data {
      requestId
      requestType
      dataSubjectEmail
      legalBasis
      organizationId
      requesterId
      status
      receivedAt
      deadline
      completedAt
      estimatedCompletion
      automatedProcessing
      accessReport
      deletionResult
      portableData
      rejectionReason
      errorDetails
      complianceNotes
      createdAt
      updatedAt
    }
  }
}
`;

export const PrivacyRequestsDisableMutation = /* GraphQL */ `
mutation PrivacyRequestsDisable($id: ID!) {
  PrivacyRequestsDisable(id: $id) {
    StatusCode
    Message
    Data {
      requestId
      requestType
      dataSubjectEmail
      legalBasis
      organizationId
      requesterId
      status
      receivedAt
      deadline
      completedAt
      estimatedCompletion
      automatedProcessing
      accessReport
      deletionResult
      portableData
      rejectionReason
      errorDetails
      complianceNotes
      createdAt
      updatedAt
    }
  }
}
`;

export const PrivacyRequestsQueryByRequestId = /* GraphQL */ `
query PrivacyRequestsQueryByRequestId($input: PrivacyRequestsQueryByRequestIdInput!) {
  PrivacyRequestsQueryByRequestId(input: $input) {
    StatusCode
    Message
    Data {
      requestId
      requestType
      dataSubjectEmail
      legalBasis
      organizationId
      requesterId
      status
      receivedAt
      deadline
      completedAt
      estimatedCompletion
      automatedProcessing
      accessReport
      deletionResult
      portableData
      rejectionReason
      errorDetails
      complianceNotes
      createdAt
      updatedAt
    }
  }
}
`;

export const PrivacyRequestsQueryByRequestType = /* GraphQL */ `
query PrivacyRequestsQueryByRequestType($input: PrivacyRequestsQueryByRequestTypeInput!) {
  PrivacyRequestsQueryByRequestType(input: $input) {
    StatusCode
    Message
    Data {
      requestId
      requestType
      dataSubjectEmail
      legalBasis
      organizationId
      requesterId
      status
      receivedAt
      deadline
      completedAt
      estimatedCompletion
      automatedProcessing
      accessReport
      deletionResult
      portableData
      rejectionReason
      errorDetails
      complianceNotes
      createdAt
      updatedAt
    }
  }
}
`;

export const PrivacyRequestsQueryByDataSubjectEmail = /* GraphQL */ `
query PrivacyRequestsQueryByDataSubjectEmail($input: PrivacyRequestsQueryByDataSubjectEmailInput!) {
  PrivacyRequestsQueryByDataSubjectEmail(input: $input) {
    StatusCode
    Message
    Data {
      requestId
      requestType
      dataSubjectEmail
      legalBasis
      organizationId
      requesterId
      status
      receivedAt
      deadline
      completedAt
      estimatedCompletion
      automatedProcessing
      accessReport
      deletionResult
      portableData
      rejectionReason
      errorDetails
      complianceNotes
      createdAt
      updatedAt
    }
  }
}
`;

export const PrivacyRequestsQueryByOrganizationId = /* GraphQL */ `
query PrivacyRequestsQueryByOrganizationId($input: PrivacyRequestsQueryByOrganizationIdInput!) {
  PrivacyRequestsQueryByOrganizationId(input: $input) {
    StatusCode
    Message
    Data {
      requestId
      requestType
      dataSubjectEmail
      legalBasis
      organizationId
      requesterId
      status
      receivedAt
      deadline
      completedAt
      estimatedCompletion
      automatedProcessing
      accessReport
      deletionResult
      portableData
      rejectionReason
      errorDetails
      complianceNotes
      createdAt
      updatedAt
    }
  }
}
`;

export const PrivacyRequestsQueryByStatus = /* GraphQL */ `
query PrivacyRequestsQueryByStatus($input: PrivacyRequestsQueryByStatusInput!) {
  PrivacyRequestsQueryByStatus(input: $input) {
    StatusCode
    Message
    Data {
      requestId
      requestType
      dataSubjectEmail
      legalBasis
      organizationId
      requesterId
      status
      receivedAt
      deadline
      completedAt
      estimatedCompletion
      automatedProcessing
      accessReport
      deletionResult
      portableData
      rejectionReason
      errorDetails
      complianceNotes
      createdAt
      updatedAt
    }
  }
}
`;


// The operations above already include all queries generated by the schema