// Auto-generated GraphQL operations for Roles
// Do not edit manually. Generated by generate.py

    export const RolesCreateMutation = /* GraphQL */ `
    mutation RolesCreate($input: RolesCreateInput!) {
  RolesCreate(input: $input) {
    StatusCode
    Message
    Data {
      roleId
      userId
      applicationId
      roleName
      roleType
      permissions
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    export const RolesUpdateMutation = /* GraphQL */ `
    mutation RolesUpdate($input: RolesUpdateInput!) {
  RolesUpdate(input: $input) {
    StatusCode
    Message
    Data {
      roleId
      userId
      applicationId
      roleName
      roleType
      permissions
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    export const RolesDeleteMutation = /* GraphQL */ `
    mutation RolesDelete($id: ID!) {
  RolesDelete(id: $id) {
    StatusCode
    Message
    Data {
      roleId
      userId
      applicationId
      roleName
      roleType
      permissions
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    export const RolesQueryByRoleId = /* GraphQL */ `
    query RolesQueryByRoleId($input: RolesQueryByRoleIdInput!) {
  RolesQueryByRoleId(input: $input) {
    StatusCode
    Message
    Data {
      roleId
      userId
      applicationId
      roleName
      roleType
      permissions
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    export const RolesQueryByUserId = /* GraphQL */ `
    query RolesQueryByUserId($input: RolesQueryByUserIdInput!) {
  RolesQueryByUserId(input: $input) {
    StatusCode
    Message
    Data {
      roleId
      userId
      applicationId
      roleName
      roleType
      permissions
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    export const RolesQueryByApplicationId = /* GraphQL */ `
    query RolesQueryByApplicationId($input: RolesQueryByApplicationIdInput!) {
  RolesQueryByApplicationId(input: $input) {
    StatusCode
    Message
    Data {
      roleId
      userId
      applicationId
      roleName
      roleType
      permissions
      status
      createdAt
      updatedAt
    }
  }
}
    `;

// For each secondary index, generate a query operation
 