// Auto-generated GraphQL operations for Roles
// Do not edit manually. Generated by generate.py

export const RolesCreateMutation = /* GraphQL */ `
mutation RolesCreate($input: RolesCreateInput!) {
  RolesCreate(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const RolesUpdateMutation = /* GraphQL */ `
mutation RolesUpdate($input: RolesUpdateInput!) {
  RolesUpdate(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const RolesDeleteMutation = /* GraphQL */ `
mutation RolesDelete($input: RolesDeleteInput!) {
  RolesDelete(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const RolesQueryByRoleId = /* GraphQL */ `
query RolesQueryByRoleId($input: RolesQueryByRoleIdInput!) {
  RolesQueryByRoleId(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
 