// Auto-generated GraphQL operations for Roles
// Do not edit manually. Generated by generate.py

export const RolesQueryByRoleId = /* GraphQL */ `

  query RolesQueryByRoleId($input: RolesQueryByRoleIdInput!) {
    RolesQueryByRoleId(input: $input) {
      StatusCode
      Message
      Data {
        ...fields
      }
    }
  }

`;
 