// Auto-generated GraphQL operations for SmsRateLimit
// Do not edit manually. Generated by generate.py




export const SmsRateLimitCreateMutation = /* GraphQL */ `
mutation SmsRateLimitCreate($input: SmsRateLimitCreateInput!) {
  SmsRateLimitCreate(input: $input) {
    StatusCode
    Message
    Data {
      phoneNumber
      requestCount
      firstRequestTime
      ttl
    }
  }
}
`;





export const SmsRateLimitUpdateMutation = /* GraphQL */ `
mutation SmsRateLimitUpdate($input: SmsRateLimitUpdateInput!) {
  SmsRateLimitUpdate(input: $input) {
    StatusCode
    Message
    Data {
      phoneNumber
      requestCount
      firstRequestTime
      ttl
    }
  }
}
`;





export const SmsRateLimitDeleteMutation = /* GraphQL */ `
mutation SmsRateLimitDelete($id: ID!) {
  SmsRateLimitDelete(id: $id) {
    StatusCode
    Message
    Data {
      phoneNumber
      requestCount
      firstRequestTime
      ttl
    }
  }
}
`;





export const SmsRateLimitDisableMutation = /* GraphQL */ `
mutation SmsRateLimitDisable($id: ID!) {
  SmsRateLimitDisable(id: $id) {
    StatusCode
    Message
    Data {
      phoneNumber
      requestCount
      firstRequestTime
      ttl
    }
  }
}
`;





export const SmsRateLimitQueryByPhoneNumber = /* GraphQL */ `
query SmsRateLimitQueryByPhoneNumber($input: SmsRateLimitQueryByPhoneNumberInput!) {
  SmsRateLimitQueryByPhoneNumber(input: $input) {
    StatusCode
    Message
    Data {
      phoneNumber
      requestCount
      firstRequestTime
      ttl
    }
  }
}
`;





// For each secondary index, generate a query operation
 