// Auto-generated GraphQL operations for Users
// Do not edit manually. Generated by generate.py

export const UsersCreateMutation = /* GraphQL */ `
mutation UsersCreate($input: UsersCreateInput!) {
  UsersCreate(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const UsersUpdateMutation = /* GraphQL */ `
mutation UsersUpdate($input: UsersUpdateInput!) {
  UsersUpdate(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const UsersDeleteMutation = /* GraphQL */ `
mutation UsersDelete($input: UsersDeleteInput!) {
  UsersDelete(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
export const UsersQueryByUserId = /* GraphQL */ `
query UsersQueryByUserId($input: UsersQueryByUserIdInput!) {
  UsersQueryByUserId(input: $input) {
    StatusCode
    Message
    Data { ...fields }
  }
}
`;
 