// Auto-generated GraphQL operations for Users
// Do not edit manually. Generated by generate.py

    export const UsersCreateMutation = /* GraphQL */ `
    mutation UsersCreate($input: UsersCreateInput!) {
  UsersCreate(input: $input) {
    StatusCode
    Message
    Data {
      id
      email
      firstName
      lastName
      roleId
      roleType
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    export const UsersUpdateMutation = /* GraphQL */ `
    mutation UsersUpdate($input: UsersUpdateInput!) {
  UsersUpdate(input: $input) {
    StatusCode
    Message
    Data {
      id
      email
      firstName
      lastName
      roleId
      roleType
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    export const UsersDeleteMutation = /* GraphQL */ `
    mutation UsersDelete($id: ID!) {
  UsersDelete(id: $id) {
    StatusCode
    Message
    Data {
      id
      email
      firstName
      lastName
      roleId
      roleType
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    export const UsersQueryById = /* GraphQL */ `
    query UsersQueryById($input: UsersQueryByIdInput!) {
  UsersQueryById(input: $input) {
    StatusCode
    Message
    Data {
      id
      email
      firstName
      lastName
      roleId
      roleType
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    export const UsersQueryByEmail = /* GraphQL */ `
    query UsersQueryByEmail($input: UsersQueryByEmailInput!) {
  UsersQueryByEmail(input: $input) {
    StatusCode
    Message
    Data {
      id
      email
      firstName
      lastName
      roleId
      roleType
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    export const UsersQueryByBoth = /* GraphQL */ `
    query UsersQueryByBoth($input: UsersQueryByBothInput!) {
  UsersQueryByBoth(input: $input) {
    StatusCode
    Message
    Data {
      id
      email
      firstName
      lastName
      roleId
      roleType
      status
      createdAt
      updatedAt
    }
  }
}
    `;
    export const UsersQueryByRoleId = /* GraphQL */ `
    query UsersQueryByRoleId($input: UsersQueryByRoleIdInput!) {
  UsersQueryByRoleId(input: $input) {
    StatusCode
    Message
    Data {
      id
      email
      firstName
      lastName
      roleId
      roleType
      status
      createdAt
      updatedAt
    }
  }
}
    `;

// For each secondary index, generate a query operation
 