// Auto-generated GraphQL operations for Users
// Do not edit manually. Generated by generate.py

export const UsersQueryByUserId = /* GraphQL */ `

  query UsersQueryByUserId($input: UsersQueryByUserIdInput!) {
    UsersQueryByUserId(input: $input) {
      StatusCode
      Message
      Data {
        ...fields
      }
    }
  }

`;
 