# --------------------------------------------------- #
AWSTemplateFormatVersion: 2010-09-09

# --------------------------------------------------- #
Transform: AWS::Serverless-2016-10-31

# --------------------------------------------------- #
Description: >
 Application Infrastructure - DynamoDB Tables

# --------------------------------------------------- #
Parameters:
  Environment:
    Default: dev
    Type: String
  CustomerId:
    Default: orb
    Type: String
  ProjectId:
    Default: integration-hub
    Type: String
  TracingIs:
    Default: Active
    Type: String

# --------------------------------------------------- #
Resources:
  
  # Roles Table
  RolesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: role_id
          AttributeType: S
        - AttributeName: application_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: role_type
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: role_id
          KeyType: HASH
        - AttributeName: application_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: user-role-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: role_id
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - role_name
              - role_type
              - permissions
        - IndexName: application-role-index
          KeySchema:
            - AttributeName: application_id
              KeyType: HASH
            - AttributeName: role_id
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
      LocalSecondaryIndexes:
        - IndexName: role-type-index
          KeySchema:
            - AttributeName: role_id
              KeyType: HASH
            - AttributeName: role_type
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TableName: !Sub '${CustomerId}-${ProjectId}-${Environment}-roles'
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  # Parameter Store for Roles table name
  RolesTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-roles-table-name'
      Type: String
      Value: !Ref RolesTable
      Description: DynamoDB Roles Table Name
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId

  # Parameter Store for Roles table ARN
  RolesTableArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-roles-table-arn'
      Type: String
      Value: !GetAtt RolesTable.Arn
      Description: DynamoDB Roles Table Arn
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
  
  # Users Table
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: cognito_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: cognito_id-index
          KeySchema:
            - AttributeName: cognito_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TableName: !Sub '${CustomerId}-${ProjectId}-${Environment}-users'
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  # Parameter Store for Users table name
  UsersTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-users-table-name'
      Type: String
      Value: !Ref UsersTable
      Description: DynamoDB Users Table Name
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId

  # Parameter Store for Users table ARN
  UsersTableArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-users-table-arn'
      Type: String
      Value: !GetAtt UsersTable.Arn
      Description: DynamoDB Users Table Arn
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
  
  # Applications Table
  ApplicationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: application_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: application_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user_id-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: application_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TableName: !Sub '${CustomerId}-${ProjectId}-${Environment}-applications'
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  # Parameter Store for Applications table name
  ApplicationsTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-applications-table-name'
      Type: String
      Value: !Ref ApplicationsTable
      Description: DynamoDB Applications Table Name
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId

  # Parameter Store for Applications table ARN
  ApplicationsTableArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-applications-table-arn'
      Type: String
      Value: !GetAtt ApplicationsTable.Arn
      Description: DynamoDB Applications Table Arn
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
  
  # ApplicationUsers Table
  ApplicationUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: application_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: application_role_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: application_id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: user-applications-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: application_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: application-role-index
          KeySchema:
            - AttributeName: application_id
              KeyType: HASH
            - AttributeName: application_role_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TableName: !Sub '${CustomerId}-${ProjectId}-${Environment}-application_users'
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  # Parameter Store for ApplicationUsers table name
  ApplicationUsersTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-application_users-table-name'
      Type: String
      Value: !Ref ApplicationUsersTable
      Description: DynamoDB ApplicationUsers Table Name
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId

  # Parameter Store for ApplicationUsers table ARN
  ApplicationUsersTableArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-application_users-table-arn'
      Type: String
      Value: !GetAtt ApplicationUsersTable.Arn
      Description: DynamoDB ApplicationUsers Table Arn
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
  
  # ApplicationRoles Table
  ApplicationRolesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: application_id
          AttributeType: S
        - AttributeName: role_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: application_id
          KeyType: HASH
        - AttributeName: role_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: role-status-index
          KeySchema:
            - AttributeName: application_id
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TableName: !Sub '${CustomerId}-${ProjectId}-${Environment}-application_roles'
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  # Parameter Store for ApplicationRoles table name
  ApplicationRolesTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-application_roles-table-name'
      Type: String
      Value: !Ref ApplicationRolesTable
      Description: DynamoDB ApplicationRoles Table Name
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId

  # Parameter Store for ApplicationRoles table ARN
  ApplicationRolesTableArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-application_roles-table-arn'
      Type: String
      Value: !GetAtt ApplicationRolesTable.Arn
      Description: DynamoDB ApplicationRoles Table Arn
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
  