AWSTemplateFormatVersion: '2010-09-09'
Description: Application Infrastructure
Parameters:
  CustomerId:
    Default: orb
    Type: String
  Environment:
    Default: dev
    Type: String
  ProjectId:
    Default: integration-hub
    Type: String
  TracingIs:
    Default: Active
    Type: String
Resources:
  RolesTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: role_id
        AttributeType: S
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: application_id
        AttributeType: S
      - AttributeName: role_type
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
      - IndexName: user-role-index
        KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: role_id
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - role_name
          - role_type
          - permissions
          ProjectionType: INCLUDE
      - IndexName: application-role-index
        KeySchema:
        - AttributeName: application_id
          KeyType: HASH
        - AttributeName: role_id
          KeyType: RANGE
        Projection:
          ProjectionType: KEYS_ONLY
      KeySchema:
      - AttributeName: role_id
        KeyType: HASH
      LocalSecondaryIndexes:
      - IndexName: role-type-index
        KeySchema:
        - AttributeName: role_id
          KeyType: HASH
        - AttributeName: role_type
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      TableName:
        Fn::Sub: ${CustomerId}-${ProjectId}-${Environment}-roles
      Tags:
      - Key: Billable
        Value: 'true'
      - Key: CustomerId
        Value:
          Ref: CustomerId
      - Key: Environment
        Value:
          Ref: Environment
      - Key: ProjectId
        Value:
          Ref: ProjectId
    Type: AWS::DynamoDB::Table
  RolesTableArnParameter:
    Properties:
      Description: DynamoDB Roles Table Arn
      Name:
        Fn::Sub: ${CustomerId}-${ProjectId}-${Environment}-roles-table-arn
      Tags:
        Billable: 'true'
        CustomerId:
          Ref: CustomerId
        Environment:
          Ref: Environment
        ProjectId:
          Ref: ProjectId
      Type: String
      Value:
        Fn::GetAtt:
        - RolesTable
        - Arn
    Type: AWS::SSM::Parameter
  RolesTableNameParameter:
    Properties:
      Description: DynamoDB Roles Table Name
      Name:
        Fn::Sub: ${CustomerId}-${ProjectId}-${Environment}-roles-table-name
      Tags:
        Billable: 'true'
        CustomerId:
          Ref: CustomerId
        Environment:
          Ref: Environment
        ProjectId:
          Ref: ProjectId
      Type: String
      Value:
        Ref: RolesTable
    Type: AWS::SSM::Parameter
  UsersTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: email
        AttributeType: S
      - AttributeName: cognito_id
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      TableName:
        Fn::Sub: ${CustomerId}-${ProjectId}-${Environment}-users
      Tags:
      - Key: Billable
        Value: 'true'
      - Key: CustomerId
        Value:
          Ref: CustomerId
      - Key: Environment
        Value:
          Ref: Environment
      - Key: ProjectId
        Value:
          Ref: ProjectId
    Type: AWS::DynamoDB::Table
  UsersTableArnParameter:
    Properties:
      Description: DynamoDB Users Table Arn
      Name:
        Fn::Sub: ${CustomerId}-${ProjectId}-${Environment}-users-table-arn
      Tags:
        Billable: 'true'
        CustomerId:
          Ref: CustomerId
        Environment:
          Ref: Environment
        ProjectId:
          Ref: ProjectId
      Type: String
      Value:
        Fn::GetAtt:
        - UsersTable
        - Arn
    Type: AWS::SSM::Parameter
  UsersTableNameParameter:
    Properties:
      Description: DynamoDB Users Table Name
      Name:
        Fn::Sub: ${CustomerId}-${ProjectId}-${Environment}-users-table-name
      Tags:
        Billable: 'true'
        CustomerId:
          Ref: CustomerId
        Environment:
          Ref: Environment
        ProjectId:
          Ref: ProjectId
      Type: String
      Value:
        Ref: UsersTable
    Type: AWS::SSM::Parameter
Transform: AWS::Serverless-2016-10-31
