# --------------------------------------------------- #
AWSTemplateFormatVersion: 2010-09-09

# --------------------------------------------------- #
Transform: AWS::Serverless-2016-10-31

# --------------------------------------------------- #
Description: Application Infrastructure

# --------------------------------------------------- #
Parameters:
  Environment:
    Default: dev
    Type: String
  CustomerId:
    Default: orb
    Type: String
  ProjectId:
    Default: integration-hub
    Type: String
  TracingIs:
    Default: Active
    Type: String

# --------------------------------------------------- #
Resources:
  # Applications Table
  ApplicationsTable:
    Properties:
      AttributeDefinitions:
        -
          AttributeName: application_id
          AttributeType: S
        -
          AttributeName: user_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: application_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        -
          IndexName: user-id-index # gets all the applications owned by a given user
          KeySchema:
            -
              AttributeName: user_id
              KeyType: HASH
            -
              AttributeName: application_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TableName: !Sub "${CustomerId}-${ProjectId}-${Environment}-applications"
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId
    Type: AWS::DynamoDB::Table

  # Application User Roles Table
  ApplicationUsersTable:
    Properties:
      AttributeDefinitions:
        -
          AttributeName: application_id
          AttributeType: S
        -
          AttributeName: user_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema: # for a given application, get all the users
        -
          AttributeName: application_id
          KeyType: HASH
        -
          AttributeName: user_id
          KeyType: RANGE
      TableName: !Sub "${CustomerId}-${ProjectId}-${Environment}-application-users"
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId
    Type: AWS::DynamoDB::Table

  # Users Table
  UsersTable:
    Properties:
      AttributeDefinitions:
        -
          AttributeName: user_id
          AttributeType: S
        -
          AttributeName: cognito_id
          AttributeType: S
        -
          AttributeName: email
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        -
          IndexName: cognito-id-index
          KeySchema:
            -
              AttributeName: cognito_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        -
          IndexName: email-index
          KeySchema:
            -
              AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TableName: !Sub "${CustomerId}-${ProjectId}-${Environment}-users"
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId
    Type: AWS::DynamoDB::Table

  # Parameter Store
  ApplicationsTableNameParameter:
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-applications-table-name"
      Type: String
      Value: !Ref ApplicationsTable
      Description: DynamoDB Applications Table Name
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
    Type: AWS::SSM::Parameter
  ApplicationsTableArnParameter:
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-applications-table-arn"
      Type: String
      Value: !GetAtt ApplicationsTable.Arn
      Description: DynamoDB Applications Table Arn
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
    Type: AWS::SSM::Parameter
  ApplicationUsersTableNameParameter:
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-application-users-table-name"
      Type: String
      Value: !Ref ApplicationUsersTable
      Description: DynamoDB Application Users Table Name
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
    Type: AWS::SSM::Parameter
  ApplicationUsersTableArnParameter:
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-application-users-table-arn"
      Type: String
      Value: !GetAtt ApplicationUsersTable.Arn
      Description: DynamoDB Application Users Table Arn
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
    Type: AWS::SSM::Parameter
  UsersTableNameParameter:
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-users-table-name"
      Type: String
      Value: !Ref UsersTable
      Description: DynamoDB Users Table Name
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
    Type: AWS::SSM::Parameter
  UsersTableArnParameter:
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-users-table-arn"
      Type: String
      Value: !GetAtt UsersTable.Arn
      Description: DynamoDB Users Table Arn
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
    Type: AWS::SSM::Parameter


Resources:
rolesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: roles
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: role_id
        AttributeType: S
      
      
      - AttributeName: user_id
        AttributeType: S
      
      - AttributeName: role_id
        AttributeType: S
      
      
      - AttributeName: application_id
        AttributeType: S
      
      - AttributeName: role_id
        AttributeType: S
      
      
      - AttributeName: role_id
        AttributeType: S
      
      - AttributeName: role_type
        AttributeType: S
      
      
    KeySchema:
      - AttributeName: role_id
        KeyType: HASH
      
    
    
    
    
      
        
      
    
      
        
      
    
      
        
      
    
    
    GlobalSecondaryIndexes:
      
      - IndexName: user-role-index
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          
          - AttributeName: role_id
            KeyType: RANGE
          
        Projection:
          ProjectionType: INCLUDE
          
          NonKeyAttributes:
            
            - role_name
            
            - role_type
            
            - permissions
            
          
      
      - IndexName: application-role-index
        KeySchema:
          - AttributeName: application_id
            KeyType: HASH
          
          - AttributeName: role_id
            KeyType: RANGE
          
        Projection:
          ProjectionType: KEYS_ONLY
          
      
    
    
    LocalSecondaryIndexes:
      
      - IndexName: role-type-index
        KeySchema:
          - AttributeName: role_id
            KeyType: HASH
          
          - AttributeName: role_type
            KeyType: RANGE
          
        Projection:
          ProjectionType: ALL
          
      
    
    
    Tags:
      - Key: Environment
        Value: ${env}
      - Key: Project
        Value: orb-integration-hub
      - Key: ManagedBy
        Value: schema-generator 


Resources:
usersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: users
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      
      
      - AttributeName: email
        AttributeType: S
      
      
      - AttributeName: cognito_id
        AttributeType: S
      
      
    KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      
    
    
    
    
      
    
      
    
    
    
    
    Tags:
      - Key: Environment
        Value: ${env}
      - Key: Project
        Value: orb-integration-hub
      - Key: ManagedBy
        Value: schema-generator 