# --------------------------------------------------- #
AWSTemplateFormatVersion: 2010-09-09

# --------------------------------------------------- #
Transform: AWS::Serverless-2016-10-31

# --------------------------------------------------- #
Description: >
  Application Infrastructure - Lambda Stack

# --------------------------------------------------- #
Parameters:
  ApplicationLoggingLevel:
    Default: DEBUG
    Type: String
  Environment:
    Default: dev
    Type: String
  LogFormat:
    Default: JSON
    Type: String
  NotificationEmail:
    Default: models@oneredboot.com
    Description: The email address for notifications
    Type: String
  CustomerId:
    Default: orb
    Type: String
  ProjectId:
    Default: integration-hub
    Type: String
  Runtime:
    Default: python3.12
    Type: String
  SystemLoggingLevel:
    Default: WARN
    Type: String
  ToEmail:
    Default: corey@shabot.ca
    Description: The email address to send contact form submissions to
    Type: String
  SMSOriginationNumber:
    Type: String
    Description: The AWS SNS origination number for sending SMS messages
    NoEcho: true

# --------------------------------------------------- #
Globals:
  Function:
    DeadLetterQueue:
      TargetArn: !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-dead-letter-queue-arn}}'
      Type: SNS
    Environment:
      Variables:
        ALERTS_QUEUE: !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-alerts-queue-arn}}'
        LOGGING_LEVEL: INFO
        VERSION: 1
    Handler: index.lambda_handler
    MemorySize: 256
    Runtime: !Ref Runtime
    Tags:
      Billable: true
      CustomerId: !Ref CustomerId
      Environment: !Ref Environment
      ProjectId: !Ref ProjectId
    Timeout: 30

# --------------------------------------------------- #
Resources:

  # SMS Origination Number
  SMSOriginationNumber:
    Type: AWS::SNS::OriginationNumber
    Properties:
      PhoneNumber: !Ref SMSOriginationNumber
      IsoCountryCode: US
      MessageType: TRANSACTIONAL

  # SMS Verification Lambda Function
  SMSVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${CustomerId}-${ProjectId}-${Environment}-sms-verification'
      Role: !GetAtt LambdaExecutionRole.Arn
      CodeUri: ../../src/lambdas/sms_verification
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: !Ref ApplicationLoggingLevel
          ORIGINATION_NUMBER: !Ref SMSOriginationNumber

  # IAM Roles
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Ref CloudWatchLoggingPolicy
        - !Ref ParameterStorePolicy
        - !Ref QueueStorePolicy
        - !Ref SecretsManagerPolicy
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                Resource:
                  - !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-users-table-arn}}'
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${CustomerId}-${ProjectId}-${Environment}-*'
        - PolicyName: SSMParameterAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${CustomerId}-${ProjectId}-${Environment}-*'
        - PolicyName: CloudWatchLogging
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${CustomerId}-${ProjectId}-${Environment}-*'
        - PolicyName: SQSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource:
                  - !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-alerts-queue-arn}}'
                  - !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-dead-letter-queue-arn}}'
        - PolicyName: SESAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ses:SendEmail
                Resource: '*'

  # IAM Policies
  CloudWatchLoggingPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${CustomerId}-${ProjectId}-${Environment}-cloudwatch-access-policy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource:
              - "arn:aws:logs:*:*:*"
  ParameterStorePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${CustomerId}-${ProjectId}-${Environment}-parameter-store-policy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: "Allow"
            Action:
              - "ssm:GetParameter"
            Resource:
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter//${CustomerId}/${ProjectId}/${Environment}/*"
  QueueStorePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${CustomerId}-${ProjectId}-${Environment}-queue-store-policy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: "Allow"
            Action:
              - "sqs:*"
              - "sns:*"
            Resource:
              - !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-dead-letter-queue-arn}}'
              - !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-alerts-queue-arn}}'
              - !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-phone-number-verification-topic-arn}}'
              - !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-sms-origination-number-arn}}'
  SecretsManagerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${CustomerId}-${ProjectId}-${Environment}-secrets-manager-policy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: "Allow"
            Action:
              - "secretsmanager:GetSecretValue"
            Resource:
              - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${CustomerId}/${ProjectId}/${Environment}/*"

  # SSM Parameters
  SMSVerificationLambdaArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-sms-verification-lambda-arn"
      Type: String
      Value: !GetAtt SMSVerificationFunction.Arn
      Description: ARN of the SMS Verification Lambda function
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId

  SMSOriginationNumberArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-sms-origination-number-arn"
      Type: String
      Value: !GetAtt SMSOriginationNumber.Arn
      Description: ARN of the SMS origination number
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId

# --------------------------------------------------- #
Outputs:
  SMSVerificationFunctionArn:
    Description: ARN of the SMS Verification Lambda function
    Value: !GetAtt SMSVerificationFunction.Arn