
Resources:
  usersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        
        
        - AttributeName: email
          AttributeType: S
        
        
        - AttributeName: cognito_id
          AttributeType: S
        
        
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        
      
      
      
      
        
      
        
      
      
      
      
      Tags:
        - Key: Environment
          Value: ${env}
        - Key: Project
          Value: orb-integration-hub
        - Key: ManagedBy
          Value: schema-generator 