# --------------------------------------------------- #
AWSTemplateFormatVersion: 2010-09-09

# --------------------------------------------------- #
Transform: AWS::Serverless-2016-10-31

# --------------------------------------------------- #
Description: >
  Application Infrastructure - AppSync Stack

# --------------------------------------------------- #
Parameters:
  Environment:
    Default: dev
    Type: String
  CustomerId:
    Default: orb
    Type: String
  ProjectId:
    Default: integration-hub
    Type: String
  TracingIs:
    Default: Active
    Type: String
  SchemaS3Key:
    Type: String
    Description: Name of the GraphQL schema file in S3

# --------------------------------------------------- #
Resources:
  # IAM Roles for AppSync
  AppSyncServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
      Policies:
        - PolicyName: SSMParameterAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Environment}/${CustomerId}/${ProjectId}/*'
  
  AppSyncLoggingServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs

  IntegrationHubApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-appsync'
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      UserPoolConfig:
        UserPoolId: !Sub "resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-cognito-user-pool-id"
        AwsRegion: !Ref AWS::Region
        DefaultAction: ALLOW
      AdditionalAuthenticationProviders:
        - AuthenticationType: API_KEY
      LogConfig:
        CloudWatchLogsRoleArn: !GetAtt AppSyncLoggingServiceRole.Arn
        FieldLogLevel: ALL
        ExcludeVerboseContent: false

  IntegrationHubApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Description: "API Key for unauthenticated access"
      Expires: 1767211838

  ApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-appsync-graphql-key'
      Description: "AppSync API Key for unauthenticated access"
      SecretString: !GetAtt IntegrationHubApiKey.ApiKey

  IntegrationHubSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      DefinitionS3Location: !Sub 's3://${CustomerId}-${ProjectId}-build-templates/${SchemaS3Key}'

  # Data Sources
  # --------------------------------------------------- #
  # ApplicationRoles Data Source
  ApplicationRolesDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Name: ApplicationRolesDataSource
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      DynamoDBConfig:
        TableName: !Sub 'resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-application-roles-table-name'
        AwsRegion: !Ref AWS::Region

  # ApplicationRoles Resolvers
  # --------------------------------------------------- #

  # Applications Data Source
  ApplicationsDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Name: ApplicationsDataSource
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      DynamoDBConfig:
        TableName: !Sub 'resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-applications-table-name'
        AwsRegion: !Ref AWS::Region

  # Applications Resolvers
  # --------------------------------------------------- #

  # ApplicationUsers Data Source
  ApplicationUsersDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Name: ApplicationUsersDataSource
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      DynamoDBConfig:
        TableName: !Sub 'resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-application-users-table-name'
        AwsRegion: !Ref AWS::Region

  # ApplicationUsers Resolvers
  # --------------------------------------------------- #

  # Roles Data Source
  RolesDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Name: RolesDataSource
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      DynamoDBConfig:
        TableName: !Sub 'resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-roles-table-name'
        AwsRegion: !Ref AWS::Region

  # Roles Resolvers
  # --------------------------------------------------- #

  # Users Data Source
  UsersDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Name: UsersDataSource
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      DynamoDBConfig:
        TableName: !Sub 'resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-users-table-name'
        AwsRegion: !Ref AWS::Region

  # Users Resolvers
  # --------------------------------------------------- #

  # Index-based Resolvers
  # --------------------------------------------------- #
  ApplicationRolesrole-applications-indexResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Query
      FieldName: ApplicationRolesQueryByRole_id
      DataSourceName: !GetAtt ApplicationRolesDataSource.Name
      RequestMappingTemplate: |
        # DynamoDB Query request mapping template
      ResponseMappingTemplate: |
        # DynamoDB Query response mapping template
  Applicationsapplication-name-indexResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Query
      FieldName: ApplicationsQueryByName
      DataSourceName: !GetAtt ApplicationsDataSource.Name
      RequestMappingTemplate: |
        # DynamoDB Query request mapping template
      ResponseMappingTemplate: |
        # DynamoDB Query response mapping template
  ApplicationUsersuser-applications-indexResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Query
      FieldName: ApplicationUsersQueryByUser_id
      DataSourceName: !GetAtt ApplicationUsersDataSource.Name
      RequestMappingTemplate: |
        # DynamoDB Query request mapping template
      ResponseMappingTemplate: |
        # DynamoDB Query response mapping template
  ApplicationUsersapplication-role-indexResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Query
      FieldName: ApplicationUsersQueryByApplication_id
      DataSourceName: !GetAtt ApplicationUsersDataSource.Name
      RequestMappingTemplate: |
        # DynamoDB Query request mapping template
      ResponseMappingTemplate: |
        # DynamoDB Query response mapping template
  ApplicationUsersuser-status-indexResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Query
      FieldName: ApplicationUsersQueryByApplication_id
      DataSourceName: !GetAtt ApplicationUsersDataSource.Name
      RequestMappingTemplate: |
        # DynamoDB Query request mapping template
      ResponseMappingTemplate: |
        # DynamoDB Query response mapping template
  Rolesuser-role-indexResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Query
      FieldName: RolesQueryByUser_id
      DataSourceName: !GetAtt RolesDataSource.Name
      RequestMappingTemplate: |
        # DynamoDB Query request mapping template
      ResponseMappingTemplate: |
        # DynamoDB Query response mapping template
  Rolesapplication-role-indexResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Query
      FieldName: RolesQueryByApplication_id
      DataSourceName: !GetAtt RolesDataSource.Name
      RequestMappingTemplate: |
        # DynamoDB Query request mapping template
      ResponseMappingTemplate: |
        # DynamoDB Query response mapping template
  Rolesrole-type-indexResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Query
      FieldName: RolesQueryByRole_id
      DataSourceName: !GetAtt RolesDataSource.Name
      RequestMappingTemplate: |
        # DynamoDB Query request mapping template
      ResponseMappingTemplate: |
        # DynamoDB Query response mapping template
  Usersuser-status-indexResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Query
      FieldName: UsersQueryByUser_id
      DataSourceName: !GetAtt UsersDataSource.Name
      RequestMappingTemplate: |
        # DynamoDB Query request mapping template
      ResponseMappingTemplate: |
        # DynamoDB Query response mapping template
  Usersuser-email-indexResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Query
      FieldName: UsersQueryByEmail
      DataSourceName: !GetAtt UsersDataSource.Name
      RequestMappingTemplate: |
        # DynamoDB Query request mapping template
      ResponseMappingTemplate: |
        # DynamoDB Query response mapping template

# --------------------------------------------------- #
Outputs:
  IntegrationHubApiId:
    Description: The ID of the AppSync API
    Value: !GetAtt IntegrationHubApi.ApiId
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-appsync-api-id

  IntegrationHubApiEndpoint:
    Description: The endpoint URL of the AppSync API
    Value: !GetAtt IntegrationHubApi.GraphQLUrl
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-appsync-api-endpoint 