# --------------------------------------------------- #
AWSTemplateFormatVersion: 2010-09-09

# --------------------------------------------------- #
Transform: AWS::Serverless-2016-10-31

# --------------------------------------------------- #
Description: >
  Application Infrastructure - AppSync Stack

# --------------------------------------------------- #
Parameters:
  Environment:
    Default: dev
    Type: String
  CustomerId:
    Default: orb
    Type: String
  ProjectId:
    Default: integration-hub
    Type: String
  TracingIs:
    Default: Active
    Type: String
  SchemaS3Key:
    Type: String
    Description: Name of the GraphQL schema file in S3

# --------------------------------------------------- #
Resources:
  AppSyncServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Policies:
        - PolicyName: SSMParameterAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Environment}/${CustomerId}/${ProjectId}/*'
  
  AppSyncLoggingServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs

  IntegrationHubApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-appsync'
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      UserPoolConfig:
        UserPoolId: !Sub "resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-cognito-user-pool-id"
        AwsRegion: !Ref AWS::Region
        DefaultAction: ALLOW
      AdditionalAuthenticationProviders:
        - AuthenticationType: API_KEY
      LogConfig:
        CloudWatchLogsRoleArn: !GetAtt AppSyncLoggingServiceRole.Arn
        FieldLogLevel: ALL
        ExcludeVerboseContent: false

  IntegrationHubApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Description: "API Key for unauthenticated access"
      Expires: 1767211838

  ApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-appsync-graphql-key'
      Description: "AppSync API Key for unauthenticated access"
      SecretString: !GetAtt IntegrationHubApiKey.ApiKey

  IntegrationHubSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      DefinitionS3Location: !Sub 's3://${CustomerId}-${ProjectId}-build-templates/${SchemaS3Key}'

  # DynamoDB DataSources
  # Jinja template for AppSync DynamoDB DataSources
  ApplicationRolesDynamoDbDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Name: ApplicationRolesDynamoDbDataSource
      Type: AMAZON_DYNAMODB
      DynamoDBConfig:
        TableName: !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-application-roles-table-name}}'
        AwsRegion: !Ref AWS::Region
        UseCallerCredentials: false
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
  ApplicationsDynamoDbDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Name: ApplicationsDynamoDbDataSource
      Type: AMAZON_DYNAMODB
      DynamoDBConfig:
        TableName: !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-applications-table-name}}'
        AwsRegion: !Ref AWS::Region
        UseCallerCredentials: false
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
  ApplicationUsersDynamoDbDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Name: ApplicationUsersDynamoDbDataSource
      Type: AMAZON_DYNAMODB
      DynamoDBConfig:
        TableName: !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-application-users-table-name}}'
        AwsRegion: !Ref AWS::Region
        UseCallerCredentials: false
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
  RolesDynamoDbDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Name: RolesDynamoDbDataSource
      Type: AMAZON_DYNAMODB
      DynamoDBConfig:
        TableName: !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-roles-table-name}}'
        AwsRegion: !Ref AWS::Region
        UseCallerCredentials: false
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
  UsersDynamoDbDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Name: UsersDynamoDbDataSource
      Type: AMAZON_DYNAMODB
      DynamoDBConfig:
        TableName: !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-users-table-name}}'
        AwsRegion: !Ref AWS::Region
        UseCallerCredentials: false
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn

  # DynamoDB Resolvers
  # Jinja template for AppSync DynamoDB Resolvers
  ApplicationRolesCreateResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: ApplicationRolesDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: ApplicationRolesCreate
      DataSourceName: ApplicationRolesDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "PutItem",
          "key": {
            "applicationRoleId": $util.dynamodb.toDynamoDBJson($ctx.args.input.applicationRoleId)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  ApplicationRolesUpdateResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: ApplicationRolesDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: ApplicationRolesUpdate
      DataSourceName: ApplicationRolesDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "UpdateItem",
          "key": {
            "applicationRoleId": $util.dynamodb.toDynamoDBJson($ctx.args.input.applicationRoleId)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  ApplicationRolesDeleteResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: ApplicationRolesDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: ApplicationRolesDelete
      DataSourceName: ApplicationRolesDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "DeleteItem",
          "key": {
            "applicationRoleId": $util.dynamodb.toDynamoDBJson($ctx.args.input.applicationRoleId)
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  ApplicationRolesDisableResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: ApplicationRolesDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: ApplicationRolesDisable
      DataSourceName: ApplicationRolesDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "UpdateItem",
          "key": {
            "applicationRoleId": $util.dynamodb.toDynamoDBJson($ctx.args.input.applicationRoleId)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  ApplicationsCreateResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: ApplicationsDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: ApplicationsCreate
      DataSourceName: ApplicationsDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "PutItem",
          "key": {
            "applicationId": $util.dynamodb.toDynamoDBJson($ctx.args.input.applicationId)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  ApplicationsUpdateResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: ApplicationsDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: ApplicationsUpdate
      DataSourceName: ApplicationsDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "UpdateItem",
          "key": {
            "applicationId": $util.dynamodb.toDynamoDBJson($ctx.args.input.applicationId)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  ApplicationsDeleteResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: ApplicationsDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: ApplicationsDelete
      DataSourceName: ApplicationsDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "DeleteItem",
          "key": {
            "applicationId": $util.dynamodb.toDynamoDBJson($ctx.args.input.applicationId)
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  ApplicationsDisableResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: ApplicationsDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: ApplicationsDisable
      DataSourceName: ApplicationsDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "UpdateItem",
          "key": {
            "applicationId": $util.dynamodb.toDynamoDBJson($ctx.args.input.applicationId)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  ApplicationUsersCreateResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: ApplicationUsersDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: ApplicationUsersCreate
      DataSourceName: ApplicationUsersDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "PutItem",
          "key": {
            "applicationUserId": $util.dynamodb.toDynamoDBJson($ctx.args.input.applicationUserId)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  ApplicationUsersUpdateResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: ApplicationUsersDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: ApplicationUsersUpdate
      DataSourceName: ApplicationUsersDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "UpdateItem",
          "key": {
            "applicationUserId": $util.dynamodb.toDynamoDBJson($ctx.args.input.applicationUserId)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  ApplicationUsersDeleteResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: ApplicationUsersDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: ApplicationUsersDelete
      DataSourceName: ApplicationUsersDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "DeleteItem",
          "key": {
            "applicationUserId": $util.dynamodb.toDynamoDBJson($ctx.args.input.applicationUserId)
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  ApplicationUsersDisableResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: ApplicationUsersDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: ApplicationUsersDisable
      DataSourceName: ApplicationUsersDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "UpdateItem",
          "key": {
            "applicationUserId": $util.dynamodb.toDynamoDBJson($ctx.args.input.applicationUserId)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  RolesCreateResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: RolesDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: RolesCreate
      DataSourceName: RolesDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "PutItem",
          "key": {
            "roleId": $util.dynamodb.toDynamoDBJson($ctx.args.input.roleId)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  RolesUpdateResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: RolesDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: RolesUpdate
      DataSourceName: RolesDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "UpdateItem",
          "key": {
            "roleId": $util.dynamodb.toDynamoDBJson($ctx.args.input.roleId)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  RolesDeleteResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: RolesDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: RolesDelete
      DataSourceName: RolesDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "DeleteItem",
          "key": {
            "roleId": $util.dynamodb.toDynamoDBJson($ctx.args.input.roleId)
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  RolesDisableResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: RolesDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: RolesDisable
      DataSourceName: RolesDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "UpdateItem",
          "key": {
            "roleId": $util.dynamodb.toDynamoDBJson($ctx.args.input.roleId)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  UsersCreateResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: UsersDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: UsersCreate
      DataSourceName: UsersDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "PutItem",
          "key": {
            "userId": $util.dynamodb.toDynamoDBJson($ctx.args.input.userId)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  UsersUpdateResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: UsersDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: UsersUpdate
      DataSourceName: UsersDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "UpdateItem",
          "key": {
            "userId": $util.dynamodb.toDynamoDBJson($ctx.args.input.userId)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  UsersDeleteResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: UsersDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: UsersDelete
      DataSourceName: UsersDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "DeleteItem",
          "key": {
            "userId": $util.dynamodb.toDynamoDBJson($ctx.args.input.userId)
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)
  UsersDisableResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: UsersDynamoDbDataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: UsersDisable
      DataSourceName: UsersDynamoDbDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "UpdateItem",
          "key": {
            "userId": $util.dynamodb.toDynamoDBJson($ctx.args.input.userId)
          },
          "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result) 

# --------------------------------------------------- #
Outputs:
  IntegrationHubApiId:
    Description: The ID of the AppSync API
    Value: !GetAtt IntegrationHubApi.ApiId
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-appsync-api-id

  IntegrationHubApiEndpoint:
    Description: The endpoint URL of the AppSync API
    Value: !GetAtt IntegrationHubApi.GraphQLUrl
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-appsync-api-endpoint 