# --------------------------------------------------- #
AWSTemplateFormatVersion: 2010-09-09

# --------------------------------------------------- #
Transform: AWS::Serverless-2016-10-31

# --------------------------------------------------- #
Description: >
 Application Infrastructure - DynamoDB Tables

# --------------------------------------------------- #
Parameters:
  Environment:
    Default: dev
    Type: String
    Description: Environment name (dev, staging, prod)
  CustomerId:
    Default: orb
    Type: String
    Description: Customer identifier
  ProjectId:
    Default: integration-hub
    Type: String
    Description: Project identifier
  TracingIs:
    Default: Active
    Type: String
    Description: Whether tracing is enabled

# --------------------------------------------------- #
Resources:
  ApplicationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-applications
      AttributeDefinitions:
        - AttributeName: application_id
          AttributeType: S
      KeySchema:
        - AttributeName: application_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  ApplicationsTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/${CustomerId}/${ProjectId}/dynamodb/applications/table-name
      Type: String
      Value: !Ref ApplicationsTable

  ApplicationsTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/${CustomerId}/${ProjectId}/dynamodb/applications/table-arn
      Type: String
      Value: !GetAtt ApplicationsTable.Arn
  ApplicationrolesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-applicationroles
      AttributeDefinitions:
        - AttributeName: application_id
          AttributeType: S
        - AttributeName: role_id
          AttributeType: S
      KeySchema:
        - AttributeName: application_id
          KeyType: HASH
        - AttributeName: role_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  ApplicationrolesTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/${CustomerId}/${ProjectId}/dynamodb/applicationroles/table-name
      Type: String
      Value: !Ref ApplicationrolesTable

  ApplicationrolesTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/${CustomerId}/${ProjectId}/dynamodb/applicationroles/table-arn
      Type: String
      Value: !GetAtt ApplicationrolesTable.Arn
  ApplicationusersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-applicationusers
      AttributeDefinitions:
        - AttributeName: application_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: application_id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  ApplicationusersTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/${CustomerId}/${ProjectId}/dynamodb/applicationusers/table-name
      Type: String
      Value: !Ref ApplicationusersTable

  ApplicationusersTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/${CustomerId}/${ProjectId}/dynamodb/applicationusers/table-arn
      Type: String
      Value: !GetAtt ApplicationusersTable.Arn
  RolesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-roles
      AttributeDefinitions:
        - AttributeName: role_id
          AttributeType: S
        - AttributeName: application_id
          AttributeType: S
      KeySchema:
        - AttributeName: role_id
          KeyType: HASH
        - AttributeName: application_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  RolesTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/${CustomerId}/${ProjectId}/dynamodb/roles/table-name
      Type: String
      Value: !Ref RolesTable

  RolesTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/${CustomerId}/${ProjectId}/dynamodb/roles/table-arn
      Type: String
      Value: !GetAtt RolesTable.Arn
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-users
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  UsersTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/${CustomerId}/${ProjectId}/dynamodb/users/table-name
      Type: String
      Value: !Ref UsersTable

  UsersTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/${CustomerId}/${ProjectId}/dynamodb/users/table-arn
      Type: String
      Value: !GetAtt UsersTable.Arn

# --------------------------------------------------- #
Outputs:
  ApplicationsTableName:
    Description: Applications Table Name
    Value: !Ref ApplicationsTable

  ApplicationsTableArn:
    Description: Applications Table ARN
    Value: !GetAtt ApplicationsTable.Arn
  ApplicationrolesTableName:
    Description: Applicationroles Table Name
    Value: !Ref ApplicationrolesTable

  ApplicationrolesTableArn:
    Description: Applicationroles Table ARN
    Value: !GetAtt ApplicationrolesTable.Arn
  ApplicationusersTableName:
    Description: Applicationusers Table Name
    Value: !Ref ApplicationusersTable

  ApplicationusersTableArn:
    Description: Applicationusers Table ARN
    Value: !GetAtt ApplicationusersTable.Arn
  RolesTableName:
    Description: Roles Table Name
    Value: !Ref RolesTable

  RolesTableArn:
    Description: Roles Table ARN
    Value: !GetAtt RolesTable.Arn
  UsersTableName:
    Description: Users Table Name
    Value: !Ref UsersTable

  UsersTableArn:
    Description: Users Table ARN
    Value: !GetAtt UsersTable.Arn
