# --------------------------------------------------- #
AWSTemplateFormatVersion: 2010-09-09

# --------------------------------------------------- #
Transform: AWS::Serverless-2016-10-31

# --------------------------------------------------- #
Description: >
 Application Infrastructure - DynamoDB Tables

# --------------------------------------------------- #
Parameters:
  Environment:
    Default: dev
    Type: String
    Description: Environment name (dev, staging, prod)
  CustomerId:
    Default: orb
    Type: String
    Description: Customer identifier
  ProjectId:
    Default: integration-hub
    Type: String
    Description: Project identifier
  TracingIs:
    Default: Active
    Type: String
    Description: Whether tracing is enabled

# --------------------------------------------------- #
Resources:
  ApplicationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-applications
      AttributeDefinitions:
        - AttributeName: application_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: application_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: application-status-index
          KeySchema:
            - AttributeName: application_id
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  ApplicationsTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-applications-table-name
      Type: String
      Value: !Ref ApplicationsTable

  ApplicationsTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-applications-table-arn
      Type: String
      Value: !GetAtt ApplicationsTable.Arn
  ApplicationRolesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-roles
      AttributeDefinitions:
        - AttributeName: application_id
          AttributeType: S
        - AttributeName: role_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: application_id
          KeyType: HASH
        - AttributeName: role_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: role-status-index
          KeySchema:
            - AttributeName: application_id
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  ApplicationRolesTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-roles-table-name
      Type: String
      Value: !Ref ApplicationRolesTable

  ApplicationRolesTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-roles-table-arn
      Type: String
      Value: !GetAtt ApplicationRolesTable.Arn
  ApplicationUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-users
      AttributeDefinitions:
        - AttributeName: application_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: role_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: application_id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: user-applications-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: application_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: application-role-index
          KeySchema:
            - AttributeName: application_id
              KeyType: HASH
            - AttributeName: role_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: user-status-index
          KeySchema:
            - AttributeName: application_id
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  ApplicationUsersTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-users-table-name
      Type: String
      Value: !Ref ApplicationUsersTable

  ApplicationUsersTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-users-table-arn
      Type: String
      Value: !GetAtt ApplicationUsersTable.Arn
  RolesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-roles
      AttributeDefinitions:
        - AttributeName: role_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: application_id
          AttributeType: S
        - AttributeName: role_type
          AttributeType: S
      KeySchema:
        - AttributeName: role_id
          KeyType: HASH
        - AttributeName: application_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: user-role-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: role_id
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
        - IndexName: application-role-index
          KeySchema:
            - AttributeName: application_id
              KeyType: HASH
            - AttributeName: role_id
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: role-type-index
          KeySchema:
            - AttributeName: role_id
              KeyType: HASH
            - AttributeName: role_type
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  RolesTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-roles-table-name
      Type: String
      Value: !Ref RolesTable

  RolesTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-roles-table-arn
      Type: String
      Value: !GetAtt RolesTable.Arn
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-users
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user-status-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: user-email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
            - AttributeName: user_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  UsersTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-users-table-name
      Type: String
      Value: !Ref UsersTable

  UsersTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-users-table-arn
      Type: String
      Value: !GetAtt UsersTable.Arn

# --------------------------------------------------- #
Outputs:
  ApplicationsTableName:
    Description: Applications Table Name
    Value: !Ref ApplicationsTable

  ApplicationsTableArn:
    Description: Applications Table ARN
    Value: !GetAtt ApplicationsTable.Arn
  ApplicationRolesTableName:
    Description: ApplicationRoles Table Name
    Value: !Ref ApplicationRolesTable

  ApplicationRolesTableArn:
    Description: ApplicationRoles Table ARN
    Value: !GetAtt ApplicationRolesTable.Arn
  ApplicationUsersTableName:
    Description: ApplicationUsers Table Name
    Value: !Ref ApplicationUsersTable

  ApplicationUsersTableArn:
    Description: ApplicationUsers Table ARN
    Value: !GetAtt ApplicationUsersTable.Arn
  RolesTableName:
    Description: Roles Table Name
    Value: !Ref RolesTable

  RolesTableArn:
    Description: Roles Table ARN
    Value: !GetAtt RolesTable.Arn
  UsersTableName:
    Description: Users Table Name
    Value: !Ref UsersTable

  UsersTableArn:
    Description: Users Table ARN
    Value: !GetAtt UsersTable.Arn
