# --------------------------------------------------- #
AWSTemplateFormatVersion: 2010-09-09

# --------------------------------------------------- #
Transform: AWS::Serverless-2016-10-31

# --------------------------------------------------- #
Description: >
 Application Infrastructure - DynamoDB Tables

# --------------------------------------------------- #
Parameters:
  Environment:
    Default: dev
    Type: String
    Description: Environment name (dev, staging, prod)
  CustomerId:
    Default: orb
    Type: String
    Description: Customer identifier
  ProjectId:
    Default: integration-hub
    Type: String
    Description: Project identifier
  TracingIs:
    Default: Active
    Type: String
    Description: Whether tracing is enabled

# --------------------------------------------------- #
Resources:
  ApplicationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-applications
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: application_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: application_id
          AttributeType: S

  ApplicationsTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-applications-table-arn
      Type: String
      Value: !GetAtt ApplicationsTable.Arn

  ApplicationsTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-applications-table-name
      Type: String
      Value: !Ref ApplicationsTable
  ApplicationRolesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-roles
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: application_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: application_id
          AttributeType: S

  ApplicationRolesTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-roles-table-arn
      Type: String
      Value: !GetAtt ApplicationRolesTable.Arn

  ApplicationRolesTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-roles-table-name
      Type: String
      Value: !Ref ApplicationRolesTable
  ApplicationUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-users
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: application_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: application_id
          AttributeType: S

  ApplicationUsersTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-users-table-arn
      Type: String
      Value: !GetAtt ApplicationUsersTable.Arn

  ApplicationUsersTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-users-table-name
      Type: String
      Value: !Ref ApplicationUsersTable
  RolesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-roles
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: role_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: role_id
          AttributeType: S

  RolesTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-roles-table-arn
      Type: String
      Value: !GetAtt RolesTable.Arn

  RolesTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-roles-table-name
      Type: String
      Value: !Ref RolesTable
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-users
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S

  UsersTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-users-table-arn
      Type: String
      Value: !GetAtt UsersTable.Arn

  UsersTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-users-table-name
      Type: String
      Value: !Ref UsersTable

# --------------------------------------------------- #
Outputs:
  ApplicationsTableArn:
    Description: The ARN of the Applications table
    Value: !GetAtt ApplicationsTable.Arn
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-applications-table-arn

  ApplicationsTableName:
    Description: The name of the Applications table
    Value: !Ref ApplicationsTable
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-applications-table-name
  ApplicationRolesTableArn:
    Description: The ARN of the ApplicationRoles table
    Value: !GetAtt ApplicationRolesTable.Arn
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-roles-table-arn

  ApplicationRolesTableName:
    Description: The name of the ApplicationRoles table
    Value: !Ref ApplicationRolesTable
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-roles-table-name
  ApplicationUsersTableArn:
    Description: The ARN of the ApplicationUsers table
    Value: !GetAtt ApplicationUsersTable.Arn
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-users-table-arn

  ApplicationUsersTableName:
    Description: The name of the ApplicationUsers table
    Value: !Ref ApplicationUsersTable
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-users-table-name
  RolesTableArn:
    Description: The ARN of the Roles table
    Value: !GetAtt RolesTable.Arn
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-roles-table-arn

  RolesTableName:
    Description: The name of the Roles table
    Value: !Ref RolesTable
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-roles-table-name
  UsersTableArn:
    Description: The ARN of the Users table
    Value: !GetAtt UsersTable.Arn
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-users-table-arn

  UsersTableName:
    Description: The name of the Users table
    Value: !Ref UsersTable
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-users-table-name
