# --------------------------------------------------- #
AWSTemplateFormatVersion: 2010-09-09

# --------------------------------------------------- #
Transform: AWS::Serverless-2016-10-31

# --------------------------------------------------- #
Description: >
 Application Infrastructure - DynamoDB Tables

# --------------------------------------------------- #
Parameters:
  Environment:
    Default: dev
    Type: String
    Description: Environment name (dev, staging, prod)
  CustomerId:
    Default: orb
    Type: String
    Description: Customer identifier
  ProjectId:
    Default: integration-hub
    Type: String
    Description: Project identifier
  TracingIs:
    Default: Active
    Type: String
    Description: Whether tracing is enabled

# --------------------------------------------------- #
Resources:
  ApplicationRolesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-roles
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      AttributeDefinitions:

  ApplicationRolesTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-roles-table-arn
      Type: String
      Value: !GetAtt ApplicationRolesTable.Arn

  ApplicationRolesTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-roles-table-name
      Type: String
      Value: !Ref ApplicationRolesTable
  ApplicationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-applications
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      AttributeDefinitions:

  ApplicationsTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-applications-table-arn
      Type: String
      Value: !GetAtt ApplicationsTable.Arn

  ApplicationsTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-applications-table-name
      Type: String
      Value: !Ref ApplicationsTable
  ApplicationUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-users
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      AttributeDefinitions:

  ApplicationUsersTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-users-table-arn
      Type: String
      Value: !GetAtt ApplicationUsersTable.Arn

  ApplicationUsersTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-users-table-name
      Type: String
      Value: !Ref ApplicationUsersTable
  AuthTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-auth
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      AttributeDefinitions:

  AuthTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-auth-table-arn
      Type: String
      Value: !GetAtt AuthTable.Arn

  AuthTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-auth-table-name
      Type: String
      Value: !Ref AuthTable
  AuthErrorTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-auth-error
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      AttributeDefinitions:

  AuthErrorTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-auth-error-table-arn
      Type: String
      Value: !GetAtt AuthErrorTable.Arn

  AuthErrorTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-auth-error-table-name
      Type: String
      Value: !Ref AuthErrorTable
  ErrorRegistryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-error-registry
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      AttributeDefinitions:

  ErrorRegistryTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-error-registry-table-arn
      Type: String
      Value: !GetAtt ErrorRegistryTable.Arn

  ErrorRegistryTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-error-registry-table-name
      Type: String
      Value: !Ref ErrorRegistryTable
  MfaSetupDetailsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-mfa-setup-details
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      AttributeDefinitions:

  MfaSetupDetailsTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-mfa-setup-details-table-arn
      Type: String
      Value: !GetAtt MfaSetupDetailsTable.Arn

  MfaSetupDetailsTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-mfa-setup-details-table-name
      Type: String
      Value: !Ref MfaSetupDetailsTable
  RolesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-roles
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      AttributeDefinitions:

  RolesTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-roles-table-arn
      Type: String
      Value: !GetAtt RolesTable.Arn

  RolesTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-roles-table-name
      Type: String
      Value: !Ref RolesTable
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-users
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      AttributeDefinitions:

  UsersTableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-users-table-arn
      Type: String
      Value: !GetAtt UsersTable.Arn

  UsersTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-users-table-name
      Type: String
      Value: !Ref UsersTable

# --------------------------------------------------- #
Outputs:
  ApplicationRolesTableArn:
    Description: The ARN of the ApplicationRoles table
    Value: !GetAtt ApplicationRolesTable.Arn
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-roles-table-arn

  ApplicationRolesTableName:
    Description: The name of the ApplicationRoles table
    Value: !Ref ApplicationRolesTable
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-roles-table-name
  ApplicationsTableArn:
    Description: The ARN of the Applications table
    Value: !GetAtt ApplicationsTable.Arn
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-applications-table-arn

  ApplicationsTableName:
    Description: The name of the Applications table
    Value: !Ref ApplicationsTable
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-applications-table-name
  ApplicationUsersTableArn:
    Description: The ARN of the ApplicationUsers table
    Value: !GetAtt ApplicationUsersTable.Arn
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-users-table-arn

  ApplicationUsersTableName:
    Description: The name of the ApplicationUsers table
    Value: !Ref ApplicationUsersTable
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-application-users-table-name
  AuthTableArn:
    Description: The ARN of the Auth table
    Value: !GetAtt AuthTable.Arn
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-auth-table-arn

  AuthTableName:
    Description: The name of the Auth table
    Value: !Ref AuthTable
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-auth-table-name
  AuthErrorTableArn:
    Description: The ARN of the AuthError table
    Value: !GetAtt AuthErrorTable.Arn
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-auth-error-table-arn

  AuthErrorTableName:
    Description: The name of the AuthError table
    Value: !Ref AuthErrorTable
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-auth-error-table-name
  ErrorRegistryTableArn:
    Description: The ARN of the ErrorRegistry table
    Value: !GetAtt ErrorRegistryTable.Arn
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-error-registry-table-arn

  ErrorRegistryTableName:
    Description: The name of the ErrorRegistry table
    Value: !Ref ErrorRegistryTable
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-error-registry-table-name
  MfaSetupDetailsTableArn:
    Description: The ARN of the MfaSetupDetails table
    Value: !GetAtt MfaSetupDetailsTable.Arn
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-mfa-setup-details-table-arn

  MfaSetupDetailsTableName:
    Description: The name of the MfaSetupDetails table
    Value: !Ref MfaSetupDetailsTable
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-mfa-setup-details-table-name
  RolesTableArn:
    Description: The ARN of the Roles table
    Value: !GetAtt RolesTable.Arn
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-roles-table-arn

  RolesTableName:
    Description: The name of the Roles table
    Value: !Ref RolesTable
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-roles-table-name
  UsersTableArn:
    Description: The ARN of the Users table
    Value: !GetAtt UsersTable.Arn
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-users-table-arn

  UsersTableName:
    Description: The name of the Users table
    Value: !Ref UsersTable
    Export:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-users-table-name
