# --------------------------------------------------- #
AWSTemplateFormatVersion: 2010-09-09

# --------------------------------------------------- #
Transform: AWS::Serverless-2016-10-31

# --------------------------------------------------- #
Description: >
 Application Infrastructure - DynamoDB Tables

# --------------------------------------------------- #
Parameters:
  Environment:
    Default: dev
    Type: String
    Description: Environment name (dev, staging, prod)
  CustomerId:
    Default: orb
    Type: String
    Description: Customer identifier
  ProjectId:
    Default: integration-hub
    Type: String
    Description: Project identifier
  TracingIs:
    Default: Active
    Type: String
    Description: Whether tracing is enabled

# --------------------------------------------------- #
Resources:
  [[ table_name | to_pascal_case ]]Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-[[ table_name | to_kebab_case ]]
      AttributeDefinitions:
        - AttributeName: [[ attr.name ]]
          AttributeType: [[ attr.type | to_dynamodb_type ]]
        - AttributeName: [[ attr.name ]]
          AttributeType: [[ attr.type | to_dynamodb_type ]]
      KeySchema:
        - AttributeName: [[ schema.partition_key ]]
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: [[ index.name ]]
          KeySchema:
            - AttributeName: [[ index.partition ]]
              KeyType: HASH
            - AttributeName: [[ index.sort ]]
              KeyType: RANGE
          Projection:
            ProjectionType: [[ index.projection_type ]]
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  [[ table_name | to_pascal_case ]]TableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-[[ table_name | to_kebab_case ]]-table-name
      Type: String
      Value: !Ref [[ table_name | to_pascal_case ]]Table

  [[ table_name | to_pascal_case ]]TableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-[[ table_name | to_kebab_case ]]-table-arn
      Type: String
      Value: !GetAtt [[ table_name | to_pascal_case ]]Table.Arn
  [[ table_name | to_pascal_case ]]Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-[[ table_name | to_kebab_case ]]
      AttributeDefinitions:
        - AttributeName: [[ attr.name ]]
          AttributeType: [[ attr.type | to_dynamodb_type ]]
        - AttributeName: [[ attr.name ]]
          AttributeType: [[ attr.type | to_dynamodb_type ]]
      KeySchema:
        - AttributeName: [[ schema.partition_key ]]
          KeyType: HASH
        - AttributeName: [[ schema.sort_key ]]
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: [[ index.name ]]
          KeySchema:
            - AttributeName: [[ index.partition ]]
              KeyType: HASH
            - AttributeName: [[ index.sort ]]
              KeyType: RANGE
          Projection:
            ProjectionType: [[ index.projection_type ]]
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  [[ table_name | to_pascal_case ]]TableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-[[ table_name | to_kebab_case ]]-table-name
      Type: String
      Value: !Ref [[ table_name | to_pascal_case ]]Table

  [[ table_name | to_pascal_case ]]TableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-[[ table_name | to_kebab_case ]]-table-arn
      Type: String
      Value: !GetAtt [[ table_name | to_pascal_case ]]Table.Arn
  [[ table_name | to_pascal_case ]]Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-[[ table_name | to_kebab_case ]]
      AttributeDefinitions:
        - AttributeName: [[ attr.name ]]
          AttributeType: [[ attr.type | to_dynamodb_type ]]
        - AttributeName: [[ attr.name ]]
          AttributeType: [[ attr.type | to_dynamodb_type ]]
        - AttributeName: [[ attr.name ]]
          AttributeType: [[ attr.type | to_dynamodb_type ]]
        - AttributeName: [[ attr.name ]]
          AttributeType: [[ attr.type | to_dynamodb_type ]]
      KeySchema:
        - AttributeName: [[ schema.partition_key ]]
          KeyType: HASH
        - AttributeName: [[ schema.sort_key ]]
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: [[ index.name ]]
          KeySchema:
            - AttributeName: [[ index.partition ]]
              KeyType: HASH
            - AttributeName: [[ index.sort ]]
              KeyType: RANGE
          Projection:
            ProjectionType: [[ index.projection_type ]]
        - IndexName: [[ index.name ]]
          KeySchema:
            - AttributeName: [[ index.partition ]]
              KeyType: HASH
            - AttributeName: [[ index.sort ]]
              KeyType: RANGE
          Projection:
            ProjectionType: [[ index.projection_type ]]
        - IndexName: [[ index.name ]]
          KeySchema:
            - AttributeName: [[ index.partition ]]
              KeyType: HASH
            - AttributeName: [[ index.sort ]]
              KeyType: RANGE
          Projection:
            ProjectionType: [[ index.projection_type ]]
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  [[ table_name | to_pascal_case ]]TableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-[[ table_name | to_kebab_case ]]-table-name
      Type: String
      Value: !Ref [[ table_name | to_pascal_case ]]Table

  [[ table_name | to_pascal_case ]]TableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-[[ table_name | to_kebab_case ]]-table-arn
      Type: String
      Value: !GetAtt [[ table_name | to_pascal_case ]]Table.Arn
  [[ table_name | to_pascal_case ]]Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-[[ table_name | to_kebab_case ]]
      AttributeDefinitions:
        - AttributeName: [[ attr.name ]]
          AttributeType: [[ attr.type | to_dynamodb_type ]]
        - AttributeName: [[ attr.name ]]
          AttributeType: [[ attr.type | to_dynamodb_type ]]
        - AttributeName: [[ attr.name ]]
          AttributeType: [[ attr.type | to_dynamodb_type ]]
        - AttributeName: [[ attr.name ]]
          AttributeType: [[ attr.type | to_dynamodb_type ]]
      KeySchema:
        - AttributeName: [[ schema.partition_key ]]
          KeyType: HASH
        - AttributeName: [[ schema.sort_key ]]
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: [[ index.name ]]
          KeySchema:
            - AttributeName: [[ index.partition ]]
              KeyType: HASH
            - AttributeName: [[ index.sort ]]
              KeyType: RANGE
          Projection:
            ProjectionType: [[ index.projection_type ]]
            NonKeyAttributes:
              - [[ attr ]]
              - [[ attr ]]
              - [[ attr ]]
        - IndexName: [[ index.name ]]
          KeySchema:
            - AttributeName: [[ index.partition ]]
              KeyType: HASH
            - AttributeName: [[ index.sort ]]
              KeyType: RANGE
          Projection:
            ProjectionType: [[ index.projection_type ]]
        - IndexName: [[ index.name ]]
          KeySchema:
            - AttributeName: [[ index.partition ]]
              KeyType: HASH
            - AttributeName: [[ index.sort ]]
              KeyType: RANGE
          Projection:
            ProjectionType: [[ index.projection_type ]]
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  [[ table_name | to_pascal_case ]]TableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-[[ table_name | to_kebab_case ]]-table-name
      Type: String
      Value: !Ref [[ table_name | to_pascal_case ]]Table

  [[ table_name | to_pascal_case ]]TableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-[[ table_name | to_kebab_case ]]-table-arn
      Type: String
      Value: !GetAtt [[ table_name | to_pascal_case ]]Table.Arn
  [[ table_name | to_pascal_case ]]Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${CustomerId}-${ProjectId}-${Environment}-[[ table_name | to_kebab_case ]]
      AttributeDefinitions:
        - AttributeName: [[ attr.name ]]
          AttributeType: [[ attr.type | to_dynamodb_type ]]
        - AttributeName: [[ attr.name ]]
          AttributeType: [[ attr.type | to_dynamodb_type ]]
        - AttributeName: [[ attr.name ]]
          AttributeType: [[ attr.type | to_dynamodb_type ]]
      KeySchema:
        - AttributeName: [[ schema.partition_key ]]
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: [[ index.name ]]
          KeySchema:
            - AttributeName: [[ index.partition ]]
              KeyType: HASH
            - AttributeName: [[ index.sort ]]
              KeyType: RANGE
          Projection:
            ProjectionType: [[ index.projection_type ]]
        - IndexName: [[ index.name ]]
          KeySchema:
            - AttributeName: [[ index.partition ]]
              KeyType: HASH
            - AttributeName: [[ index.sort ]]
              KeyType: RANGE
          Projection:
            ProjectionType: [[ index.projection_type ]]
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId

  [[ table_name | to_pascal_case ]]TableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-[[ table_name | to_kebab_case ]]-table-name
      Type: String
      Value: !Ref [[ table_name | to_pascal_case ]]Table

  [[ table_name | to_pascal_case ]]TableArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${CustomerId}-${ProjectId}-${Environment}-[[ table_name | to_kebab_case ]]-table-arn
      Type: String
      Value: !GetAtt [[ table_name | to_pascal_case ]]Table.Arn

# --------------------------------------------------- #
Outputs:
  [[ table_name | to_pascal_case ]]TableName:
    Description: [[ table_name | to_pascal_case ]] Table Name
    Value: !Ref [[ table_name | to_pascal_case ]]Table

  [[ table_name | to_pascal_case ]]TableArn:
    Description: [[ table_name | to_pascal_case ]] Table ARN
    Value: !GetAtt [[ table_name | to_pascal_case ]]Table.Arn
  [[ table_name | to_pascal_case ]]TableName:
    Description: [[ table_name | to_pascal_case ]] Table Name
    Value: !Ref [[ table_name | to_pascal_case ]]Table

  [[ table_name | to_pascal_case ]]TableArn:
    Description: [[ table_name | to_pascal_case ]] Table ARN
    Value: !GetAtt [[ table_name | to_pascal_case ]]Table.Arn
  [[ table_name | to_pascal_case ]]TableName:
    Description: [[ table_name | to_pascal_case ]] Table Name
    Value: !Ref [[ table_name | to_pascal_case ]]Table

  [[ table_name | to_pascal_case ]]TableArn:
    Description: [[ table_name | to_pascal_case ]] Table ARN
    Value: !GetAtt [[ table_name | to_pascal_case ]]Table.Arn
  [[ table_name | to_pascal_case ]]TableName:
    Description: [[ table_name | to_pascal_case ]] Table Name
    Value: !Ref [[ table_name | to_pascal_case ]]Table

  [[ table_name | to_pascal_case ]]TableArn:
    Description: [[ table_name | to_pascal_case ]] Table ARN
    Value: !GetAtt [[ table_name | to_pascal_case ]]Table.Arn
  [[ table_name | to_pascal_case ]]TableName:
    Description: [[ table_name | to_pascal_case ]] Table Name
    Value: !Ref [[ table_name | to_pascal_case ]]Table

  [[ table_name | to_pascal_case ]]TableArn:
    Description: [[ table_name | to_pascal_case ]] Table ARN
    Value: !GetAtt [[ table_name | to_pascal_case ]]Table.Arn
