AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for within-the-veil.ca React website'

Parameters:
  CloudFrontDistributionHostedZoneId:
    Type: String
    Default: Z2FDTNDATAQYW2
    Description: The CloudFront distribution hosted zone ID
  DomainName:
    Type: String
    Default: within-the-veil.ca
    Description: The domain name for the website
  Environment:
    Type: String
    Default: dev
    Description: The environment for the website
  Organization:
    Type: String
    Default: orb
    Description: The organization for the website
  ProjectId:
    Type: String
    Default: wtv
    Description: The project ID for the website

Resources:
  # S3Bucket: Stores the static files for the website and serves them via CloudFront.
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Organization}-${ProjectId}-${Environment}-website'
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  # S3BucketPolicy: Grants CloudFront access to the S3 bucket for serving content.
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}'
            Action: 's3:GetObject'
            Resource: !Sub '${S3Bucket.Arn}/*'

  # CloudFrontOAI: Configures the CloudFront Origin Access Identity for secure access to the S3 bucket.
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: OAI for within-the-veil.ca

  # CloudFrontDistribution: Distributes the website content globally with caching and SSL support.
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt S3Bucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI}'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

  # Certificate: Manages the SSL certificate for the website domain.
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS

  # Route53RecordSet: Configures DNS settings for the website domain to point to the CloudFront distribution.
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: !Ref CloudFrontDistributionHostedZoneId

Outputs:
  WebsiteURL:
    Value: !Sub 'https://${DomainName}'
    Description: URL of the website
  S3BucketName:
    Value: !Ref S3Bucket
    Description: Name of the S3 bucket
  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution
    Description: ID of the CloudFront distribution