# file: infrastructure/cloudformation/lambda-layer-organizations-security.yml
# author: AI Assistant
# created: 2025-07-18
# description: Organizations Security Lambda Layer

# --------------------------------------------------- #
AWSTemplateFormatVersion: '2010-09-09'

# --------------------------------------------------- #
Transform: AWS::Serverless-2016-10-31

# --------------------------------------------------- #
Description: 'Organizations Security Lambda Layer - RBAC, audit logging, and security utilities'

# --------------------------------------------------- #
Parameters:
  CustomerId:
    Type: String
    Default: orb
    Description: Customer identifier for resource naming
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Deployment environment
  ProjectId:
    Type: String
    Default: integration-hub
    Description: Project identifier for resource naming
  Runtime:
    Default: python3.12
    Type: String

# --------------------------------------------------- #
Resources:
  OrganizationsSecurityLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${CustomerId}-${ProjectId}-${Environment}-organizations-security-layer'
      Description: 'Organization security middleware with audit logging and RBAC utilities'
      ContentUri: ../../backend/src/layers/organizations_security/
      CompatibleRuntimes:
        - !Ref Runtime
      LicenseInfo: MIT

  OrganizationsSecurityLayerArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-organizations-security-layer-arn'
      Type: String
      Value: !Ref OrganizationsSecurityLayer
      Description: "ARN of the Organization Security Lambda Layer"

# --------------------------------------------------- #
Outputs:
  LayerVersionArn:
    Description: ARN of the Organizations Security Lambda layer version
    Value: !Ref OrganizationsSecurityLayer
    Export:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-organizations-security-layer-arn'