# file: infrastructure/cloudformation/lambda-layer-common.yml
# author: AI Assistant
# created: 2025-07-18
# description: Common Lambda Layer

# --------------------------------------------------- #
AWSTemplateFormatVersion: '2010-09-09'

# --------------------------------------------------- #
Transform: AWS::Serverless-2016-10-31

# --------------------------------------------------- #
Description: 'Common Lambda Layer - Shared utilities, exceptions, and security components'

# --------------------------------------------------- #
Parameters:
  CustomerId:
    Type: String
    Default: orb
    Description: Customer identifier for resource naming
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Deployment environment
  ProjectId:
    Type: String
    Default: integration-hub
    Description: Project identifier for resource naming
  Runtime:
    Default: python3.12
    Type: String

# --------------------------------------------------- #
Resources:
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${CustomerId}-${ProjectId}-${Environment}-common-layer'
      Description: 'Common utilities including security exceptions and shared components'
      ContentUri: ../../backend/src/layers/common/
      CompatibleRuntimes:
        - !Ref Runtime
      LicenseInfo: MIT

  CommonLayerArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-common-layer-arn'
      Type: String
      Value: !Ref CommonLayer
      Description: "ARN of the Common Lambda Layer"

# --------------------------------------------------- #
Outputs:
  LayerVersionArn:
    Description: ARN of the Common Lambda layer version
    Value: !Ref CommonLayer
    Export:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-common-layer-arn'