# file: infrastructure/cloudformation/layers.yml
# author: AI Assistant
# created: 2025-07-03
# description: Consolidated Lambda Layers CloudFormation Template

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Lambda Layers - Organization Security and Stripe Payment layers'

Parameters:
  CustomerId:
    Type: String
    Default: 'orb'
    Description: Customer identifier for resource naming
  ProjectId:
    Type: String
    Default: 'integration-hub'
    Description: Project identifier for resource naming
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]
    Description: Deployment environment

Resources:
  # ===== ORGANIZATION SECURITY LAYER =====
  
  OrganizationSecurityLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub '${CustomerId}-${ProjectId}-${Environment}-organization-security-layer'
      Description: 'Organization security middleware with audit logging and RBAC utilities'
      Content:
        S3Bucket: !Sub '${CustomerId}-${ProjectId}-${Environment}-build-artifacts'
        S3Key: 'layers/organization-security-layer.zip'
      CompatibleRuntimes:
        - python3.12
      CompatibleArchitectures:
        - x86_64
        - arm64
      LicenseInfo: MIT

  # ===== STRIPE PAYMENT LAYER =====
  
  StripeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${CustomerId}-${ProjectId}-${Environment}-stripe-layer'
      Description: 'Stripe Payment processing layer'
      ContentUri: ../../backend/src/layers/stripe/
      CompatibleRuntimes:
        - python3.12
      CompatibleArchitectures:
        - x86_64
        - arm64
    Metadata:
      BuildMethod: python3.12

  # ===== SSM PARAMETERS FOR CROSS-STACK REFERENCES =====
  
  OrganizationSecurityLayerArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-organization-security-layer-arn'
      Type: String
      Value: !Ref OrganizationSecurityLayer
      Description: "ARN of the Organization Security Lambda Layer"

  StripeLayerArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-stripe-layer-arn'
      Type: String
      Value: !Ref StripeLayer
      Description: "ARN of the Stripe Payment Lambda Layer"

Outputs:
  # Organization Security Layer Outputs
  OrganizationSecurityLayerArn:
    Description: 'ARN of the Organization Security Lambda Layer'
    Value: !Ref OrganizationSecurityLayer
    Export:
      Name: !Sub '${CustomerId}-${ProjectId}-organization-security-layer-arn-${Environment}'
  
  OrganizationSecurityLayerVersion:
    Description: 'Version of the Organization Security Lambda Layer'
    Value: !GetAtt OrganizationSecurityLayer.Version
    Export:
      Name: !Sub '${CustomerId}-${ProjectId}-organization-security-layer-version-${Environment}'

  # Stripe Layer Outputs
  StripeLayerArn:
    Description: 'ARN of the Stripe Payment Lambda Layer'
    Value: !Ref StripeLayer
    Export:
      Name: !Sub '${CustomerId}-${ProjectId}-stripe-layer-arn-${Environment}'
  
  StripeLayerVersion:
    Description: 'Version of the Stripe Payment Lambda Layer'
    Value: !GetAtt StripeLayer.Version
    Export:
      Name: !Sub '${CustomerId}-${ProjectId}-stripe-layer-version-${Environment}'