AWSTemplateFormatVersion: 2010-09-09
Description: Monitoring and Dashboard resources for Orb Integration Hub

Parameters:
  AppSyncApiId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The AppSync API ID from SSM Parameter Store
  Environment:
    Type: String
    Default: dev
  CustomerId:
    Type: String
    Default: orb
  ProjectId:
    Type: String
    Default: integration-hub

Resources:
  AppSyncMonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${CustomerId}-${ProjectId}-${Environment}-appsync-dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/AppSync", "4XXError", "GraphQLAPIId", "${AppSyncApiId}" ],
                  [ ".", "5XXError", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "AppSync 4XX/5XX Errors"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/AppSync", "Latency", "GraphQLAPIId", "${AppSyncApiId}" ],
                  [ ".", "IntegrationLatency", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "AppSync Latency"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/AppSync", "RequestCount", "GraphQLAPIId", "${AppSyncApiId}" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "AppSync Request Count"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/AppSync", "ThrottledRequests", "GraphQLAPIId", "${AppSyncApiId}" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "AppSync Throttled Requests"
              }
            }
          ]
        }

  AppSync4XXErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${CustomerId}-${ProjectId}-${Environment}-appsync-4xx-error-alarm'
      MetricName: 4XXError
      Namespace: AWS/AppSync
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: GraphQLAPIId
          Value: !Ref AppSyncApiId
      AlarmDescription: 'AppSync 4XX error rate is high.'
      TreatMissingData: notBreaching

  AppSync5XXErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${CustomerId}-${ProjectId}-${Environment}-appsync-5xx-error-alarm'
      MetricName: 5XXError
      Namespace: AWS/AppSync
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: GraphQLAPIId
          Value: !Ref AppSyncApiId
      AlarmDescription: 'AppSync 5XX error rate is high.'
      TreatMissingData: notBreaching

  AppSyncLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${CustomerId}-${ProjectId}-${Environment}-appsync-latency-alarm'
      MetricName: Latency
      Namespace: AWS/AppSync
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2000
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: GraphQLAPIId
          Value: !Ref AppSyncApiId
      AlarmDescription: 'AppSync average latency is high (ms).'
      TreatMissingData: notBreaching

  # Security Monitoring Resources
  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
      FindingPublishingFrequency: FIFTEEN_MINUTES

  SecurityHub:
    Type: AWS::SecurityHub::Hub
    DependsOn: GuardDutyDetector
    Properties:
      EnableDefaultStandards: true

  SecurityDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${CustomerId}-${ProjectId}-${Environment}-security-dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "log",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "query": "SOURCE '/aws/lambda/audit-logger/security'\n| filter event_type = \"UNAUTHORIZED_ACCESS_ATTEMPT\"\n| stats count() by bin(5m)",
                "region": "${AWS::Region}",
                "title": "Unauthorized Access Attempts (5-min intervals)",
                "view": "line"
              }
            },
            {
              "type": "log",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "query": "SOURCE '/aws/lambda/audit-logger/access'\n| filter organization_id != \"\"\n| stats count() as requests by organization_id\n| sort requests desc\n| limit 10",
                "region": "${AWS::Region}",
                "title": "Top 10 Most Active Organizations",
                "view": "table"
              }
            },
            {
              "type": "log",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "query": "SOURCE '/aws/lambda/audit-logger/security'\n| filter event_type in [\"CROSS_ORGANIZATION_ACCESS\", \"PRIVILEGE_ESCALATION\", \"SUSPICIOUS_API_USAGE\"]\n| fields @timestamp, event_type, user_context.user_id, organization_id\n| sort @timestamp desc\n| limit 20",
                "region": "${AWS::Region}",
                "title": "Recent High-Priority Security Events",
                "view": "table"
              }
            },
            {
              "type": "log",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "query": "SOURCE '/aws/lambda/audit-logger/api'\n| filter action_details.response_time_ms > 1000\n| stats count() as slow_requests by organization_id\n| sort slow_requests desc\n| limit 10",
                "region": "${AWS::Region}",
                "title": "Slow API Requests (>1s) by Organization",
                "view": "table"
              }
            }
          ]
        }

  # CloudWatch Anomaly Detection for AppSync metrics
  AppSyncRequestCountAnomalyDetector:
    Type: AWS::CloudWatch::AnomalyDetector
    Properties:
      MetricName: RequestCount
      Namespace: AWS/AppSync
      Stat: Average
      Dimensions:
        - Name: GraphQLAPIId
          Value: !Ref AppSyncApiId

  AppSyncLatencyAnomalyDetector:
    Type: AWS::CloudWatch::AnomalyDetector
    Properties:
      MetricName: Latency
      Namespace: AWS/AppSync
      Stat: Average
      Dimensions:
        - Name: GraphQLAPIId
          Value: !Ref AppSyncApiId

  # Anomaly Detection Alarms
  AppSyncRequestAnomalyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${CustomerId}-${ProjectId}-${Environment}-appsync-request-anomaly'
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      EvaluationPeriods: 2
      Metrics:
        - Id: m1
          ReturnData: true
          MetricStat:
            Metric:
              MetricName: RequestCount
              Namespace: AWS/AppSync
              Dimensions:
                - Name: GraphQLAPIId
                  Value: !Ref AppSyncApiId
            Period: 300
            Stat: Average
        - Id: ad1
          Expression: ANOMALY_DETECTION_FUNCTION(m1, 2)
      ThresholdMetricId: ad1
      ActionsEnabled: true
      AlarmDescription: 'AppSync request count anomaly detected'
      TreatMissingData: breaching

  AppSyncLatencyAnomalyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${CustomerId}-${ProjectId}-${Environment}-appsync-latency-anomaly'
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      EvaluationPeriods: 2
      Metrics:
        - Id: m1
          ReturnData: true
          MetricStat:
            Metric:
              MetricName: Latency
              Namespace: AWS/AppSync
              Dimensions:
                - Name: GraphQLAPIId
                  Value: !Ref AppSyncApiId
            Period: 300
            Stat: Average
        - Id: ad1
          Expression: ANOMALY_DETECTION_FUNCTION(m1, 2)
      ThresholdMetricId: ad1
      ActionsEnabled: true
      AlarmDescription: 'AppSync latency anomaly detected'
      TreatMissingData: breaching
