# file: schemas/tables/application_users.yml
# author: AI Assistant
# date: 2024-03-21
# description: yaml file containing the application users table schema

version: '1.0'
table: ApplicationUsers
model:
  auth_config:
    default_auth: user_pools
  keys:
    primary:
      partition: application_id
      sort: user_id
      projection_type: ALL
      description: Primary key for application users
    secondary:
      - name: user-applications-index
        type: GSI
        partition: user_id
        sort: application_id
        projection_type: ALL
        description: Index for querying applications by user
      - name: application-role-index
        type: GSI
        partition: application_id
        sort: role_id
        projection_type: ALL
        description: Index for querying users by role within an application
      - name: user-status-index
        type: GSI
        partition: application_id
        sort: status
        projection_type: ALL
        description: Index for querying users by status within an application
  attributes:
    application_id:
      type: string
      required: true
      description: Unique identifier for the application
    user_id:
      type: string
      required: true
      description: Unique identifier for the user
    role_id:
      type: string
      required: false
      description: Unique identifier for the role assigned to the user
    status:
      type: string
      enum_type: ApplicationUserStatus
      required: true
      description: Current status of the user in the application (ACTIVE, INACTIVE, DELETED)
    created_at:
      type: number
      required: true
      description: Unix timestamp when the user was added to the application
    updated_at:
      type: number
      required: false
      description: Unix timestamp when the user's application details were last updated 