# file: schemas/tables/applications.yml
# author: AI Assistant
# date: 2024-03-21
# description: yaml file containing the applications table schema

version: '1.0'
table: Applications
model:
  auth_config:
    default_auth: user_pools
  keys:
    primary:
      partition: application_id
      projection_type: ALL
      description: Primary key for applications
    secondary:
      - name: application-status-index
        type: GSI
        partition: application_id
        sort: status
        projection_type: ALL
        description: Index for querying applications by status
  attributes:
    application_id:
      type: string
      required: true
      description: Unique identifier for the application
    name:
      type: string
      required: true
      description: Human-readable name of the application
    description:
      type: string
      required: false
      description: Human-readable description of the application
    status:
      type: string
      enum_type: ApplicationStatus
      required: true
      description: Current status of the application (ACTIVE, INACTIVE, DELETED)
    created_at:
      type: number
      required: true
      description: Unix timestamp when the application was created
    updated_at:
      type: number
      required: true
      description: Unix timestamp when the application was last updated
    user_id:
      type: string
      required: true
      description: Unique identifier for the user who created the application 