# AUTO-GENERATED by orb-schema-generator v0.13.5 - DO NOT EDIT
# Regenerate with: orb-schema generate
from aws_cdk import (
    aws_dynamodb as dynamodb,
)
from constructs import Construct


class UsersTable(Construct):
    """DynamoDB table construct for Users."""

    def __init__(self, scope: Construct, id: str) -> None:
        super().__init__(scope, id)

        self.table = dynamodb.Table(
            self, "Users",
            table_name="orb-integration-hub-dev-table-users",
            partition_key=dynamodb.Attribute(
                name="userId",
                type=dynamodb.AttributeType.STRING,
            ),
            billing_mode=dynamodb.BillingMode.PAY_PER_REQUEST,
            stream=dynamodb.StreamViewType.NEW_AND_OLD_IMAGES,
        )

        self.table.add_global_secondary_index(
            index_name="EmailIndex",
            partition_key=dynamodb.Attribute(
                name="email",
                type=dynamodb.AttributeType.STRING,
            ),
            projection_type=dynamodb.ProjectionType.ALL,
        )

        self.table.add_global_secondary_index(
            index_name="CognitoIdIndex",
            partition_key=dynamodb.Attribute(
                name="cognitoId",
                type=dynamodb.AttributeType.STRING,
            ),
            projection_type=dynamodb.ProjectionType.ALL,
        )

        self.table.add_global_secondary_index(
            index_name="CognitoSubIndex",
            partition_key=dynamodb.Attribute(
                name="cognitoSub",
                type=dynamodb.AttributeType.STRING,
            ),
            projection_type=dynamodb.ProjectionType.ALL,
        )