// AUTO-GENERATED by e2e-test-generator v0.1.0 - DO NOT EDIT
// Regenerate with: python -m tools.e2e_generator generate

/**
 * Page Object Model for ApplicationRoles
 */

import { Page, Locator } from '@playwright/test';

export class ApplicationRolesPage {
  readonly page: Page;

  // Locators
  readonly pageTitle: Locator;
  readonly dataGrid: Locator;
  readonly createButton: Locator;
  readonly submitButton: Locator;
  readonly editButton: Locator;
  readonly deleteButton: Locator;
  readonly confirmDeleteButton: Locator;
  readonly successMessage: Locator;
  readonly paginationControls: Locator;
  readonly nextPageButton: Locator;
  readonly filterInput: Locator;
  readonly applicationroleidInput: Locator;
  readonly applicationroleidDisplay: Locator;
  readonly applicationidInput: Locator;
  readonly applicationidDisplay: Locator;
  readonly roleidInput: Locator;
  readonly roleidDisplay: Locator;
  readonly rolenameInput: Locator;
  readonly rolenameDisplay: Locator;
  readonly roletypeInput: Locator;
  readonly roletypeDisplay: Locator;
  readonly descriptionInput: Locator;
  readonly descriptionDisplay: Locator;
  readonly statusInput: Locator;
  readonly statusDisplay: Locator;
  readonly createdatInput: Locator;
  readonly createdatDisplay: Locator;
  readonly updatedatInput: Locator;
  readonly updatedatDisplay: Locator;

  constructor(page: Page) {
    this.page = page;

    // Initialize locators
    this.pageTitle = page.locator('h1, h2').first();
    this.dataGrid = page.locator('app-data-grid, table');
    this.createButton = page.locator('button:has-text("Create")');
    this.submitButton = page.locator('button[type="submit"]');
    this.editButton = page.locator('button:has-text("Edit")');
    this.deleteButton = page.locator('button:has-text("Delete")');
    this.confirmDeleteButton = page.locator('button:has-text("Confirm")');
    this.successMessage = page.locator('.success-message, .alert-success');
    this.paginationControls = page.locator('.pagination, app-pagination');
    this.nextPageButton = page.locator('button:has-text("Next")');
    this.filterInput = page.locator('input[placeholder*="Filter"], input[placeholder*="Search"]');
    this.applicationroleidInput = page.locator('input[name="applicationRoleId"], input[formControlName="applicationRoleId"]');
    this.applicationroleidDisplay = page.locator('[data-field="applicationRoleId"]');
    this.applicationidInput = page.locator('input[name="applicationId"], input[formControlName="applicationId"]');
    this.applicationidDisplay = page.locator('[data-field="applicationId"]');
    this.roleidInput = page.locator('input[name="roleId"], input[formControlName="roleId"]');
    this.roleidDisplay = page.locator('[data-field="roleId"]');
    this.rolenameInput = page.locator('input[name="roleName"], input[formControlName="roleName"]');
    this.rolenameDisplay = page.locator('[data-field="roleName"]');
    this.roletypeInput = page.locator('input[name="roleType"], input[formControlName="roleType"]');
    this.roletypeDisplay = page.locator('[data-field="roleType"]');
    this.descriptionInput = page.locator('input[name="description"], input[formControlName="description"]');
    this.descriptionDisplay = page.locator('[data-field="description"]');
    this.statusInput = page.locator('input[name="status"], input[formControlName="status"]');
    this.statusDisplay = page.locator('[data-field="status"]');
    this.createdatInput = page.locator('input[name="createdAt"], input[formControlName="createdAt"]');
    this.createdatDisplay = page.locator('[data-field="createdAt"]');
    this.updatedatInput = page.locator('input[name="updatedAt"], input[formControlName="updatedAt"]');
    this.updatedatDisplay = page.locator('[data-field="updatedAt"]');
  }

  // Navigation methods
  async goToList() {
    await this.page.goto('/applications/:applicationId/roles');
    await this.page.waitForLoadState('networkidle');
  }

  async goToDetail(id: string) {
    const url = '/applications/:applicationId/roles/:id'.replace(':id', id);
    await this.page.goto(url);
    await this.page.waitForLoadState('networkidle');
  }

  async goToCreate() {
    await this.page.goto('/applications/:applicationId/roles/new');
    await this.page.waitForLoadState('networkidle');
  }

  // Interaction methods
  async clickCreate() {
    await this.createButton.click();
  }

  async clickSubmit() {
    await this.submitButton.click();
  }

  async clickEdit() {
    await this.editButton.click();
  }

  async clickDelete() {
    await this.deleteButton.click();
  }

  async confirmDelete() {
    await this.confirmDeleteButton.click();
  }

  async clickFirstRow() {
    await this.dataGrid.locator('tr').nth(1).click();
  }

  async clickNextPage() {
    await this.nextPageButton.click();
  }

  async applyFilter(filterText: string) {
    await this.filterInput.fill(filterText);
  }

  async clickSortColumn(columnName: string) {
    await this.dataGrid.locator(`th:has-text("${columnName}")`).click();
  }

  async fillApplicationroleid(value: string) {
    await this.applicationroleidInput.fill(value);
  }

  async fillApplicationid(value: string) {
    await this.applicationidInput.fill(value);
  }

  async fillRoleid(value: string) {
    await this.roleidInput.fill(value);
  }

  async fillRolename(value: string) {
    await this.rolenameInput.fill(value);
  }

  async fillRoletype(value: string) {
    await this.roletypeInput.fill(value);
  }

  async fillDescription(value: string) {
    await this.descriptionInput.fill(value);
  }

  async fillStatus(value: string) {
    await this.statusInput.fill(value);
  }

  async fillCreatedat(value: string) {
    await this.createdatInput.fill(value);
  }

  async fillUpdatedat(value: string) {
    await this.updatedatInput.fill(value);
  }

  // Assertion helpers
  getPageTitle() {
    return this.pageTitle;
  }

  getDataGrid() {
    return this.dataGrid;
  }

  getSuccessMessage() {
    return this.successMessage;
  }

  getPaginationControls() {
    return this.paginationControls;
  }

  getFirstRow() {
    return this.dataGrid.locator('tr').nth(1);
  }

  getApplicationroleidDisplay() {
    return this.applicationroleidDisplay;
  }

  getApplicationidDisplay() {
    return this.applicationidDisplay;
  }

  getRoleidDisplay() {
    return this.roleidDisplay;
  }

  getRolenameDisplay() {
    return this.rolenameDisplay;
  }

  getRoletypeDisplay() {
    return this.roletypeDisplay;
  }

  getDescriptionDisplay() {
    return this.descriptionDisplay;
  }

  getStatusDisplay() {
    return this.statusDisplay;
  }

  getCreatedatDisplay() {
    return this.createdatDisplay;
  }

  getUpdatedatDisplay() {
    return this.updatedatDisplay;
  }
}