name: Bug Report
description: Report a technical issue or error with orb-integration-hub resources
title: "[BUG] "
labels: ["type/bug", "status/needs-triage"]
assignees: ["orb-integration-hub-team"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us resolve the issue quickly.
        
        **Before submitting**: Please check existing issues to avoid duplicates.

  - type: dropdown
    id: reporting-team
    attributes:
      label: Reporting Team
      description: Which team are you reporting this issue from?
      options:
        - Development Team
        - DevOps Team
        - Product Team
        - External Team
        - Other (specify in description)
    validations:
      required: true

  - type: input
    id: team-contact
    attributes:
      label: Team Contact
      description: Primary contact person or team email for follow-up
      placeholder: "e.g., john.doe@company.com or @team-handle"
    validations:
      required: true

  - type: input
    id: error-code
    attributes:
      label: Error Code/Status
      description: HTTP status code, AWS error code, or specific error message
      placeholder: "e.g., 403 Forbidden, InvalidParameterValue, AccessDenied"
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: Complete Error Message
      description: Full error message or stack trace (if available)
      placeholder: "Paste the complete error message here..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Go to...
        2. Click on...
        3. Run command...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
      placeholder: "Describe what you expected to happen..."
    validations:
      required: true

  - type: textarea
    id: environment-details
    attributes:
      label: Environment Details
      description: AWS region, account ID, resource ARNs, workflow names, etc.
      placeholder: |
        - AWS Region: us-east-1
        - Account ID: 123456789012
        - Resource ARN: arn:aws:codeartifact:us-east-1:123456789012:domain/example
        - Workflow Name: deploy-shared
        - Repository: org/repo-name
    validations:
      required: true

  - type: dropdown
    id: service-type
    attributes:
      label: AWS Service Involved
      description: Which AWS service is primarily involved in this issue?
      options:
        - CodeArtifact
        - IAM (Roles/Policies)
        - CloudFormation
        - Parameter Store (SSM)
        - GitHub Actions (OIDC)
        - Multiple Services
        - Other (specify below)
    validations:
      required: true

  - type: textarea
    id: codeartifact-details
    attributes:
      label: CodeArtifact Details (if applicable)
      description: Domain name, repository name, package information
      placeholder: |
        - Domain: orb-integration-hub-shared-codeartifact-domain
        - Repository: orb-integration-hub-shared-codeartifact-repo
        - Package Name: my-package
        - Package Version: 1.0.0
        - Package Format: pypi

  - type: textarea
    id: github-actions-details
    attributes:
      label: GitHub Actions Details (if applicable)
      description: Workflow name, job name, run ID, failure step
      placeholder: |
        - Workflow: deploy-bootstrap
        - Job: deploy
        - Run ID: 1234567890
        - Failed Step: Configure AWS credentials
        - Repository: org/repo-name

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or relevant information
      placeholder: "Add any other context about the problem here..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have included all required environment details
          required: true
        - label: I have provided the complete error message
          required: true
        - label: I have included steps to reproduce the issue
          required: true