name: Technical Debt Tracking
description: Track and prioritize technical debt for resolution
title: "[TECH-DEBT] "
labels: ["type/maintenance", "category/technical-debt", "status/needs-prioritization"]
assignees: ["orb-integration-hub-team"]
body:
  - type: markdown
    attributes:
      value: |
        **Technical Debt Tracking Template**
        
        Use this template to document technical debt that needs to be addressed. Technical debt includes 
        code quality issues, outdated dependencies, suboptimal implementations, and maintenance tasks 
        that improve the long-term health of the codebase.

  - type: dropdown
    id: debt-type
    attributes:
      label: Technical Debt Type
      description: What type of technical debt is this?
      options:
        - Code Quality Issues
        - Outdated Dependencies
        - Performance Bottlenecks
        - Security Vulnerabilities
        - Documentation Gaps
        - Test Coverage Issues
        - Architecture Improvements
        - Refactoring Needs
        - Configuration Management
        - Monitoring and Observability
        - Other (specify below)
    validations:
      required: true

  - type: input
    id: affected-component
    attributes:
      label: Affected Component/Module
      description: Which component, module, or system is affected?
      placeholder: "e.g., bootstrap-stack, codeartifact-construct, github-actions-workflows"
    validations:
      required: true

  - type: textarea
    id: debt-description
    attributes:
      label: Technical Debt Description
      description: Detailed description of the technical debt
      placeholder: |
        - What is the current suboptimal implementation?
        - Why is this considered technical debt?
        - What are the symptoms or problems it causes?
    validations:
      required: true

  - type: textarea
    id: current-impact
    attributes:
      label: Current Impact
      description: How is this technical debt currently affecting the system or team?
      placeholder: |
        - Performance impact (specific metrics if available)
        - Maintenance burden (time spent on workarounds)
        - Developer productivity impact
        - Risk to system stability
        - Security implications
    validations:
      required: true

  - type: dropdown
    id: severity-level
    attributes:
      label: Severity Level
      description: How severe is this technical debt?
      options:
        - Critical (Causing active problems)
        - High (Significant impact on productivity/performance)
        - Medium (Noticeable but manageable impact)
        - Low (Minor inconvenience)
    validations:
      required: true

  - type: textarea
    id: code-quality-metrics
    attributes:
      label: Code Quality Metrics
      description: Specific code quality issues and metrics (if applicable)
      placeholder: |
        - Cyclomatic complexity: X
        - Code duplication: Y lines/files
        - Test coverage: Z%
        - Static analysis warnings: N issues
        - Performance benchmarks: X ms/requests per second
    validations:
      required: true

  - type: textarea
    id: refactoring-requirements
    attributes:
      label: Refactoring Requirements
      description: What specific refactoring or improvements are needed?
      placeholder: |
        - Extract common functionality into shared modules
        - Simplify complex conditional logic
        - Improve error handling patterns
        - Update to modern language features
        - Consolidate duplicate code
        - Improve naming and documentation
    validations:
      required: true

  - type: dropdown
    id: estimated-effort
    attributes:
      label: Estimated Effort to Resolve
      description: Rough estimate of the effort required to address this debt
      options:
        - Small (1-2 days)
        - Medium (3-5 days)
        - Large (1-2 weeks)
        - Extra Large (2+ weeks)
        - Unknown (needs investigation)
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should this technical debt be addressed?
      placeholder: |
        - Specific refactoring approach
        - Technology upgrades needed
        - Architecture changes required
        - Testing strategy for changes
        - Migration plan (if applicable)

  - type: textarea
    id: benefits-of-resolution
    attributes:
      label: Benefits of Resolution
      description: What benefits will be gained by addressing this technical debt?
      placeholder: |
        - Improved performance (specific metrics)
        - Reduced maintenance burden
        - Enhanced security posture
        - Better developer experience
        - Increased system reliability
        - Easier future enhancements

  - type: textarea
    id: risks-of-not-addressing
    attributes:
      label: Risks of Not Addressing
      description: What are the risks if this technical debt is not addressed?
      placeholder: |
        - Increasing maintenance costs
        - Performance degradation over time
        - Security vulnerabilities
        - Difficulty implementing new features
        - Team productivity decline
        - System stability risks

  - type: dropdown
    id: priority-recommendation
    attributes:
      label: Priority Recommendation
      description: What priority do you recommend for addressing this debt?
      options:
        - Immediate (Should be addressed in current sprint)
        - High (Should be addressed in next 1-2 sprints)
        - Medium (Should be addressed in next quarter)
        - Low (Can be addressed when time permits)
        - Backlog (Document for future consideration)

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies and Blockers
      description: What dependencies or blockers exist for addressing this debt?
      placeholder: |
        - Depends on completion of other tasks
        - Requires coordination with other teams
        - Needs approval for breaking changes
        - Blocked by external dependencies
        - Requires additional tooling or infrastructure

  - type: textarea
    id: testing-strategy
    attributes:
      label: Testing Strategy
      description: How should changes be tested to ensure no regressions?
      placeholder: |
        - Existing test coverage to maintain
        - New tests needed for refactored code
        - Performance testing requirements
        - Integration testing needs
        - Rollback testing procedures

  - type: textarea
    id: security-considerations
    attributes:
      label: Security Considerations
      description: Are there any security implications of this technical debt or its resolution?
      placeholder: |
        - Current security risks from the debt
        - Security improvements from resolution
        - Security testing needed for changes
        - Compliance considerations
    validations:
      required: true

  - type: textarea
    id: monitoring-metrics
    attributes:
      label: Success Metrics and Monitoring
      description: How will we measure the success of addressing this technical debt?
      placeholder: |
        - Performance metrics to track
        - Code quality metrics to improve
        - Maintenance time reduction targets
        - Error rate improvements
        - Developer productivity metrics

  - type: checkboxes
    id: checklist
    attributes:
      label: Technical Debt Assessment Checklist
      description: Please confirm these items have been considered
      options:
        - label: I have assessed the current impact on the system
          required: true
        - label: I have identified specific code quality issues
          required: true
        - label: I have considered security implications
          required: true
        - label: I have estimated the effort required for resolution
          required: true
        - label: I have identified the benefits and risks
          required: true