# AUTO-GENERATED by orb-schema-generator v1.1.0 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Application group user membership status
"""

from enum import StrEnum


class ApplicationGroupUserStatus(StrEnum):
    """Application group user membership status"""

    # Unknown status
    UNKNOWN = "UNKNOWN"
    # Active membership
    ACTIVE = "ACTIVE"
    # User removed from group
    REMOVED = "REMOVED"
    # User invited to group (pending acceptance)
    INVITED = "INVITED"

    def to_json(self) -> str:
        """Convert enum to JSON string value."""
        return self.value

    @classmethod
    def from_json(cls, value: str) -> "ApplicationGroupUserStatus":
        """Create enum from JSON string value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"Unknown ApplicationGroupUserStatus value: {value}")