# AUTO-GENERATED by orb-schema-generator v1.3.0 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Application group role assignment status
"""

from enum import StrEnum


class ApplicationGroupRoleStatus(StrEnum):
    """Application group role assignment status"""

    # Unknown status
    UNKNOWN = "UNKNOWN"
    # Active role assignment
    ACTIVE = "ACTIVE"
    # Deleted role assignment
    DELETED = "DELETED"

    def to_json(self) -> str:
        """Convert enum to JSON string value."""
        return self.value

    @classmethod
    def from_json(cls, value: str) -> "ApplicationGroupRoleStatus":
        """Create enum from JSON string value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"Unknown ApplicationGroupRoleStatus value: {value}")