# AUTO-GENERATED by orb-schema-generator v2.0.3 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Authentication flow step states
"""

from enum import StrEnum


class AuthStep(StrEnum):
    """Authentication flow step states"""

    # Unknown step
    UNKNOWN = "UNKNOWN"
    # Initial email entry step
    EMAIL_ENTRY = "EMAIL_ENTRY"
    # Email step (alias for EMAIL_ENTRY)
    EMAIL = "EMAIL"
    # Password entry for existing users
    PASSWORD = "PASSWORD"
    # Password verification step
    PASSWORD_VERIFY = "PASSWORD_VERIFY"
    # Password setup for new users
    PASSWORD_SETUP = "PASSWORD_SETUP"
    # Email verification code entry
    EMAIL_VERIFY = "EMAIL_VERIFY"
    # Sign in step for verified users
    SIGNIN = "SIGNIN"
    # MFA setup for users without MFA
    MFA_SETUP = "MFA_SETUP"
    # MFA code verification
    MFA_VERIFY = "MFA_VERIFY"
    # Password reset initiation
    PASSWORD_RESET = "PASSWORD_RESET"
    # Password reset code verification
    PASSWORD_RESET_VERIFY = "PASSWORD_RESET_VERIFY"
    # New password confirmation
    PASSWORD_RESET_CONFIRM = "PASSWORD_RESET_CONFIRM"
    # Authentication flow complete
    COMPLETE = "COMPLETE"

    def to_json(self) -> str:
        """Convert enum to JSON string value."""
        return self.value

    @classmethod
    def from_json(cls, value: str) -> "AuthStep":
        """Create enum from JSON string value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"Unknown AuthStep value: {value}")