# AUTO-GENERATED by orb-schema-generator v0.13.5 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Generated Python enum for ErrorRegistry
"""

from enum import StrEnum


class ErrorRegistry(StrEnum):
    """ErrorRegistry enum."""

    # The provided email address format is invalid
    ORB_AUTH_001 = "orb-auth-001"
    # The provided email and password combination is invalid
    ORB_AUTH_002 = "orb-auth-002"
    # Failed to verify email with provided code
    ORB_AUTH_003 = "orb-auth-003"
    # A user with this email already exists
    ORB_AUTH_004 = "orb-auth-004"
    # Failed to check if user exists by email
    ORB_AUTH_005 = "orb-auth-005"
    # An error occurred while executing a GraphQL query
    ORB_API_001 = "orb-api-001"
    # An error occurred while executing a GraphQL mutation
    ORB_API_002 = "orb-api-002"
    # The input provided for a GraphQL operation was invalid
    ORB_API_003 = "orb-api-003"
    # A network error occurred while communicating with the API
    ORB_API_004 = "orb-api-004"
    # The data format provided is invalid
    ORB_DATA_001 = "orb-data-001"
    # The requested data was not found
    ORB_DATA_002 = "orb-data-002"
    # An unexpected error occurred
    ORB_SYS_001 = "orb-sys-001"

    def to_json(self) -> str:
        """Convert enum to JSON string value."""
        return self.value

    @classmethod
    def from_json(cls, value: str) -> "ErrorRegistry":
        """Create enum from JSON string value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"Unknown ErrorRegistry value: {value}")