# AUTO-GENERATED by orb-schema-generator v0.17.0 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Legal basis for privacy requests under various regulations
"""

from enum import StrEnum


class LegalBasis(StrEnum):
    """Legal basis for privacy requests under various regulations"""

    # GDPR Article 15 - Right of access by the data subject
    GDPR_ARTICLE_15_RIGHT_OF_ACCESS = "GDPR_ARTICLE_15_RIGHT_OF_ACCESS"
    # GDPR Article 17 - Right to erasure (right to be forgotten)
    GDPR_ARTICLE_17_RIGHT_TO_ERASURE = "GDPR_ARTICLE_17_RIGHT_TO_ERASURE"
    # GDPR Article 20 - Right to data portability
    GDPR_ARTICLE_20_DATA_PORTABILITY = "GDPR_ARTICLE_20_DATA_PORTABILITY"
    # CCPA - Right to know what personal information is collected
    CCPA_RIGHT_TO_KNOW = "CCPA_RIGHT_TO_KNOW"
    # CCPA - Right to delete personal information
    CCPA_RIGHT_TO_DELETE = "CCPA_RIGHT_TO_DELETE"
    # CCPA - Right to opt out of sale of personal information
    CCPA_RIGHT_TO_OPT_OUT = "CCPA_RIGHT_TO_OPT_OUT"

    def to_json(self) -> str:
        """Convert enum to JSON string value."""
        return self.value

    @classmethod
    def from_json(cls, value: str) -> "LegalBasis":
        """Create enum from JSON string value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"Unknown LegalBasis value: {value}")