# AUTO-GENERATED by orb-schema-generator v0.13.2 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Status of a notification
"""

from enum import StrEnum


class NotificationStatus(StrEnum):
    """Status of a notification"""

    # Notification is pending delivery or action
    PENDING = "PENDING"
    # Notification has been read
    READ = "READ"
    # Notification was dismissed by user
    DISMISSED = "DISMISSED"
    # Notification has expired
    EXPIRED = "EXPIRED"

    def to_json(self) -> str:
        """Convert enum to JSON string value."""
        return self.value

    @classmethod
    def from_json(cls, value: str) -> "NotificationStatus":
        """Create enum from JSON string value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"Unknown NotificationStatus value: {value}")