# AUTO-GENERATED by orb-schema-generator v0.13.6 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Types of notifications that can be sent to users
"""

from enum import StrEnum


class NotificationType(StrEnum):
    """Types of notifications that can be sent to users"""

    # Request to transfer application ownership
    APPLICATION_TRANSFER_REQUEST = "APPLICATION_TRANSFER_REQUEST"
    # Application ownership transfer completed
    APPLICATION_TRANSFER_COMPLETED = "APPLICATION_TRANSFER_COMPLETED"
    # User received an organization invitation
    ORGANIZATION_INVITATION_RECEIVED = "ORGANIZATION_INVITATION_RECEIVED"
    # Organization invitation was accepted
    ORGANIZATION_INVITATION_ACCEPTED = "ORGANIZATION_INVITATION_ACCEPTED"
    # Organization invitation was rejected
    ORGANIZATION_INVITATION_REJECTED = "ORGANIZATION_INVITATION_REJECTED"

    def to_json(self) -> str:
        """Convert enum to JSON string value."""
        return self.value

    @classmethod
    def from_json(cls, value: str) -> "NotificationType":
        """Create enum from JSON string value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"Unknown NotificationType value: {value}")