# AUTO-GENERATED by orb-schema-generator v0.13.6 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Status of a user's membership in an organization
"""

from enum import StrEnum


class OrganizationUserStatus(StrEnum):
    """Status of a user's membership in an organization"""

    # User is an active member
    ACTIVE = "ACTIVE"
    # User membership is inactive
    INACTIVE = "INACTIVE"
    # User has been invited but not yet responded
    INVITED = "INVITED"
    # User membership is pending approval
    PENDING = "PENDING"
    # User membership was rejected
    REJECTED = "REJECTED"
    # User was removed from the organization
    REMOVED = "REMOVED"

    def to_json(self) -> str:
        """Convert enum to JSON string value."""
        return self.value

    @classmethod
    def from_json(cls, value: str) -> "OrganizationUserStatus":
        """Create enum from JSON string value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"Unknown OrganizationUserStatus value: {value}")