# AUTO-GENERATED by orb-schema-generator v0.18.2 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Status of an ownership transfer request
"""

from enum import StrEnum


class OwnershipTransferStatus(StrEnum):
    """Status of an ownership transfer request"""

    # Payment validation is required before transfer
    PAYMENT_VALIDATION_REQUIRED = "PAYMENT_VALIDATION_REQUIRED"
    # Payment is being processed
    PAYMENT_IN_PROGRESS = "PAYMENT_IN_PROGRESS"
    # Payment has been validated
    PAYMENT_VALIDATED = "PAYMENT_VALIDATED"
    # Transfer has been completed
    COMPLETED = "COMPLETED"
    # Transfer request has expired
    EXPIRED = "EXPIRED"
    # Transfer was cancelled
    CANCELLED = "CANCELLED"

    def to_json(self) -> str:
        """Convert enum to JSON string value."""
        return self.value

    @classmethod
    def from_json(cls, value: str) -> "OwnershipTransferStatus":
        """Create enum from JSON string value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"Unknown OwnershipTransferStatus value: {value}")
