# AUTO-GENERATED by orb-schema-generator v2.0.3 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Recovery actions determined by the smart check flow
"""

from enum import StrEnum


class RecoveryAction(StrEnum):
    """Recovery actions determined by the smart check flow"""

    # Unknown action
    UNKNOWN = "UNKNOWN"
    # User needs to complete new signup
    NEW_SIGNUP = "NEW_SIGNUP"
    # Resend email verification code
    RESEND_VERIFICATION = "RESEND_VERIFICATION"
    # Create DynamoDB record for existing Cognito user
    CREATE_DYNAMO_RECORD = "CREATE_DYNAMO_RECORD"
    # User can proceed to login
    LOGIN = "LOGIN"
    # User needs to reset password
    PASSWORD_RESET = "PASSWORD_RESET"
    # User needs to contact support
    CONTACT_SUPPORT = "CONTACT_SUPPORT"

    def to_json(self) -> str:
        """Convert enum to JSON string value."""
        return self.value

    @classmethod
    def from_json(cls, value: str) -> "RecoveryAction":
        """Create enum from JSON string value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"Unknown RecoveryAction value: {value}")