# AUTO-GENERATED by orb-schema-generator v0.13.3 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Types of roles
"""

from enum import StrEnum


class RoleType(StrEnum):
    """Types of roles"""

    # Unknown role type
    UNKNOWN = "UNKNOWN"
    # Administrator role
    ADMIN = "ADMIN"
    # Standard user role
    USER = "USER"
    # Guest role
    GUEST = "GUEST"
    # Custom role
    CUSTOM = "CUSTOM"

    def to_json(self) -> str:
        """Convert enum to JSON string value."""
        return self.value

    @classmethod
    def from_json(cls, value: str) -> "RoleType":
        """Create enum from JSON string value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"Unknown RoleType value: {value}")