# AUTO-GENERATED by orb-schema-generator v0.16.0 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Types of schemas supported by the schema generator
"""

from enum import StrEnum


class SchemaType(StrEnum):
    """Types of schemas supported by the schema generator"""

    # Standard schema type
    STANDARD = "STANDARD"
    # DynamoDB table schema
    DYNAMODB = "DYNAMODB"
    # PostgreSQL database schema
    POSTGRES = "POSTGRES"
    # MySQL database schema
    MYSQL = "MYSQL"
    # Microsoft SQL Server schema
    MSSQL = "MSSQL"
    # SQLite database schema
    SQLITE = "SQLITE"
    # AWS Lambda function schema
    LAMBDA = "LAMBDA"
    # Secured AWS Lambda function schema
    LAMBDA_SECURED = "LAMBDA_SECURED"
    # GraphQL schema
    GRAPHQL = "GRAPHQL"
    # Registry/enum schema
    REGISTRY = "REGISTRY"
    # Graph database schema
    GRAPH = "GRAPH"
    # REST API schema
    REST = "REST"
    # Elasticsearch schema
    ELASTICSEARCH = "ELASTICSEARCH"

    def to_json(self) -> str:
        """Convert enum to JSON string value."""
        return self.value

    @classmethod
    def from_json(cls, value: str) -> "SchemaType":
        """Create enum from JSON string value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"Unknown SchemaType value: {value}")