# AUTO-GENERATED by orb-schema-generator v2.0.3 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
User group types for Cognito authentication. Groups are additive - users can have multiple groups. Every user has at least USER group (baseline). CUSTOMER group is added when user pays for subscription.
"""

from enum import StrEnum


class UserGroup(StrEnum):
    """User group types for Cognito authentication. Groups are additive - users can have multiple groups. Every user has at least USER group (baseline). CUSTOMER group is added when user pays for subscription."""

    # Baseline group for all authenticated users
    USER = "USER"
    # User paying for platform subscription - can create organizations
    CUSTOMER = "CUSTOMER"
    # Internal platform team member
    EMPLOYEE = "EMPLOYEE"
    # Platform owner with full administrative access
    OWNER = "OWNER"

    def to_json(self) -> str:
        """Convert enum to JSON string value."""
        return self.value

    @classmethod
    def from_json(cls, value: str) -> "UserGroup":
        """Create enum from JSON string value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"Unknown UserGroup value: {value}")