# AUTO-GENERATED by orb-schema-generator v0.19.0 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
User account status
"""

from enum import StrEnum


class UserStatus(StrEnum):
    """User account status"""

    # Unknown status
    UNKNOWN = "UNKNOWN"
    # Active user
    ACTIVE = "ACTIVE"
    # Inactive user
    INACTIVE = "INACTIVE"
    # Pending activation
    PENDING = "PENDING"
    # Rejected user
    REJECTED = "REJECTED"
    # Deleted user
    DELETED = "DELETED"

    def to_json(self) -> str:
        """Convert enum to JSON string value."""
        return self.value

    @classmethod
    def from_json(cls, value: str) -> "UserStatus":
        """Create enum from JSON string value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"Unknown UserStatus value: {value}")
