# AUTO-GENERATED by orb-schema-generator v2.0.3 - DO NOT EDIT
# Regenerate with: orb-schema generate
"""
Types of events that can trigger webhooks
"""

from enum import StrEnum


class WebhookEventType(StrEnum):
    """Types of events that can trigger webhooks"""

    # Unknown event type
    UNKNOWN = "UNKNOWN"
    # A new user was created in the application
    USER_CREATED = "USER_CREATED"
    # A user's profile was updated
    USER_UPDATED = "USER_UPDATED"
    # A user was deleted from the application
    USER_DELETED = "USER_DELETED"
    # A new group was created
    GROUP_CREATED = "GROUP_CREATED"
    # A group was updated
    GROUP_UPDATED = "GROUP_UPDATED"
    # A group was deleted
    GROUP_DELETED = "GROUP_DELETED"
    # A role was assigned to a user or group
    ROLE_ASSIGNED = "ROLE_ASSIGNED"
    # A role was revoked from a user or group
    ROLE_REVOKED = "ROLE_REVOKED"

    def to_json(self) -> str:
        """Convert enum to JSON string value."""
        return self.value

    @classmethod
    def from_json(cls, value: str) -> "WebhookEventType":
        """Create enum from JSON string value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"Unknown WebhookEventType value: {value}")