"""
Generated Python enum for NotificationType
Generated at 
"""

from enum import Enum

class NotificationType(Enum):

    APPLICATION_TRANSFER_REQUEST = "APPLICATION_TRANSFER_REQUEST"

    APPLICATION_TRANSFER_COMPLETED = "APPLICATION_TRANSFER_COMPLETED"

    ORGANIZATION_INVITATION_RECEIVED = "ORGANIZATION_INVITATION_RECEIVED"

    ORGANIZATION_INVITATION_ACCEPTED = "ORGANIZATION_INVITATION_ACCEPTED"

    ORGANIZATION_INVITATION_REJECTED = "ORGANIZATION_INVITATION_REJECTED"

    ORGANIZATION_INVITATION_DECLINED = "ORGANIZATION_INVITATION_DECLINED"

    ORGANIZATION_INVITATION_EXPIRED = "ORGANIZATION_INVITATION_EXPIRED"

    ORGANIZATION_INVITATION_REVOKED = "ORGANIZATION_INVITATION_REVOKED"

    ORGANIZATION_INVITATION_RESENT = "ORGANIZATION_INVITATION_RESENT"
 