/**
 * Organization Service
 * 
 * Provides CRUD operations for organization management.
 * Handles API communication for organization-related functionality.
 */

import { Injectable } from '@angular/core';
import { GraphQLResult } from '@aws-amplify/api-graphql';
import { Observable, from } from 'rxjs';
import { map, catchError, switchMap } from 'rxjs/operators';

import { ApiService } from './api.service';
import { OrganizationsMutation } from '../graphql/Organizations.graphql';
import {
  Organizations,
  OrganizationsCreateInput,
  OrganizationsUpdateInput,
  OrganizationsResponse,
  OrganizationsCreateResponse,
  OrganizationsUpdateResponse,
  OrganizationsListResponse
} from '../models/OrganizationsModel';
import { OrganizationStatus } from '../enums/OrganizationStatusEnum';

interface AuthCheckResult {
  isAuthenticated: boolean;
  error?: string;
}

@Injectable({
  providedIn: 'root'
})
export class OrganizationService extends ApiService {

  constructor() {
    super();
  }

  /**
   * Check if user is properly authenticated for userPool operations
   */
  private async checkAuthentication(): Promise<AuthCheckResult> {
    try {
      const { fetchAuthSession } = await import('@aws-amplify/auth');
      const session = await fetchAuthSession();
      
      const hasAccessToken = !!session.tokens?.accessToken;
      const hasIdToken = !!session.tokens?.idToken;
      
      if (!hasAccessToken || !hasIdToken) {
        return {
          isAuthenticated: false,
          error: 'Missing authentication tokens'
        };
      }

      // Check if tokens are expired
      const now = Math.floor(Date.now() / 1000);
      const accessTokenExp = session.tokens?.accessToken?.payload?.exp as number;
      const idTokenExp = session.tokens?.idToken?.payload?.exp as number;
      
      if (!accessTokenExp || !idTokenExp || accessTokenExp <= now || idTokenExp <= now) {
        return {
          isAuthenticated: false,
          error: 'Authentication tokens have expired or are invalid'
        };
      }

      console.debug('[OrganizationService] Authentication check passed', {
        hasAccessToken,
        hasIdToken,
        accessTokenExp: new Date(accessTokenExp * 1000),
        idTokenExp: new Date(idTokenExp * 1000)
      });

      return { isAuthenticated: true };
    } catch (error) {
      console.error('[OrganizationService] Authentication check failed:', error);
      return {
        isAuthenticated: false,
        error: `Authentication check failed: ${error instanceof Error ? error.message : 'Unknown error'}`
      };
    }
  }

  /**
   * Create a new organization
   * @param input Organization creation data
   * @returns Observable<OrganizationsCreateResponse>
   */
  public createOrganization(input: Partial<OrganizationsCreateInput>): Observable<OrganizationsCreateResponse> {
    console.debug('[OrganizationService] Creating organization:', input);

    return from(this.checkAuthentication()).pipe(
      switchMap((authResult: AuthCheckResult) => {
        if (!authResult.isAuthenticated) {
          throw new Error(`Authentication required: ${authResult.error}`);
        }

        console.debug('[OrganizationService] User is authenticated, proceeding with organization creation');

        const timestamp = new Date();

        // Build the create input with required fields
        const createInput: OrganizationsCreateInput = {
          organizationId: input.organizationId || '', // Will be generated by backend
          name: input.name || '',
          description: input.description || '',
          ownerId: input.ownerId || '', // Will be set by backend from authenticated user
          status: input.status || OrganizationStatus.Pending,
          createdAt: timestamp,
          updatedAt: timestamp,
          kmsKeyId: input.kmsKeyId || '',
          kmsKeyArn: input.kmsKeyArn || '',
          kmsAlias: input.kmsAlias || ''
        };

        return from(
          this.mutate(
            OrganizationsMutation,
            { 
              input: {
                action: 'CREATE',
                data: createInput
              }
            },
            'userPool' // Use userPool auth for authenticated operations
          ) as Promise<GraphQLResult<OrganizationsCreateResponse>>
        );
      })
    ).pipe(
      map((response: GraphQLResult<{ Organizations?: { StatusCode?: number; Message?: string; Data?: Record<string, unknown> } }>) => {
        console.debug('[OrganizationService] Create organization response:', response);
        
        if (!response.data) {
          throw new Error('No data in create organization response');
        }

        const organizationsData = response.data.Organizations;
        return {
          StatusCode: organizationsData?.StatusCode ?? 200,
          Message: organizationsData?.Message ?? 'Organization created successfully',
          Data: organizationsData?.Data ? new Organizations(organizationsData.Data) : null
        } as OrganizationsCreateResponse;
      }),
      catchError((error) => {
        console.error('[OrganizationService] Error creating organization:', error);
        
        // Handle authentication errors
        if (error?.message?.includes('Not Authorized') || error?.message?.includes('Unauthorized')) {
          throw new Error('You are not authorized to create organizations. Please ensure you are signed in and have the necessary permissions.');
        }
        
        // Handle validation errors
        if (error?.message?.includes('validation')) {
          throw new Error('Invalid organization data. Please check your input and try again.');
        }
        
        // Generic error
        throw new Error('Failed to create organization. Please try again later.');
      })
    );
  }

  /**
   * Update an existing organization
   * @param input Organization update data
   * @returns Observable<OrganizationsUpdateResponse>
   */
  public updateOrganization(input: Partial<OrganizationsUpdateInput>): Observable<OrganizationsUpdateResponse> {
    console.debug('[OrganizationService] Updating organization:', input);

    if (!input.organizationId) {
      throw new Error('Organization ID is required for updates');
    }

    const updateInput: OrganizationsUpdateInput = {
      organizationId: input.organizationId,
      name: input.name || '',
      description: input.description || '',
      ownerId: input.ownerId || '',
      status: input.status || OrganizationStatus.Active,
      createdAt: input.createdAt || new Date(),
      updatedAt: new Date(), // Always update timestamp
      kmsKeyId: input.kmsKeyId || '',
      kmsKeyArn: input.kmsKeyArn || '',
      kmsAlias: input.kmsAlias || ''
    };

    return from(
      this.mutate(
        OrganizationsMutation,
        { 
          input: {
            action: 'UPDATE',
            data: updateInput
          }
        },
        'userPool' // Use userPool auth for authenticated operations
      ) as Promise<GraphQLResult<OrganizationsUpdateResponse>>
    ).pipe(
      map(response => {
        console.debug('[OrganizationService] Update organization response:', response);
        
        if (!response.data) {
          throw new Error('No data in update organization response');
        }

        return {
          StatusCode: response.data.StatusCode ?? 200,
          Message: response.data.Message ?? 'Organization updated successfully',
          Data: response.data.Data ? new Organizations(response.data.Data) : null
        } as OrganizationsUpdateResponse;
      }),
      catchError((error) => {
        console.error('[OrganizationService] Error updating organization:', error);
        
        if (error?.message?.includes('Not Authorized') || error?.message?.includes('Unauthorized')) {
          throw new Error('You are not authorized to update this organization.');
        }
        
        if (error?.message?.includes('not found')) {
          throw new Error('Organization not found. It may have been deleted.');
        }
        
        throw new Error('Failed to update organization. Please try again later.');
      })
    );
  }

  /**
   * Delete an organization
   * @param organizationId ID of organization to delete
   * @returns Observable<OrganizationsResponse>
   */
  public deleteOrganization(organizationId: string): Observable<OrganizationsResponse> {
    console.debug('[OrganizationService] Deleting organization:', organizationId);

    if (!organizationId) {
      throw new Error('Organization ID is required for deletion');
    }

    return from(
      this.mutate(
        OrganizationsMutation,
        { 
          input: {
            action: 'DELETE',
            data: {
              organizationId: organizationId
            }
          }
        },
        'userPool' // Use userPool auth for authenticated operations
      ) as Promise<GraphQLResult<OrganizationsResponse>>
    ).pipe(
      map(response => {
        console.debug('[OrganizationService] Delete organization response:', response);
        
        if (!response.data) {
          throw new Error('No data in delete organization response');
        }

        return {
          StatusCode: response.data.StatusCode ?? 200,
          Message: response.data.Message ?? 'Organization deleted successfully',
          Data: response.data.Data ? new Organizations(response.data.Data) : null
        } as OrganizationsResponse;
      }),
      catchError((error) => {
        console.error('[OrganizationService] Error deleting organization:', error);
        
        if (error?.message?.includes('Not Authorized') || error?.message?.includes('Unauthorized')) {
          throw new Error('You are not authorized to delete this organization.');
        }
        
        if (error?.message?.includes('not found')) {
          throw new Error('Organization not found. It may have already been deleted.');
        }
        
        throw new Error('Failed to delete organization. Please try again later.');
      })
    );
  }

  /**
   * Get organizations for the current user
   * @returns Observable<OrganizationsListResponse>
   */
  public getUserOrganizations(): Observable<OrganizationsListResponse> {
    console.debug('[OrganizationService] Getting user organizations');

    return from(
      this.mutate(
        OrganizationsMutation,
        { 
          input: {
            action: 'LIST_USER_ORGANIZATIONS'
          }
        },
        'userPool' // Use userPool auth for authenticated operations
      ) as Promise<GraphQLResult<OrganizationsListResponse>>
    ).pipe(
      map(response => {
        console.debug('[OrganizationService] Get user organizations response:', response);
        
        if (!response.data) {
          throw new Error('No data in get organizations response');
        }

        // Convert raw data to Organizations instances
        const organizations = (response.data.Data || []).map(org => new Organizations(org));

        return {
          StatusCode: response.data.StatusCode ?? 200,
          Message: response.data.Message ?? 'Organizations retrieved successfully',
          Data: organizations
        } as OrganizationsListResponse;
      }),
      catchError((error) => {
        console.error('[OrganizationService] Error getting organizations:', error);
        
        if (error?.message?.includes('Not Authorized') || error?.message?.includes('Unauthorized')) {
          throw new Error('You are not authorized to view organizations.');
        }
        
        throw new Error('Failed to retrieve organizations. Please try again later.');
      })
    );
  }

  /**
   * Get a specific organization by ID
   * @param organizationId ID of organization to retrieve
   * @returns Observable<OrganizationsResponse>
   */
  public getOrganization(organizationId: string): Observable<OrganizationsResponse> {
    console.debug('[OrganizationService] Getting organization:', organizationId);

    if (!organizationId) {
      throw new Error('Organization ID is required');
    }

    return from(
      this.mutate(
        OrganizationsMutation,
        { 
          input: {
            action: 'GET',
            data: {
              organizationId: organizationId
            }
          }
        },
        'userPool' // Use userPool auth for authenticated operations
      ) as Promise<GraphQLResult<OrganizationsResponse>>
    ).pipe(
      map(response => {
        console.debug('[OrganizationService] Get organization response:', response);
        
        if (!response.data) {
          throw new Error('No data in get organization response');
        }

        return {
          StatusCode: response.data.StatusCode ?? 200,
          Message: response.data.Message ?? 'Organization retrieved successfully',
          Data: response.data.Data ? new Organizations(response.data.Data) : null
        } as OrganizationsResponse;
      }),
      catchError((error) => {
        console.error('[OrganizationService] Error getting organization:', error);
        
        if (error?.message?.includes('Not Authorized') || error?.message?.includes('Unauthorized')) {
          throw new Error('You are not authorized to view this organization.');
        }
        
        if (error?.message?.includes('not found')) {
          throw new Error('Organization not found.');
        }
        
        throw new Error('Failed to retrieve organization. Please try again later.');
      })
    );
  }
}