// Generated TypeScript enum for LegalBasis
// Generated at 

export enum LegalBasis {
  GDPR_ARTICLE_15_RIGHT_OF_ACCESS = 'GDPR_ARTICLE_15_RIGHT_OF_ACCESS',  GDPR_ARTICLE_17_RIGHT_TO_ERASURE = 'GDPR_ARTICLE_17_RIGHT_TO_ERASURE',  GDPR_ARTICLE_20_DATA_PORTABILITY = 'GDPR_ARTICLE_20_DATA_PORTABILITY',  CCPA_RIGHT_TO_KNOW = 'CCPA_RIGHT_TO_KNOW',  CCPA_RIGHT_TO_DELETE = 'CCPA_RIGHT_TO_DELETE',  CCPA_RIGHT_TO_OPT_OUT = 'CCPA_RIGHT_TO_OPT_OUT'} 