// Generated TypeScript enum for PrivacyRequestType
// Generated at 

export enum PrivacyRequestType {

  DATA_ACCESS = 'DATA_ACCESS',

  DATA_DELETION = 'DATA_DELETION',

  DATA_PORTABILITY = 'DATA_PORTABILITY',

  DATA_RECTIFICATION = 'DATA_RECTIFICATION',

  PROCESSING_RESTRICTION = 'PROCESSING_RESTRICTION',

  MARKETING_OPT_OUT = 'MARKETING_OPT_OUT'

} 