// AUTO-GENERATED by orb-schema-generator v0.18.2 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * GraphQL operations for ApplicationUsers
 */

export const ApplicationUsersCreate = /* GraphQL */ `
  mutation ApplicationUsersCreate($input: ApplicationUsersCreateInput!) {
    ApplicationUsersCreate(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersUpdate = /* GraphQL */ `
  mutation ApplicationUsersUpdate($input: ApplicationUsersUpdateInput!) {
    ApplicationUsersUpdate(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersDelete = /* GraphQL */ `
  mutation ApplicationUsersDelete($input: ApplicationUsersDeleteInput!) {
    ApplicationUsersDelete(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersDisable = /* GraphQL */ `
  mutation ApplicationUsersDisable($input: ApplicationUsersDisableInput!) {
    ApplicationUsersDisable(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersQueryByApplicationUserId = /* GraphQL */ `
  query ApplicationUsersQueryByApplicationUserId($input: ApplicationUsersQueryByApplicationUserIdInput!) {
    ApplicationUsersQueryByApplicationUserId(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersQueryByUserId = /* GraphQL */ `
  query ApplicationUsersQueryByUserId($input: ApplicationUsersQueryByUserIdInput!) {
    ApplicationUsersQueryByUserId(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersQueryByUserIdAndApplicationId = /* GraphQL */ `
  query ApplicationUsersQueryByUserIdAndApplicationId($input: ApplicationUsersQueryByUserIdAndApplicationIdInput!) {
    ApplicationUsersQueryByUserIdAndApplicationId(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersQueryByApplicationId = /* GraphQL */ `
  query ApplicationUsersQueryByApplicationId($input: ApplicationUsersQueryByApplicationIdInput!) {
    ApplicationUsersQueryByApplicationId(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersQueryByApplicationIdAndUserId = /* GraphQL */ `
  query ApplicationUsersQueryByApplicationIdAndUserId($input: ApplicationUsersQueryByApplicationIdAndUserIdInput!) {
    ApplicationUsersQueryByApplicationIdAndUserId(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;
