// AUTO-GENERATED by orb-schema-generator v1.3.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * GraphQL operations for ApplicationUserRoles
 */

export const ApplicationUserRolesCreate = /* GraphQL */ `
  mutation ApplicationUserRolesCreate($input: ApplicationUserRolesCreateInput!) {
    ApplicationUserRolesCreate(input: $input) {
      code
      success
      message
      item {
        applicationUserRoleId
        userId
        applicationId
        organizationId
        organizationName
        applicationName
        environment
        roleId
        roleName
        status
        createdAt
        updatedAt
      }
    }
  }
`;

export const ApplicationUserRolesUpdate = /* GraphQL */ `
  mutation ApplicationUserRolesUpdate($input: ApplicationUserRolesUpdateInput!) {
    ApplicationUserRolesUpdate(input: $input) {
      code
      success
      message
      item {
        applicationUserRoleId
        userId
        applicationId
        organizationId
        organizationName
        applicationName
        environment
        roleId
        roleName
        status
        createdAt
        updatedAt
      }
    }
  }
`;

export const ApplicationUserRolesDelete = /* GraphQL */ `
  mutation ApplicationUserRolesDelete($input: ApplicationUserRolesDeleteInput!) {
    ApplicationUserRolesDelete(input: $input) {
      code
      success
      message
      item {
        applicationUserRoleId
        userId
        applicationId
        organizationId
        organizationName
        applicationName
        environment
        roleId
        roleName
        status
        createdAt
        updatedAt
      }
    }
  }
`;

export const ApplicationUserRolesDisable = /* GraphQL */ `
  mutation ApplicationUserRolesDisable($input: ApplicationUserRolesDisableInput!) {
    ApplicationUserRolesDisable(input: $input) {
      code
      success
      message
      item {
        applicationUserRoleId
        userId
        applicationId
        organizationId
        organizationName
        applicationName
        environment
        roleId
        roleName
        status
        createdAt
        updatedAt
      }
    }
  }
`;

export const ApplicationUserRolesGet = /* GraphQL */ `
  query ApplicationUserRolesGet($input: ApplicationUserRolesGetInput!) {
    ApplicationUserRolesGet(input: $input) {
      code
      success
      message
      item {
        applicationUserRoleId
        userId
        applicationId
        organizationId
        organizationName
        applicationName
        environment
        roleId
        roleName
        status
        createdAt
        updatedAt
      }
    }
  }
`;

export const ApplicationUserRolesListByApplicationUserRoleId = /* GraphQL */ `
  query ApplicationUserRolesListByApplicationUserRoleId($input: ApplicationUserRolesListByApplicationUserRoleIdInput!) {
    ApplicationUserRolesListByApplicationUserRoleId(input: $input) {
      code
      success
      message
      items {
        applicationUserRoleId
        userId
        applicationId
        organizationId
        organizationName
        applicationName
        environment
        roleId
        roleName
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUserRolesListByUserId = /* GraphQL */ `
  query ApplicationUserRolesListByUserId($input: ApplicationUserRolesListByUserIdInput!) {
    ApplicationUserRolesListByUserId(input: $input) {
      code
      success
      message
      items {
        applicationUserRoleId
        userId
        applicationId
        organizationId
        organizationName
        applicationName
        environment
        roleId
        roleName
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUserRolesListByUserIdAndEnvironment = /* GraphQL */ `
  query ApplicationUserRolesListByUserIdAndEnvironment($input: ApplicationUserRolesListByUserIdAndEnvironmentInput!) {
    ApplicationUserRolesListByUserIdAndEnvironment(input: $input) {
      code
      success
      message
      items {
        applicationUserRoleId
        userId
        applicationId
        organizationId
        organizationName
        applicationName
        environment
        roleId
        roleName
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUserRolesListByApplicationId = /* GraphQL */ `
  query ApplicationUserRolesListByApplicationId($input: ApplicationUserRolesListByApplicationIdInput!) {
    ApplicationUserRolesListByApplicationId(input: $input) {
      code
      success
      message
      items {
        applicationUserRoleId
        userId
        applicationId
        organizationId
        organizationName
        applicationName
        environment
        roleId
        roleName
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUserRolesListByApplicationIdAndEnvironment = /* GraphQL */ `
  query ApplicationUserRolesListByApplicationIdAndEnvironment($input: ApplicationUserRolesListByApplicationIdAndEnvironmentInput!) {
    ApplicationUserRolesListByApplicationIdAndEnvironment(input: $input) {
      code
      success
      message
      items {
        applicationUserRoleId
        userId
        applicationId
        organizationId
        organizationName
        applicationName
        environment
        roleId
        roleName
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUserRolesListByUserIdAndApplicationId = /* GraphQL */ `
  query ApplicationUserRolesListByUserIdAndApplicationId($input: ApplicationUserRolesListByUserIdAndApplicationIdInput!) {
    ApplicationUserRolesListByUserIdAndApplicationId(input: $input) {
      code
      success
      message
      items {
        applicationUserRoleId
        userId
        applicationId
        organizationId
        organizationName
        applicationName
        environment
        roleId
        roleName
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUserRolesListByUserIdAndStatus = /* GraphQL */ `
  query ApplicationUserRolesListByUserIdAndStatus($input: ApplicationUserRolesListByUserIdAndStatusInput!) {
    ApplicationUserRolesListByUserIdAndStatus(input: $input) {
      code
      success
      message
      items {
        applicationUserRoleId
        userId
        applicationId
        organizationId
        organizationName
        applicationName
        environment
        roleId
        roleName
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;
