// AUTO-GENERATED by orb-schema-generator v0.19.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * GraphQL operations for Applications
 */

export const ApplicationsCreate = /* GraphQL */ `
  mutation ApplicationsCreate($input: ApplicationsCreateInput!) {
    ApplicationsCreate(input: $input) {
      items {
        applicationId
        name
        organizationId
        ownerId
        status
        createdAt
        updatedAt
        apiKey
        apiKeyNext
        environments
      }
      nextToken
    }
  }
`;

export const ApplicationsUpdate = /* GraphQL */ `
  mutation ApplicationsUpdate($input: ApplicationsUpdateInput!) {
    ApplicationsUpdate(input: $input) {
      items {
        applicationId
        name
        organizationId
        ownerId
        status
        createdAt
        updatedAt
        apiKey
        apiKeyNext
        environments
      }
      nextToken
    }
  }
`;

export const ApplicationsDelete = /* GraphQL */ `
  mutation ApplicationsDelete($input: ApplicationsDeleteInput!) {
    ApplicationsDelete(input: $input) {
      items {
        applicationId
        name
        organizationId
        ownerId
        status
        createdAt
        updatedAt
        apiKey
        apiKeyNext
        environments
      }
      nextToken
    }
  }
`;

export const ApplicationsDisable = /* GraphQL */ `
  mutation ApplicationsDisable($input: ApplicationsDisableInput!) {
    ApplicationsDisable(input: $input) {
      items {
        applicationId
        name
        organizationId
        ownerId
        status
        createdAt
        updatedAt
        apiKey
        apiKeyNext
        environments
      }
      nextToken
    }
  }
`;

export const ApplicationsGet = /* GraphQL */ `
  query ApplicationsGet($input: ApplicationsGetInput!) {
    ApplicationsGet(input: $input) {
      items {
        applicationId
        name
        organizationId
        ownerId
        status
        createdAt
        updatedAt
        apiKey
        apiKeyNext
        environments
      }
      nextToken
    }
  }
`;

export const ApplicationsListByApplicationId = /* GraphQL */ `
  query ApplicationsListByApplicationId($input: ApplicationsListByApplicationIdInput!) {
    ApplicationsListByApplicationId(input: $input) {
      items {
        applicationId
        name
        organizationId
        ownerId
        status
        createdAt
        updatedAt
        apiKey
        apiKeyNext
        environments
      }
      nextToken
    }
  }
`;

export const ApplicationsListByOrganizationId = /* GraphQL */ `
  query ApplicationsListByOrganizationId($input: ApplicationsListByOrganizationIdInput!) {
    ApplicationsListByOrganizationId(input: $input) {
      items {
        applicationId
        name
        organizationId
        ownerId
        status
        createdAt
        updatedAt
        apiKey
        apiKeyNext
        environments
      }
      nextToken
    }
  }
`;

export const ApplicationsListByOrganizationIdAndCreatedAt = /* GraphQL */ `
  query ApplicationsListByOrganizationIdAndCreatedAt($input: ApplicationsListByOrganizationIdAndCreatedAtInput!) {
    ApplicationsListByOrganizationIdAndCreatedAt(input: $input) {
      items {
        applicationId
        name
        organizationId
        ownerId
        status
        createdAt
        updatedAt
        apiKey
        apiKeyNext
        environments
      }
      nextToken
    }
  }
`;
