// AUTO-GENERATED by orb-schema-generator v1.3.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * GraphQL operations for ApplicationEnvironmentConfig
 */

export const ApplicationEnvironmentConfigCreate = /* GraphQL */ `
  mutation ApplicationEnvironmentConfigCreate($input: ApplicationEnvironmentConfigCreateInput!) {
    ApplicationEnvironmentConfigCreate(input: $input) {
      code
      success
      message
      item {
        applicationId
        environment
        organizationId
        allowedOrigins
        rateLimitPerMinute
        rateLimitPerDay
        webhookUrl
        webhookSecret
        webhookEvents
        webhookEnabled
        webhookMaxRetries
        webhookRetryDelaySeconds
        featureFlags
        metadata
        createdAt
        updatedAt
      }
    }
  }
`;

export const ApplicationEnvironmentConfigUpdate = /* GraphQL */ `
  mutation ApplicationEnvironmentConfigUpdate($input: ApplicationEnvironmentConfigUpdateInput!) {
    ApplicationEnvironmentConfigUpdate(input: $input) {
      code
      success
      message
      item {
        applicationId
        environment
        organizationId
        allowedOrigins
        rateLimitPerMinute
        rateLimitPerDay
        webhookUrl
        webhookSecret
        webhookEvents
        webhookEnabled
        webhookMaxRetries
        webhookRetryDelaySeconds
        featureFlags
        metadata
        createdAt
        updatedAt
      }
    }
  }
`;

export const ApplicationEnvironmentConfigDelete = /* GraphQL */ `
  mutation ApplicationEnvironmentConfigDelete($input: ApplicationEnvironmentConfigDeleteInput!) {
    ApplicationEnvironmentConfigDelete(input: $input) {
      code
      success
      message
      item {
        applicationId
        environment
        organizationId
        allowedOrigins
        rateLimitPerMinute
        rateLimitPerDay
        webhookUrl
        webhookSecret
        webhookEvents
        webhookEnabled
        webhookMaxRetries
        webhookRetryDelaySeconds
        featureFlags
        metadata
        createdAt
        updatedAt
      }
    }
  }
`;

export const ApplicationEnvironmentConfigDisable = /* GraphQL */ `
  mutation ApplicationEnvironmentConfigDisable($input: ApplicationEnvironmentConfigDisableInput!) {
    ApplicationEnvironmentConfigDisable(input: $input) {
      code
      success
      message
      item {
        applicationId
        environment
        organizationId
        allowedOrigins
        rateLimitPerMinute
        rateLimitPerDay
        webhookUrl
        webhookSecret
        webhookEvents
        webhookEnabled
        webhookMaxRetries
        webhookRetryDelaySeconds
        featureFlags
        metadata
        createdAt
        updatedAt
      }
    }
  }
`;

export const ApplicationEnvironmentConfigGet = /* GraphQL */ `
  query ApplicationEnvironmentConfigGet($input: ApplicationEnvironmentConfigGetInput!) {
    ApplicationEnvironmentConfigGet(input: $input) {
      code
      success
      message
      item {
        applicationId
        environment
        organizationId
        allowedOrigins
        rateLimitPerMinute
        rateLimitPerDay
        webhookUrl
        webhookSecret
        webhookEvents
        webhookEnabled
        webhookMaxRetries
        webhookRetryDelaySeconds
        featureFlags
        metadata
        createdAt
        updatedAt
      }
    }
  }
`;

export const ApplicationEnvironmentConfigListByApplicationId = /* GraphQL */ `
  query ApplicationEnvironmentConfigListByApplicationId($input: ApplicationEnvironmentConfigListByApplicationIdInput!) {
    ApplicationEnvironmentConfigListByApplicationId(input: $input) {
      code
      success
      message
      items {
        applicationId
        environment
        organizationId
        allowedOrigins
        rateLimitPerMinute
        rateLimitPerDay
        webhookUrl
        webhookSecret
        webhookEvents
        webhookEnabled
        webhookMaxRetries
        webhookRetryDelaySeconds
        featureFlags
        metadata
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationEnvironmentConfigListByEnvironment = /* GraphQL */ `
  query ApplicationEnvironmentConfigListByEnvironment($input: ApplicationEnvironmentConfigListByEnvironmentInput!) {
    ApplicationEnvironmentConfigListByEnvironment(input: $input) {
      code
      success
      message
      items {
        applicationId
        environment
        organizationId
        allowedOrigins
        rateLimitPerMinute
        rateLimitPerDay
        webhookUrl
        webhookSecret
        webhookEvents
        webhookEnabled
        webhookMaxRetries
        webhookRetryDelaySeconds
        featureFlags
        metadata
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationEnvironmentConfigListByApplicationIdAndEnvironment = /* GraphQL */ `
  query ApplicationEnvironmentConfigListByApplicationIdAndEnvironment($input: ApplicationEnvironmentConfigListByApplicationIdAndEnvironmentInput!) {
    ApplicationEnvironmentConfigListByApplicationIdAndEnvironment(input: $input) {
      code
      success
      message
      items {
        applicationId
        environment
        organizationId
        allowedOrigins
        rateLimitPerMinute
        rateLimitPerDay
        webhookUrl
        webhookSecret
        webhookEvents
        webhookEnabled
        webhookMaxRetries
        webhookRetryDelaySeconds
        featureFlags
        metadata
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationEnvironmentConfigListByOrganizationId = /* GraphQL */ `
  query ApplicationEnvironmentConfigListByOrganizationId($input: ApplicationEnvironmentConfigListByOrganizationIdInput!) {
    ApplicationEnvironmentConfigListByOrganizationId(input: $input) {
      code
      success
      message
      items {
        applicationId
        environment
        organizationId
        allowedOrigins
        rateLimitPerMinute
        rateLimitPerDay
        webhookUrl
        webhookSecret
        webhookEvents
        webhookEnabled
        webhookMaxRetries
        webhookRetryDelaySeconds
        featureFlags
        metadata
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationEnvironmentConfigListByOrganizationIdAndEnvironment = /* GraphQL */ `
  query ApplicationEnvironmentConfigListByOrganizationIdAndEnvironment($input: ApplicationEnvironmentConfigListByOrganizationIdAndEnvironmentInput!) {
    ApplicationEnvironmentConfigListByOrganizationIdAndEnvironment(input: $input) {
      code
      success
      message
      items {
        applicationId
        environment
        organizationId
        allowedOrigins
        rateLimitPerMinute
        rateLimitPerDay
        webhookUrl
        webhookSecret
        webhookEvents
        webhookEnabled
        webhookMaxRetries
        webhookRetryDelaySeconds
        featureFlags
        metadata
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;
