// AUTO-GENERATED by orb-schema-generator v0.16.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * GraphQL operations for Applications
 */

export const ApplicationsCreate = /* GraphQL */ `
  mutation ApplicationsCreate($input: ApplicationsCreateInput!) {
    ApplicationsCreate(input: $input) {
      items {
        applicationId
        name
        organizationId
        ownerId
        status
        createdAt
        updatedAt
        apiKey
        apiKeyNext
        environments
      }
      nextToken
    }
  }
`;

export const ApplicationsUpdate = /* GraphQL */ `
  mutation ApplicationsUpdate($input: ApplicationsUpdateInput!) {
    ApplicationsUpdate(input: $input) {
      items {
        applicationId
        name
        organizationId
        ownerId
        status
        createdAt
        updatedAt
        apiKey
        apiKeyNext
        environments
      }
      nextToken
    }
  }
`;

export const ApplicationsDelete = /* GraphQL */ `
  mutation ApplicationsDelete($input: ApplicationsDeleteInput!) {
    ApplicationsDelete(input: $input) {
      items {
        applicationId
        name
        organizationId
        ownerId
        status
        createdAt
        updatedAt
        apiKey
        apiKeyNext
        environments
      }
      nextToken
    }
  }
`;

export const ApplicationsDisable = /* GraphQL */ `
  mutation ApplicationsDisable($input: ApplicationsDisableInput!) {
    ApplicationsDisable(input: $input) {
      items {
        applicationId
        name
        organizationId
        ownerId
        status
        createdAt
        updatedAt
        apiKey
        apiKeyNext
        environments
      }
      nextToken
    }
  }
`;

export const ApplicationsQueryByApplicationId = /* GraphQL */ `
  query ApplicationsQueryByApplicationId($input: ApplicationsQueryByApplicationIdInput!) {
    ApplicationsQueryByApplicationId(input: $input) {
      items {
        applicationId
        name
        organizationId
        ownerId
        status
        createdAt
        updatedAt
        apiKey
        apiKeyNext
        environments
      }
      nextToken
    }
  }
`;

export const ApplicationsQueryByOrganizationId = /* GraphQL */ `
  query ApplicationsQueryByOrganizationId($input: ApplicationsQueryByOrganizationIdInput!) {
    ApplicationsQueryByOrganizationId(input: $input) {
      items {
        applicationId
        name
        organizationId
        ownerId
        status
        createdAt
        updatedAt
        apiKey
        apiKeyNext
        environments
      }
      nextToken
    }
  }
`;

export const ApplicationsQueryByOrganizationIdAndCreatedAt = /* GraphQL */ `
  query ApplicationsQueryByOrganizationIdAndCreatedAt($input: ApplicationsQueryByOrganizationIdAndCreatedAtInput!) {
    ApplicationsQueryByOrganizationIdAndCreatedAt(input: $input) {
      items {
        applicationId
        name
        organizationId
        ownerId
        status
        createdAt
        updatedAt
        apiKey
        apiKeyNext
        environments
      }
      nextToken
    }
  }
`;
