// AUTO-GENERATED by orb-schema-generator v0.19.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * GraphQL operations for ApplicationRoles
 */

export const ApplicationRolesCreate = /* GraphQL */ `
  mutation ApplicationRolesCreate($input: ApplicationRolesCreateInput!) {
    ApplicationRolesCreate(input: $input) {
      items {
        applicationRoleId
        userId
        applicationId
        roleId
        roleName
        roleType
        permissions
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationRolesUpdate = /* GraphQL */ `
  mutation ApplicationRolesUpdate($input: ApplicationRolesUpdateInput!) {
    ApplicationRolesUpdate(input: $input) {
      items {
        applicationRoleId
        userId
        applicationId
        roleId
        roleName
        roleType
        permissions
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationRolesDelete = /* GraphQL */ `
  mutation ApplicationRolesDelete($input: ApplicationRolesDeleteInput!) {
    ApplicationRolesDelete(input: $input) {
      items {
        applicationRoleId
        userId
        applicationId
        roleId
        roleName
        roleType
        permissions
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationRolesDisable = /* GraphQL */ `
  mutation ApplicationRolesDisable($input: ApplicationRolesDisableInput!) {
    ApplicationRolesDisable(input: $input) {
      items {
        applicationRoleId
        userId
        applicationId
        roleId
        roleName
        roleType
        permissions
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationRolesGet = /* GraphQL */ `
  query ApplicationRolesGet($input: ApplicationRolesGetInput!) {
    ApplicationRolesGet(input: $input) {
      items {
        applicationRoleId
        userId
        applicationId
        roleId
        roleName
        roleType
        permissions
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationRolesListByApplicationRoleId = /* GraphQL */ `
  query ApplicationRolesListByApplicationRoleId($input: ApplicationRolesListByApplicationRoleIdInput!) {
    ApplicationRolesListByApplicationRoleId(input: $input) {
      items {
        applicationRoleId
        userId
        applicationId
        roleId
        roleName
        roleType
        permissions
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationRolesListByUserId = /* GraphQL */ `
  query ApplicationRolesListByUserId($input: ApplicationRolesListByUserIdInput!) {
    ApplicationRolesListByUserId(input: $input) {
      items {
        applicationRoleId
        userId
        applicationId
        roleId
        roleName
        roleType
        permissions
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationRolesListByUserIdAndRoleId = /* GraphQL */ `
  query ApplicationRolesListByUserIdAndRoleId($input: ApplicationRolesListByUserIdAndRoleIdInput!) {
    ApplicationRolesListByUserIdAndRoleId(input: $input) {
      items {
        applicationRoleId
        userId
        applicationId
        roleId
        roleName
        roleType
        permissions
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationRolesListByApplicationId = /* GraphQL */ `
  query ApplicationRolesListByApplicationId($input: ApplicationRolesListByApplicationIdInput!) {
    ApplicationRolesListByApplicationId(input: $input) {
      items {
        applicationRoleId
        userId
        applicationId
        roleId
        roleName
        roleType
        permissions
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationRolesListByApplicationIdAndRoleId = /* GraphQL */ `
  query ApplicationRolesListByApplicationIdAndRoleId($input: ApplicationRolesListByApplicationIdAndRoleIdInput!) {
    ApplicationRolesListByApplicationIdAndRoleId(input: $input) {
      items {
        applicationRoleId
        userId
        applicationId
        roleId
        roleName
        roleType
        permissions
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationRolesListByRoleId = /* GraphQL */ `
  query ApplicationRolesListByRoleId($input: ApplicationRolesListByRoleIdInput!) {
    ApplicationRolesListByRoleId(input: $input) {
      items {
        applicationRoleId
        userId
        applicationId
        roleId
        roleName
        roleType
        permissions
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationRolesListByRoleIdAndRoleType = /* GraphQL */ `
  query ApplicationRolesListByRoleIdAndRoleType($input: ApplicationRolesListByRoleIdAndRoleTypeInput!) {
    ApplicationRolesListByRoleIdAndRoleType(input: $input) {
      items {
        applicationRoleId
        userId
        applicationId
        roleId
        roleName
        roleType
        permissions
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;
