// AUTO-GENERATED by orb-schema-generator v0.19.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * GraphQL operations for ApplicationUsers
 */

export const ApplicationUsersCreate = /* GraphQL */ `
  mutation ApplicationUsersCreate($input: ApplicationUsersCreateInput!) {
    ApplicationUsersCreate(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersUpdate = /* GraphQL */ `
  mutation ApplicationUsersUpdate($input: ApplicationUsersUpdateInput!) {
    ApplicationUsersUpdate(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersDelete = /* GraphQL */ `
  mutation ApplicationUsersDelete($input: ApplicationUsersDeleteInput!) {
    ApplicationUsersDelete(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersDisable = /* GraphQL */ `
  mutation ApplicationUsersDisable($input: ApplicationUsersDisableInput!) {
    ApplicationUsersDisable(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersGet = /* GraphQL */ `
  query ApplicationUsersGet($input: ApplicationUsersGetInput!) {
    ApplicationUsersGet(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersListByApplicationUserId = /* GraphQL */ `
  query ApplicationUsersListByApplicationUserId($input: ApplicationUsersListByApplicationUserIdInput!) {
    ApplicationUsersListByApplicationUserId(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersListByUserId = /* GraphQL */ `
  query ApplicationUsersListByUserId($input: ApplicationUsersListByUserIdInput!) {
    ApplicationUsersListByUserId(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersListByUserIdAndApplicationId = /* GraphQL */ `
  query ApplicationUsersListByUserIdAndApplicationId($input: ApplicationUsersListByUserIdAndApplicationIdInput!) {
    ApplicationUsersListByUserIdAndApplicationId(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersListByApplicationId = /* GraphQL */ `
  query ApplicationUsersListByApplicationId($input: ApplicationUsersListByApplicationIdInput!) {
    ApplicationUsersListByApplicationId(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const ApplicationUsersListByApplicationIdAndUserId = /* GraphQL */ `
  query ApplicationUsersListByApplicationIdAndUserId($input: ApplicationUsersListByApplicationIdAndUserIdInput!) {
    ApplicationUsersListByApplicationIdAndUserId(input: $input) {
      items {
        applicationUserId
        userId
        applicationId
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;
