// AUTO-GENERATED by orb-schema-generator v1.3.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * GraphQL operations for Notifications
 */

export const NotificationsCreate = /* GraphQL */ `
  mutation NotificationsCreate($input: NotificationsCreateInput!) {
    NotificationsCreate(input: $input) {
      code
      success
      message
      item {
        notificationId
        recipientUserId
        senderUserId
        type
        status
        title
        message
        metadata
        expiresAt
        createdAt
        updatedAt
      }
    }
  }
`;

export const NotificationsUpdate = /* GraphQL */ `
  mutation NotificationsUpdate($input: NotificationsUpdateInput!) {
    NotificationsUpdate(input: $input) {
      code
      success
      message
      item {
        notificationId
        recipientUserId
        senderUserId
        type
        status
        title
        message
        metadata
        expiresAt
        createdAt
        updatedAt
      }
    }
  }
`;

export const NotificationsDelete = /* GraphQL */ `
  mutation NotificationsDelete($input: NotificationsDeleteInput!) {
    NotificationsDelete(input: $input) {
      code
      success
      message
      item {
        notificationId
        recipientUserId
        senderUserId
        type
        status
        title
        message
        metadata
        expiresAt
        createdAt
        updatedAt
      }
    }
  }
`;

export const NotificationsDisable = /* GraphQL */ `
  mutation NotificationsDisable($input: NotificationsDisableInput!) {
    NotificationsDisable(input: $input) {
      code
      success
      message
      item {
        notificationId
        recipientUserId
        senderUserId
        type
        status
        title
        message
        metadata
        expiresAt
        createdAt
        updatedAt
      }
    }
  }
`;

export const NotificationsGet = /* GraphQL */ `
  query NotificationsGet($input: NotificationsGetInput!) {
    NotificationsGet(input: $input) {
      code
      success
      message
      item {
        notificationId
        recipientUserId
        senderUserId
        type
        status
        title
        message
        metadata
        expiresAt
        createdAt
        updatedAt
      }
    }
  }
`;

export const NotificationsListByNotificationId = /* GraphQL */ `
  query NotificationsListByNotificationId($input: NotificationsListByNotificationIdInput!) {
    NotificationsListByNotificationId(input: $input) {
      code
      success
      message
      items {
        notificationId
        recipientUserId
        senderUserId
        type
        status
        title
        message
        metadata
        expiresAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const NotificationsListByRecipientUserId = /* GraphQL */ `
  query NotificationsListByRecipientUserId($input: NotificationsListByRecipientUserIdInput!) {
    NotificationsListByRecipientUserId(input: $input) {
      code
      success
      message
      items {
        notificationId
        recipientUserId
        senderUserId
        type
        status
        title
        message
        metadata
        expiresAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const NotificationsListByRecipientUserIdAndCreatedAt = /* GraphQL */ `
  query NotificationsListByRecipientUserIdAndCreatedAt($input: NotificationsListByRecipientUserIdAndCreatedAtInput!) {
    NotificationsListByRecipientUserIdAndCreatedAt(input: $input) {
      code
      success
      message
      items {
        notificationId
        recipientUserId
        senderUserId
        type
        status
        title
        message
        metadata
        expiresAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const NotificationsListByType = /* GraphQL */ `
  query NotificationsListByType($input: NotificationsListByTypeInput!) {
    NotificationsListByType(input: $input) {
      code
      success
      message
      items {
        notificationId
        recipientUserId
        senderUserId
        type
        status
        title
        message
        metadata
        expiresAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const NotificationsListByTypeAndStatus = /* GraphQL */ `
  query NotificationsListByTypeAndStatus($input: NotificationsListByTypeAndStatusInput!) {
    NotificationsListByTypeAndStatus(input: $input) {
      code
      success
      message
      items {
        notificationId
        recipientUserId
        senderUserId
        type
        status
        title
        message
        metadata
        expiresAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;
