// Auto-generated GraphQL operations for Organizations (Lambda)
// Do not edit manually. Generated by generate.py

export const OrganizationsMutation = /* GraphQL */ `
mutation Organizations($input: OrganizationsInput!) {
  Organizations(input: $input) {
    StatusCode
    Message
    Data {
      organizationId
      name
      description
      ownerId
      status
      createdAt
      updatedAt
      kmsKeyId
      kmsKeyArn
      kmsAlias
    }
  }
}
`;