// AUTO-GENERATED by orb-schema-generator v2.0.3 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * GraphQL operations for OrganizationUsers
 */

export const OrganizationUsersCreate = /* GraphQL */ `
  mutation OrganizationUsersCreate($input: OrganizationUsersCreateInput!) {
    OrganizationUsersCreate(input: $input) {
      code
      success
      message
      item {
        userId
        organizationId
        role
        status
        invitedBy
        invitedAt
        joinedAt
        createdAt
        updatedAt
      }
    }
  }
`;

export const OrganizationUsersUpdate = /* GraphQL */ `
  mutation OrganizationUsersUpdate($input: OrganizationUsersUpdateInput!) {
    OrganizationUsersUpdate(input: $input) {
      code
      success
      message
      item {
        userId
        organizationId
        role
        status
        invitedBy
        invitedAt
        joinedAt
        createdAt
        updatedAt
      }
    }
  }
`;

export const OrganizationUsersDelete = /* GraphQL */ `
  mutation OrganizationUsersDelete($input: OrganizationUsersDeleteInput!) {
    OrganizationUsersDelete(input: $input) {
      code
      success
      message
      item {
        userId
        organizationId
        role
        status
        invitedBy
        invitedAt
        joinedAt
        createdAt
        updatedAt
      }
    }
  }
`;

export const OrganizationUsersDisable = /* GraphQL */ `
  mutation OrganizationUsersDisable($input: OrganizationUsersDisableInput!) {
    OrganizationUsersDisable(input: $input) {
      code
      success
      message
      item {
        userId
        organizationId
        role
        status
        invitedBy
        invitedAt
        joinedAt
        createdAt
        updatedAt
      }
    }
  }
`;

export const OrganizationUsersGet = /* GraphQL */ `
  query OrganizationUsersGet($input: OrganizationUsersGetInput!) {
    OrganizationUsersGet(input: $input) {
      code
      success
      message
      item {
        userId
        organizationId
        role
        status
        invitedBy
        invitedAt
        joinedAt
        createdAt
        updatedAt
      }
    }
  }
`;

export const OrganizationUsersListByUserId = /* GraphQL */ `
  query OrganizationUsersListByUserId($input: OrganizationUsersListByUserIdInput!) {
    OrganizationUsersListByUserId(input: $input) {
      code
      success
      message
      items {
        userId
        organizationId
        role
        status
        invitedBy
        invitedAt
        joinedAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OrganizationUsersListByOrganizationId = /* GraphQL */ `
  query OrganizationUsersListByOrganizationId($input: OrganizationUsersListByOrganizationIdInput!) {
    OrganizationUsersListByOrganizationId(input: $input) {
      code
      success
      message
      items {
        userId
        organizationId
        role
        status
        invitedBy
        invitedAt
        joinedAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OrganizationUsersListByUserIdAndOrganizationId = /* GraphQL */ `
  query OrganizationUsersListByUserIdAndOrganizationId($input: OrganizationUsersListByUserIdAndOrganizationIdInput!) {
    OrganizationUsersListByUserIdAndOrganizationId(input: $input) {
      code
      success
      message
      items {
        userId
        organizationId
        role
        status
        invitedBy
        invitedAt
        joinedAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OrganizationUsersListByOrganizationIdAndRole = /* GraphQL */ `
  query OrganizationUsersListByOrganizationIdAndRole($input: OrganizationUsersListByOrganizationIdAndRoleInput!) {
    OrganizationUsersListByOrganizationIdAndRole(input: $input) {
      code
      success
      message
      items {
        userId
        organizationId
        role
        status
        invitedBy
        invitedAt
        joinedAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OrganizationUsersListByUserIdAndRole = /* GraphQL */ `
  query OrganizationUsersListByUserIdAndRole($input: OrganizationUsersListByUserIdAndRoleInput!) {
    OrganizationUsersListByUserIdAndRole(input: $input) {
      code
      success
      message
      items {
        userId
        organizationId
        role
        status
        invitedBy
        invitedAt
        joinedAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;
