// AUTO-GENERATED by orb-schema-generator v0.19.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * GraphQL operations for OwnershipTransferRequests
 */

export const OwnershipTransferRequestsCreate = /* GraphQL */ `
  mutation OwnershipTransferRequestsCreate($input: OwnershipTransferRequestsCreateInput!) {
    OwnershipTransferRequestsCreate(input: $input) {
      items {
        transferId
        organizationId
        currentOwnerId
        newOwnerId
        status
        reason
        expiresAt
        completedAt
        cancelledAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OwnershipTransferRequestsUpdate = /* GraphQL */ `
  mutation OwnershipTransferRequestsUpdate($input: OwnershipTransferRequestsUpdateInput!) {
    OwnershipTransferRequestsUpdate(input: $input) {
      items {
        transferId
        organizationId
        currentOwnerId
        newOwnerId
        status
        reason
        expiresAt
        completedAt
        cancelledAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OwnershipTransferRequestsDelete = /* GraphQL */ `
  mutation OwnershipTransferRequestsDelete($input: OwnershipTransferRequestsDeleteInput!) {
    OwnershipTransferRequestsDelete(input: $input) {
      items {
        transferId
        organizationId
        currentOwnerId
        newOwnerId
        status
        reason
        expiresAt
        completedAt
        cancelledAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OwnershipTransferRequestsDisable = /* GraphQL */ `
  mutation OwnershipTransferRequestsDisable($input: OwnershipTransferRequestsDisableInput!) {
    OwnershipTransferRequestsDisable(input: $input) {
      items {
        transferId
        organizationId
        currentOwnerId
        newOwnerId
        status
        reason
        expiresAt
        completedAt
        cancelledAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OwnershipTransferRequestsGet = /* GraphQL */ `
  query OwnershipTransferRequestsGet($input: OwnershipTransferRequestsGetInput!) {
    OwnershipTransferRequestsGet(input: $input) {
      items {
        transferId
        organizationId
        currentOwnerId
        newOwnerId
        status
        reason
        expiresAt
        completedAt
        cancelledAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OwnershipTransferRequestsListByTransferId = /* GraphQL */ `
  query OwnershipTransferRequestsListByTransferId($input: OwnershipTransferRequestsListByTransferIdInput!) {
    OwnershipTransferRequestsListByTransferId(input: $input) {
      items {
        transferId
        organizationId
        currentOwnerId
        newOwnerId
        status
        reason
        expiresAt
        completedAt
        cancelledAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OwnershipTransferRequestsListByCurrentOwnerId = /* GraphQL */ `
  query OwnershipTransferRequestsListByCurrentOwnerId($input: OwnershipTransferRequestsListByCurrentOwnerIdInput!) {
    OwnershipTransferRequestsListByCurrentOwnerId(input: $input) {
      items {
        transferId
        organizationId
        currentOwnerId
        newOwnerId
        status
        reason
        expiresAt
        completedAt
        cancelledAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OwnershipTransferRequestsListByCurrentOwnerIdAndCreatedAt = /* GraphQL */ `
  query OwnershipTransferRequestsListByCurrentOwnerIdAndCreatedAt($input: OwnershipTransferRequestsListByCurrentOwnerIdAndCreatedAtInput!) {
    OwnershipTransferRequestsListByCurrentOwnerIdAndCreatedAt(input: $input) {
      items {
        transferId
        organizationId
        currentOwnerId
        newOwnerId
        status
        reason
        expiresAt
        completedAt
        cancelledAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OwnershipTransferRequestsListByNewOwnerId = /* GraphQL */ `
  query OwnershipTransferRequestsListByNewOwnerId($input: OwnershipTransferRequestsListByNewOwnerIdInput!) {
    OwnershipTransferRequestsListByNewOwnerId(input: $input) {
      items {
        transferId
        organizationId
        currentOwnerId
        newOwnerId
        status
        reason
        expiresAt
        completedAt
        cancelledAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OwnershipTransferRequestsListByNewOwnerIdAndCreatedAt = /* GraphQL */ `
  query OwnershipTransferRequestsListByNewOwnerIdAndCreatedAt($input: OwnershipTransferRequestsListByNewOwnerIdAndCreatedAtInput!) {
    OwnershipTransferRequestsListByNewOwnerIdAndCreatedAt(input: $input) {
      items {
        transferId
        organizationId
        currentOwnerId
        newOwnerId
        status
        reason
        expiresAt
        completedAt
        cancelledAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OwnershipTransferRequestsListByStatus = /* GraphQL */ `
  query OwnershipTransferRequestsListByStatus($input: OwnershipTransferRequestsListByStatusInput!) {
    OwnershipTransferRequestsListByStatus(input: $input) {
      items {
        transferId
        organizationId
        currentOwnerId
        newOwnerId
        status
        reason
        expiresAt
        completedAt
        cancelledAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OwnershipTransferRequestsListByStatusAndCreatedAt = /* GraphQL */ `
  query OwnershipTransferRequestsListByStatusAndCreatedAt($input: OwnershipTransferRequestsListByStatusAndCreatedAtInput!) {
    OwnershipTransferRequestsListByStatusAndCreatedAt(input: $input) {
      items {
        transferId
        organizationId
        currentOwnerId
        newOwnerId
        status
        reason
        expiresAt
        completedAt
        cancelledAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const OwnershipTransferRequestsListByStatusAndExpiresAt = /* GraphQL */ `
  query OwnershipTransferRequestsListByStatusAndExpiresAt($input: OwnershipTransferRequestsListByStatusAndExpiresAtInput!) {
    OwnershipTransferRequestsListByStatusAndExpiresAt(input: $input) {
      items {
        transferId
        organizationId
        currentOwnerId
        newOwnerId
        status
        reason
        expiresAt
        completedAt
        cancelledAt
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;
