// AUTO-GENERATED by orb-schema-generator v0.18.5 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * GraphQL operations for Roles
 */

export const RolesCreate = /* GraphQL */ `
  mutation RolesCreate($input: RolesCreateInput!) {
    RolesCreate(input: $input) {
      items {
        roleId
        userId
        roleType
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const RolesUpdate = /* GraphQL */ `
  mutation RolesUpdate($input: RolesUpdateInput!) {
    RolesUpdate(input: $input) {
      items {
        roleId
        userId
        roleType
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const RolesDelete = /* GraphQL */ `
  mutation RolesDelete($input: RolesDeleteInput!) {
    RolesDelete(input: $input) {
      items {
        roleId
        userId
        roleType
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const RolesDisable = /* GraphQL */ `
  mutation RolesDisable($input: RolesDisableInput!) {
    RolesDisable(input: $input) {
      items {
        roleId
        userId
        roleType
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const RolesQueryByRoleId = /* GraphQL */ `
  query RolesQueryByRoleId($input: RolesQueryByRoleIdInput!) {
    RolesQueryByRoleId(input: $input) {
      items {
        roleId
        userId
        roleType
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const RolesQueryByUserId = /* GraphQL */ `
  query RolesQueryByUserId($input: RolesQueryByUserIdInput!) {
    RolesQueryByUserId(input: $input) {
      items {
        roleId
        userId
        roleType
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const RolesQueryByUserIdAndRoleType = /* GraphQL */ `
  query RolesQueryByUserIdAndRoleType($input: RolesQueryByUserIdAndRoleTypeInput!) {
    RolesQueryByUserIdAndRoleType(input: $input) {
      items {
        roleId
        userId
        roleType
        status
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;
