// AUTO-GENERATED by orb-schema-generator v1.1.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * GraphQL operations for SmsRateLimit
 */

export const SmsRateLimitCreate = /* GraphQL */ `
  mutation SmsRateLimitCreate($input: SmsRateLimitCreateInput!) {
    SmsRateLimitCreate(input: $input) {
      code
      success
      message
      item {
        phoneNumber
        requestCount
        firstRequestTime
        ttl
      }
    }
  }
`;

export const SmsRateLimitUpdate = /* GraphQL */ `
  mutation SmsRateLimitUpdate($input: SmsRateLimitUpdateInput!) {
    SmsRateLimitUpdate(input: $input) {
      code
      success
      message
      item {
        phoneNumber
        requestCount
        firstRequestTime
        ttl
      }
    }
  }
`;

export const SmsRateLimitDelete = /* GraphQL */ `
  mutation SmsRateLimitDelete($input: SmsRateLimitDeleteInput!) {
    SmsRateLimitDelete(input: $input) {
      code
      success
      message
      item {
        phoneNumber
        requestCount
        firstRequestTime
        ttl
      }
    }
  }
`;

export const SmsRateLimitDisable = /* GraphQL */ `
  mutation SmsRateLimitDisable($input: SmsRateLimitDisableInput!) {
    SmsRateLimitDisable(input: $input) {
      code
      success
      message
      item {
        phoneNumber
        requestCount
        firstRequestTime
        ttl
      }
    }
  }
`;

export const SmsRateLimitGet = /* GraphQL */ `
  query SmsRateLimitGet($input: SmsRateLimitGetInput!) {
    SmsRateLimitGet(input: $input) {
      code
      success
      message
      item {
        phoneNumber
        requestCount
        firstRequestTime
        ttl
      }
    }
  }
`;

export const SmsRateLimitListByPhoneNumber = /* GraphQL */ `
  query SmsRateLimitListByPhoneNumber($input: SmsRateLimitListByPhoneNumberInput!) {
    SmsRateLimitListByPhoneNumber(input: $input) {
      code
      success
      message
      items {
        phoneNumber
        requestCount
        firstRequestTime
        ttl
      }
      nextToken
    }
  }
`;
