// AUTO-GENERATED by orb-schema-generator v1.0.1 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * GraphQL operations for SmsVerification
 */

export const SmsVerification = /* GraphQL */ `
  mutation SmsVerification($input: SmsVerificationInput!) {
    SmsVerification(input: $input) {
      phoneNumber
      code
      valid
    }
  }
`;
