// AUTO-GENERATED by orb-schema-generator v0.18.4 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * GraphQL operations for Users
 */

export const UsersCreate = /* GraphQL */ `
  mutation UsersCreate($input: UsersCreateInput!) {
    UsersCreate(input: $input) {
      items {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
      nextToken
    }
  }
`;

export const UsersUpdate = /* GraphQL */ `
  mutation UsersUpdate($input: UsersUpdateInput!) {
    UsersUpdate(input: $input) {
      items {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
      nextToken
    }
  }
`;

export const UsersDelete = /* GraphQL */ `
  mutation UsersDelete($input: UsersDeleteInput!) {
    UsersDelete(input: $input) {
      items {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
      nextToken
    }
  }
`;

export const UsersDisable = /* GraphQL */ `
  mutation UsersDisable($input: UsersDisableInput!) {
    UsersDisable(input: $input) {
      items {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
      nextToken
    }
  }
`;

export const UsersQueryByUserId = /* GraphQL */ `
  query UsersQueryByUserId($input: UsersQueryByUserIdInput!) {
    UsersQueryByUserId(input: $input) {
      items {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
      nextToken
    }
  }
`;

export const UsersQueryByEmail = /* GraphQL */ `
  query UsersQueryByEmail($input: UsersQueryByEmailInput!) {
    UsersQueryByEmail(input: $input) {
      items {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
      nextToken
    }
  }
`;

export const UsersQueryByCognitoId = /* GraphQL */ `
  query UsersQueryByCognitoId($input: UsersQueryByCognitoIdInput!) {
    UsersQueryByCognitoId(input: $input) {
      items {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
      nextToken
    }
  }
`;

export const UsersQueryByCognitoSub = /* GraphQL */ `
  query UsersQueryByCognitoSub($input: UsersQueryByCognitoSubInput!) {
    UsersQueryByCognitoSub(input: $input) {
      items {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
      nextToken
    }
  }
`;
