// AUTO-GENERATED by orb-schema-generator v0.19.3 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * GraphQL operations for Users
 */

export const UsersCreate = /* GraphQL */ `
  mutation UsersCreate($input: UsersCreateInput!) {
    UsersCreate(input: $input) {
      code
      success
      message
      item {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
    }
  }
`;

export const UsersUpdate = /* GraphQL */ `
  mutation UsersUpdate($input: UsersUpdateInput!) {
    UsersUpdate(input: $input) {
      code
      success
      message
      item {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
    }
  }
`;

export const UsersDelete = /* GraphQL */ `
  mutation UsersDelete($input: UsersDeleteInput!) {
    UsersDelete(input: $input) {
      code
      success
      message
      item {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
    }
  }
`;

export const UsersDisable = /* GraphQL */ `
  mutation UsersDisable($input: UsersDisableInput!) {
    UsersDisable(input: $input) {
      code
      success
      message
      item {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
    }
  }
`;

export const UsersGet = /* GraphQL */ `
  query UsersGet($input: UsersGetInput!) {
    UsersGet(input: $input) {
      code
      success
      message
      item {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
    }
  }
`;

export const UsersListByUserId = /* GraphQL */ `
  query UsersListByUserId($input: UsersListByUserIdInput!) {
    UsersListByUserId(input: $input) {
      code
      success
      message
      items {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
      nextToken
    }
  }
`;

export const UsersListByEmail = /* GraphQL */ `
  query UsersListByEmail($input: UsersListByEmailInput!) {
    UsersListByEmail(input: $input) {
      code
      success
      message
      items {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
      nextToken
    }
  }
`;

export const UsersListByCognitoId = /* GraphQL */ `
  query UsersListByCognitoId($input: UsersListByCognitoIdInput!) {
    UsersListByCognitoId(input: $input) {
      code
      success
      message
      items {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
      nextToken
    }
  }
`;

export const UsersListByCognitoSub = /* GraphQL */ `
  query UsersListByCognitoSub($input: UsersListByCognitoSubInput!) {
    UsersListByCognitoSub(input: $input) {
      code
      success
      message
      items {
        userId
        cognitoId
        cognitoSub
        email
        firstName
        lastName
        status
        createdAt
        updatedAt
        phoneNumber
        groups
        emailVerified
        phoneVerified
        mfaEnabled
        mfaSetupComplete
      }
      nextToken
    }
  }
`;
