"""Unit tests for base generator."""

from pathlib import Path
import tempfile

from ..base import BaseE2EGenerator


class ConcreteGenerator(BaseE2EGenerator):
    """Concrete implementation for testing."""

    def generate(self, schema_filter=None):
        """Dummy implementation."""
        pass


class TestBaseE2EGenerator:
    """Tests for BaseE2EGenerator."""

    def test_auto_generated_header_detection(self):
        """Test AUTO-GENERATED header detection."""
        with tempfile.NamedTemporaryFile(mode="w", delete=False) as f:
            f.write("// AUTO-GENERATED by test\n")
            f.write("content here\n")
            temp_path = Path(f.name)

        try:
            generator = ConcreteGenerator(config=None, dry_run=False)
            assert generator._has_auto_generated_header(temp_path) is True
        finally:
            temp_path.unlink()

    def test_no_auto_generated_header(self):
        """Test file without AUTO-GENERATED header."""
        with tempfile.NamedTemporaryFile(mode="w", delete=False) as f:
            f.write("// Regular comment\n")
            f.write("content here\n")
            temp_path = Path(f.name)

        try:
            generator = ConcreteGenerator(config=None, dry_run=False)
            assert generator._has_auto_generated_header(temp_path) is False
        finally:
            temp_path.unlink()

    def test_file_writing_with_header_check(self):
        """Test file writing respects AUTO-GENERATED header."""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / "test.ts"

            generator = ConcreteGenerator(config=None, dry_run=False)

            # Write file first time (should succeed)
            generator._write_file(output_path, "// AUTO-GENERATED\ncontent1")
            assert output_path.exists()
            assert "content1" in output_path.read_text()

            # Overwrite file with AUTO-GENERATED header (should succeed)
            generator._write_file(output_path, "// AUTO-GENERATED\ncontent2")
            assert "content2" in output_path.read_text()

    def test_file_writing_skips_without_header(self):
        """Test file writing skips files without AUTO-GENERATED header."""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / "test.ts"

            # Create file without AUTO-GENERATED header
            output_path.write_text("// Manual file\ncontent1")

            generator = ConcreteGenerator(config=None, dry_run=False)

            # Try to overwrite (should skip)
            generator._write_file(output_path, "// AUTO-GENERATED\ncontent2")

            # Original content should remain
            assert "content1" in output_path.read_text()
            assert "content2" not in output_path.read_text()

    def test_dry_run_mode(self):
        """Test dry-run mode doesn't write files."""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / "test.ts"

            generator = ConcreteGenerator(config=None, dry_run=True)
            generator._write_file(output_path, "// AUTO-GENERATED\ncontent")

            # File should not be created
            assert not output_path.exists()

    def test_file_header_generation(self):
        """Test file header generation."""
        generator = ConcreteGenerator(config=None, dry_run=False)
        header = generator._get_file_header()

        assert "AUTO-GENERATED" in header
        assert "v0.1.0" in header
        assert "python -m tools.e2e_generator generate" in header

    def test_directory_creation(self):
        """Test directory creation for nested paths."""
        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = Path(tmpdir) / "nested" / "dir" / "test.ts"

            generator = ConcreteGenerator(config=None, dry_run=False)
            generator._write_file(output_path, "// AUTO-GENERATED\ncontent")

            assert output_path.exists()
            assert output_path.parent.exists()
