# file: schemas/entities/Applications.yml
# author: Corey Dale Peters
# date: 2025-02-17
# description: Canonical applications table. Referenced by ApplicationRoles and ApplicationUsers.

# GROUP_TYPES: OWNER, ADMIN, SUPPORT, USER (see enum definition)

type: table
version: '1.0'
name: Applications
model:
  authConfig:
    cognitoAuthentication:
      default: OWNER
      groups:
        OWNER:
          - '*'
  keys:
    primary:
      partition: applicationId
      description: Primary key for applications (unique for each application)
  attributes:
    applicationId:
      type: string
      required: true
      description: Unique identifier for the application (primary key)
    name:
      type: string
      required: true
      description: Name of the application
    ownerId:
      type: string
      required: true
      description: ID of the user who owns the application (foreign key to Users)
    status:
      type: string
      required: true
      enum_type: ApplicationStatus
      enum_values:
        - ACTIVE
        - INACTIVE
        - ARCHIVED
      description: Current status of the application
    createdAt:
      type: timestamp
      required: true
      description: When the application was created
    updatedAt:
      type: timestamp
      required: true
      description: When the application was last updated 