# file: schemas/entities/Applications.yml
# author: Corey Dale Peters
# date: 2025-02-17
# description: yaml file containing the Applications table schema

type: table
version: '1.0'
name: Applications
model:
  authConfig:
    cognitoOperations:
      - ApplicationsQueryById
      - ApplicationsResponse
      - ApplicationsCreate
      - ApplicationsUpdate
      - ApplicationsDelete
      - ApplicationsQueryByStatus
  keys:
    primary:
      partition: id
      sort: name
      projectionType: ALL
      description: Primary key for applications
    secondary:
      - name: ApplicationStatusIndex
        type: GSI
        partition: status
        sort: name
        projectionType: ALL
        description: Index for querying applications by status
      - name: ApplicationTypeIndex
        type: GSI
        partition: type
        sort: name
        projectionType: ALL
        description: Index for querying applications by type
  attributes:
    id:
      type: string
      required: true
      description: Unique identifier for the application
    name:
      type: string
      required: true
      description: Name of the application
    description:
      type: string
      required: false
      description: Description of the application
    type:
      type: string
      required: true
      enum_type: ApplicationType
      enum_values:
        - INTERNAL
        - EXTERNAL
        - SYSTEM
      description: Type of the application
    status:
      type: string
      required: true
      enum_type: ApplicationStatus
      enum_values:
        - ACTIVE
        - INACTIVE
        - PENDING
        - DELETED
      description: Status of the application
    created_at:
      type: timestamp
      required: true
      description: When the application was created
    updated_at:
      type: timestamp
      required: true
      description: When the application was last updated 