# file: schemas/tables/applications.yml
# author: Corey Dale Peters
# date: 2025-02-17
# description: yaml file containing the applications table schema

version: '1.0'
table: Applications
model:
  auth_config:
    default_auth: user_pools
  keys:
    primary:
      partition: application_id
      projection_type: ALL
      description: Primary key for applications
    secondary:
      - name: application-name-index
        type: GSI
        partition: name
        sort: application_id
        projection_type: ALL
        description: Index for querying applications by name
  attributes:
    application_id:
      type: string
      required: true
      description: Unique identifier for the application
    name:
      type: string
      required: true
      description: Name of the application
    description:
      type: string
      required: true
      description: Description of the application
    status:
      type: string
      required: true
      enum_type: ApplicationStatus
      enum_values:
        - ACTIVE
        - INACTIVE
        - PENDING
        - DELETED
      description: Current status of the application
    created_at:
      type: timestamp
      required: true
      description: When the application was created
    updated_at:
      type: timestamp
      required: true
      description: When the application was last updated
    user_id:
      type: string
      required: true
      description: Unique identifier for the user who created the application 