# file: schemas/tables/application_roles.yml
# author: Corey Dale Peters
# date: 2024-03-21
# description: yaml file containing the application roles table schema

version: '1.0'
table: ApplicationRoles
model:
  auth_config:
    api_key_operations:
      - ApplicationRole
      - ApplicationRoleResponse
      - ApplicationRoleQueryInput
      - ApplicationRoleCreateInput
      - ApplicationRoleUpdateInput
      - ApplicationRoleQueryById
      - ApplicationRoleCreate
      - ApplicationRoleUpdate
      - ApplicationRoleDelete
    default_auth: user_pools
  keys:
    primary:
      partition: application_id
      sort: role_id            
      projection_type: ALL     
      description: Primary key for application roles
    secondary:
      - name: role-status-index
        type: GSI
        partition: application_id
        sort: status
        projection_type: ALL
        description: Index for querying roles by status within an application
  attributes:
    application_id:
      type: string
      required: true
      description: Unique identifier for the application
    role_id:
      type: string
      required: true
      description: Unique identifier for the role
    description:
      type: string
      required: false
      description: Human-readable description of the role
    status:
      type: string
      enum_type: ApplicationRoleStatus
      required: true
      description: Current status of the role (ACTIVE, INACTIVE, DELETED)
    created_at:
      type: number
      required: true
      description: Unix timestamp when the role was created
    updated_at:
      type: number
      required: true
      description: Unix timestamp when the role was last updated
