// AUTO-GENERATED by orb-schema-generator v1.1.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for ApplicationApiKeys
 */

import { ApplicationApiKeyStatus } from '../../core/enums/ApplicationApiKeyStatusEnum';
import { ApplicationApiKeyType } from '../../core/enums/ApplicationApiKeyTypeEnum';
import { Environment } from '../../core/enums/EnvironmentEnum';

// Input Types
export type ApplicationApiKeysCreateInput = {
  applicationApiKeyId: string;
  applicationId: string;
  organizationId: string;
  environment: Environment;
  keyHash: string;
  keyPrefix: string;
  keyType: ApplicationApiKeyType;
  permissions?: string[];
  status: ApplicationApiKeyStatus;
  nextKeyHash?: string;
  activatesAt?: Date;
  expiresAt?: Date;
  revokedAt?: Date;
  lastUsedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
  ttl?: number;
};

export type ApplicationApiKeysUpdateInput = {
  applicationApiKeyId?: string;
  applicationId?: string;
  organizationId?: string;
  environment?: Environment;
  keyHash?: string;
  keyPrefix?: string;
  keyType?: ApplicationApiKeyType;
  permissions?: string[];
  status?: ApplicationApiKeyStatus;
  nextKeyHash?: string;
  activatesAt?: Date;
  expiresAt?: Date;
  revokedAt?: Date;
  lastUsedAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
  ttl?: number;
};

export type ApplicationApiKeysQueryByApplicationApiKeyIdInput = {
  applicationApiKeyId: string;
};

export type ApplicationApiKeysQueryByApplicationIdInput = {
  applicationId: string;
};

export type ApplicationApiKeysQueryByKeyHashInput = {
  keyHash: string;
};


// Response Types
export type ApplicationApiKeysCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationApiKeys;
};

export type ApplicationApiKeysUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationApiKeys;
};

export type ApplicationApiKeysDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationApiKeys;
};

export type ApplicationApiKeysDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationApiKeys;
};

export type ApplicationApiKeysGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationApiKeys;
};

export type ApplicationApiKeysListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: ApplicationApiKeys[];
  nextToken?: string;
};


// GraphQL Response Wrappers
export type ApplicationApiKeysCreateMutationResponse = {
  ApplicationApiKeysCreate: ApplicationApiKeysCreateResponse;
};

export type ApplicationApiKeysUpdateMutationResponse = {
  ApplicationApiKeysUpdate: ApplicationApiKeysUpdateResponse;
};

export type ApplicationApiKeysDeleteMutationResponse = {
  ApplicationApiKeysDelete: ApplicationApiKeysDeleteResponse;
};

export type ApplicationApiKeysDisableMutationResponse = {
  ApplicationApiKeysDisable: ApplicationApiKeysDisableResponse;
};

export type ApplicationApiKeysGetQueryResponse = {
  ApplicationApiKeysGet: ApplicationApiKeysGetResponse;
};

export type ApplicationApiKeysListByApplicationApiKeyIdResponse = {
  ApplicationApiKeysListByApplicationApiKeyId: ApplicationApiKeysListResponse;
};

export type ApplicationApiKeysListByApplicationIdResponse = {
  ApplicationApiKeysListByApplicationId: ApplicationApiKeysListResponse;
};

export type ApplicationApiKeysListByKeyHashResponse = {
  ApplicationApiKeysListByKeyHash: ApplicationApiKeysListResponse;
};


export interface IApplicationApiKeys {
  applicationApiKeyId: string;
  applicationId: string;
  organizationId: string;
  environment: Environment;
  keyHash: string;
  keyPrefix: string;
  keyType: ApplicationApiKeyType;
  permissions?: string[];
  status: ApplicationApiKeyStatus;
  nextKeyHash?: string;
  activatesAt?: Date;
  expiresAt?: Date;
  revokedAt?: Date;
  lastUsedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
  ttl?: number;
}

export class ApplicationApiKeys implements IApplicationApiKeys {
  applicationApiKeyId: string;
  applicationId: string;
  organizationId: string;
  environment: Environment;
  keyHash: string;
  keyPrefix: string;
  keyType: ApplicationApiKeyType;
  permissions?: string[];
  status: ApplicationApiKeyStatus;
  nextKeyHash?: string;
  activatesAt?: Date;
  expiresAt?: Date;
  revokedAt?: Date;
  lastUsedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
  ttl?: number;

  constructor(data: Partial<IApplicationApiKeys> = {}) {
    this.applicationApiKeyId = data.applicationApiKeyId ?? '';
    this.applicationId = data.applicationId ?? '';
    this.organizationId = data.organizationId ?? '';
    this.environment = data.environment ?? Environment.Production;
    this.keyHash = data.keyHash ?? '';
    this.keyPrefix = data.keyPrefix ?? '';
    this.keyType = data.keyType ?? ApplicationApiKeyType.Publishable;
    this.permissions = data.permissions;
    this.status = data.status ?? ApplicationApiKeyStatus.Active;
    this.nextKeyHash = data.nextKeyHash;
    this.activatesAt = data.activatesAt;
    this.expiresAt = data.expiresAt;
    this.revokedAt = data.revokedAt;
    this.lastUsedAt = data.lastUsedAt;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
    this.ttl = data.ttl;
  }
}