// AUTO-GENERATED by orb-schema-generator v3.2.7 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for Applications
 */

import { ApplicationStatus } from '../../core/enums/ApplicationStatusEnum';

// Response Types
export type ApplicationsCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Applications;
};

export type ApplicationsUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Applications;
};

export type ApplicationsDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Applications;
};

export type ApplicationsDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Applications;
};

export type ApplicationsGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Applications;
};

export type ApplicationsListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: Applications[];
  nextToken?: string;
};

export interface IApplications {
  applicationId: string;
  name: string;
  description?: string;
  organizationId: string;
  ownerId: string;
  status: ApplicationStatus;
  createdAt: Date;
  updatedAt: Date;
  apiKey: string;
  apiKeyNext?: string;
  environments: string[];
  groupCount?: number;
  userCount?: number;
  roleCount?: number;
}

export class Applications implements IApplications {
  applicationId: string;
  name: string;
  description?: string;
  organizationId: string;
  ownerId: string;
  status: ApplicationStatus;
  createdAt: Date;
  updatedAt: Date;
  apiKey: string;
  apiKeyNext?: string;
  environments: string[];
  groupCount?: number;
  userCount?: number;
  roleCount?: number;

  constructor(data: Partial<IApplications> = {}) {
    this.applicationId = data.applicationId ?? '';
    this.name = data.name ?? '';
    this.description = data.description;
    this.organizationId = data.organizationId ?? '';
    this.ownerId = data.ownerId ?? '';
    this.status = data.status ?? ApplicationStatus.Unknown;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
    this.apiKey = data.apiKey ?? '';
    this.apiKeyNext = data.apiKeyNext;
    this.environments = data.environments ?? [];
    this.groupCount = data.groupCount;
    this.userCount = data.userCount;
    this.roleCount = data.roleCount;
  }
}