// AUTO-GENERATED by orb-schema-generator v3.2.7 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for ApplicationApiKeyStatus
 */


// Response Types
export type ApplicationApiKeyStatusCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationApiKeyStatus;
};

export type ApplicationApiKeyStatusUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationApiKeyStatus;
};

export type ApplicationApiKeyStatusDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationApiKeyStatus;
};

export type ApplicationApiKeyStatusDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationApiKeyStatus;
};

export type ApplicationApiKeyStatusGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationApiKeyStatus;
};

export type ApplicationApiKeyStatusListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: ApplicationApiKeyStatus[];
  nextToken?: string;
};

export interface IApplicationApiKeyStatus {
  value: string;
}

export class ApplicationApiKeyStatus implements IApplicationApiKeyStatus {
  value: string;

  constructor(data: Partial<IApplicationApiKeyStatus> = {}) {
    this.value = data.value ?? '';
  }
}