// AUTO-GENERATED by orb-schema-generator v0.13.5 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for Applications
 */

import { ApplicationStatus } from '../../core/enums/ApplicationStatusEnum';

// Input Types
export interface ApplicationsCreateInput {
  applicationId: string;
  name: string;
  organizationId: string;
  ownerId: string;
  status: ApplicationStatus;
  createdAt: Date;
  updatedAt: Date;
  apiKey: string;
  apiKeyNext?: string;
  environments: string[];
}

export interface ApplicationsUpdateInput {
  applicationId?: string;
  name?: string;
  organizationId?: string;
  ownerId?: string;
  status?: ApplicationStatus;
  createdAt?: Date;
  updatedAt?: Date;
  apiKey?: string;
  apiKeyNext?: string;
  environments?: string[];
}

export interface ApplicationsQueryByApplicationIdInput {
  applicationId: string;
}

export interface ApplicationsQueryByOrganizationIdInput {
  organizationId: string;
}


// Response Types
export interface ApplicationsResponse {
  StatusCode: number;
  Message: string;
  Data: Applications | null;
}

export interface ApplicationsCreateResponse {
  StatusCode: number;
  Message: string;
  Data: Applications | null;
}

export interface ApplicationsUpdateResponse {
  StatusCode: number;
  Message: string;
  Data: Applications | null;
}

export interface ApplicationsListResponse {
  StatusCode: number;
  Message: string;
  Data: Applications[] | null;
}


// GraphQL Response Wrappers
export interface ApplicationsCreateMutationResponse {
  ApplicationsCreate: ApplicationsCreateResponse;
}

export interface ApplicationsUpdateMutationResponse {
  ApplicationsUpdate: ApplicationsUpdateResponse;
}

export interface ApplicationsDeleteMutationResponse {
  ApplicationsDelete: ApplicationsResponse;
}

export interface ApplicationsQueryByApplicationIdResponse {
  ApplicationsQueryByApplicationId: ApplicationsResponse;
}

export interface ApplicationsQueryByOrganizationIdResponse {
  ApplicationsQueryByOrganizationId: ApplicationsListResponse;
}

export interface IApplications {
  applicationId: string;
  name: string;
  organizationId: string;
  ownerId: string;
  status: ApplicationStatus;
  createdAt: Date;
  updatedAt: Date;
  apiKey: string;
  apiKeyNext?: string;
  environments: string[];
}

export class Applications implements IApplications {
  applicationId: string;
  name: string;
  organizationId: string;
  ownerId: string;
  status: ApplicationStatus;
  createdAt: Date;
  updatedAt: Date;
  apiKey: string;
  apiKeyNext?: string;
  environments: string[];

  constructor(data: Partial<IApplications> = {}) {
    this.applicationId = data.applicationId ?? '';
    this.name = data.name ?? '';
    this.organizationId = data.organizationId ?? '';
    this.ownerId = data.ownerId ?? '';
    this.status = data.status ?? ApplicationStatus.Active;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
    this.apiKey = data.apiKey ?? '';
    this.apiKeyNext = data.apiKeyNext;
    this.environments = data.environments ?? [];
  }
}