// AUTO-GENERATED by orb-schema-generator v0.13.5 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for ApplicationUsers
 */

import { ApplicationUserStatus } from '../../core/enums/ApplicationUserStatusEnum';

// Input Types
export interface ApplicationUsersCreateInput {
  applicationUserId: string;
  userId: string;
  applicationId: string;
  status: ApplicationUserStatus;
  createdAt: Date;
  updatedAt: Date;
}

export interface ApplicationUsersUpdateInput {
  applicationUserId?: string;
  userId?: string;
  applicationId?: string;
  status?: ApplicationUserStatus;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface ApplicationUsersQueryByApplicationUserIdInput {
  applicationUserId: string;
}

export interface ApplicationUsersQueryByUserIdInput {
  userId: string;
}

export interface ApplicationUsersQueryByApplicationIdInput {
  applicationId: string;
}


// Response Types
export interface ApplicationUsersResponse {
  StatusCode: number;
  Message: string;
  Data: ApplicationUsers | null;
}

export interface ApplicationUsersCreateResponse {
  StatusCode: number;
  Message: string;
  Data: ApplicationUsers | null;
}

export interface ApplicationUsersUpdateResponse {
  StatusCode: number;
  Message: string;
  Data: ApplicationUsers | null;
}

export interface ApplicationUsersListResponse {
  StatusCode: number;
  Message: string;
  Data: ApplicationUsers[] | null;
}


// GraphQL Response Wrappers
export interface ApplicationUsersCreateMutationResponse {
  ApplicationUsersCreate: ApplicationUsersCreateResponse;
}

export interface ApplicationUsersUpdateMutationResponse {
  ApplicationUsersUpdate: ApplicationUsersUpdateResponse;
}

export interface ApplicationUsersDeleteMutationResponse {
  ApplicationUsersDelete: ApplicationUsersResponse;
}

export interface ApplicationUsersQueryByApplicationUserIdResponse {
  ApplicationUsersQueryByApplicationUserId: ApplicationUsersResponse;
}

export interface ApplicationUsersQueryByUserIdResponse {
  ApplicationUsersQueryByUserId: ApplicationUsersListResponse;
}

export interface ApplicationUsersQueryByApplicationIdResponse {
  ApplicationUsersQueryByApplicationId: ApplicationUsersListResponse;
}

export interface IApplicationUsers {
  applicationUserId: string;
  userId: string;
  applicationId: string;
  status: ApplicationUserStatus;
  createdAt: Date;
  updatedAt: Date;
}

export class ApplicationUsers implements IApplicationUsers {
  applicationUserId: string;
  userId: string;
  applicationId: string;
  status: ApplicationUserStatus;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<IApplicationUsers> = {}) {
    this.applicationUserId = data.applicationUserId ?? '';
    this.userId = data.userId ?? '';
    this.applicationId = data.applicationId ?? '';
    this.status = data.status ?? ApplicationUserStatus.Active;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
  }
}