// AUTO-GENERATED by orb-schema-generator v1.1.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for ApplicationGroupRoles
 */

import { ApplicationGroupRoleStatus } from '../../core/enums/ApplicationGroupRoleStatusEnum';
import { Environment } from '../../core/enums/EnvironmentEnum';

// Input Types
export type ApplicationGroupRolesCreateInput = {
  applicationGroupRoleId: string;
  applicationGroupId: string;
  applicationId: string;
  environment: Environment;
  roleId: string;
  roleName: string;
  permissions: string[];
  status: ApplicationGroupRoleStatus;
  createdAt: Date;
  updatedAt: Date;
};

export type ApplicationGroupRolesUpdateInput = {
  applicationGroupRoleId?: string;
  applicationGroupId?: string;
  applicationId?: string;
  environment?: Environment;
  roleId?: string;
  roleName?: string;
  permissions?: string[];
  status?: ApplicationGroupRoleStatus;
  createdAt?: Date;
  updatedAt?: Date;
};

export type ApplicationGroupRolesQueryByApplicationGroupRoleIdInput = {
  applicationGroupRoleId: string;
};

export type ApplicationGroupRolesQueryByApplicationGroupIdInput = {
  applicationGroupId: string;
};

export type ApplicationGroupRolesQueryByApplicationIdInput = {
  applicationId: string;
};


// Response Types
export type ApplicationGroupRolesCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationGroupRoles;
};

export type ApplicationGroupRolesUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationGroupRoles;
};

export type ApplicationGroupRolesDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationGroupRoles;
};

export type ApplicationGroupRolesDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationGroupRoles;
};

export type ApplicationGroupRolesGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationGroupRoles;
};

export type ApplicationGroupRolesListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: ApplicationGroupRoles[];
  nextToken?: string;
};


// GraphQL Response Wrappers
export type ApplicationGroupRolesCreateMutationResponse = {
  ApplicationGroupRolesCreate: ApplicationGroupRolesCreateResponse;
};

export type ApplicationGroupRolesUpdateMutationResponse = {
  ApplicationGroupRolesUpdate: ApplicationGroupRolesUpdateResponse;
};

export type ApplicationGroupRolesDeleteMutationResponse = {
  ApplicationGroupRolesDelete: ApplicationGroupRolesDeleteResponse;
};

export type ApplicationGroupRolesDisableMutationResponse = {
  ApplicationGroupRolesDisable: ApplicationGroupRolesDisableResponse;
};

export type ApplicationGroupRolesGetQueryResponse = {
  ApplicationGroupRolesGet: ApplicationGroupRolesGetResponse;
};

export type ApplicationGroupRolesListByApplicationGroupRoleIdResponse = {
  ApplicationGroupRolesListByApplicationGroupRoleId: ApplicationGroupRolesListResponse;
};

export type ApplicationGroupRolesListByApplicationGroupIdResponse = {
  ApplicationGroupRolesListByApplicationGroupId: ApplicationGroupRolesListResponse;
};

export type ApplicationGroupRolesListByApplicationIdResponse = {
  ApplicationGroupRolesListByApplicationId: ApplicationGroupRolesListResponse;
};


export interface IApplicationGroupRoles {
  applicationGroupRoleId: string;
  applicationGroupId: string;
  applicationId: string;
  environment: Environment;
  roleId: string;
  roleName: string;
  permissions: string[];
  status: ApplicationGroupRoleStatus;
  createdAt: Date;
  updatedAt: Date;
}

export class ApplicationGroupRoles implements IApplicationGroupRoles {
  applicationGroupRoleId: string;
  applicationGroupId: string;
  applicationId: string;
  environment: Environment;
  roleId: string;
  roleName: string;
  permissions: string[];
  status: ApplicationGroupRoleStatus;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<IApplicationGroupRoles> = {}) {
    this.applicationGroupRoleId = data.applicationGroupRoleId ?? '';
    this.applicationGroupId = data.applicationGroupId ?? '';
    this.applicationId = data.applicationId ?? '';
    this.environment = data.environment ?? Environment.Production;
    this.roleId = data.roleId ?? '';
    this.roleName = data.roleName ?? '';
    this.permissions = data.permissions ?? [];
    this.status = data.status ?? ApplicationGroupRoleStatus.Active;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
  }
}