// AUTO-GENERATED by orb-schema-generator v1.1.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for ApplicationUsers
 */

import { ApplicationUserStatus } from '../../core/enums/ApplicationUserStatusEnum';

// Input Types
export type ApplicationUsersCreateInput = {
  applicationUserId: string;
  userId: string;
  applicationId: string;
  status: ApplicationUserStatus;
  createdAt: Date;
  updatedAt: Date;
};

export type ApplicationUsersUpdateInput = {
  applicationUserId?: string;
  userId?: string;
  applicationId?: string;
  status?: ApplicationUserStatus;
  createdAt?: Date;
  updatedAt?: Date;
};

export type ApplicationUsersQueryByApplicationUserIdInput = {
  applicationUserId: string;
};

export type ApplicationUsersQueryByUserIdInput = {
  userId: string;
};

export type ApplicationUsersQueryByApplicationIdInput = {
  applicationId: string;
};


// Response Types
export type ApplicationUsersCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationUsers;
};

export type ApplicationUsersUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationUsers;
};

export type ApplicationUsersDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationUsers;
};

export type ApplicationUsersDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationUsers;
};

export type ApplicationUsersGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationUsers;
};

export type ApplicationUsersListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: ApplicationUsers[];
  nextToken?: string;
};


// GraphQL Response Wrappers
export type ApplicationUsersCreateMutationResponse = {
  ApplicationUsersCreate: ApplicationUsersCreateResponse;
};

export type ApplicationUsersUpdateMutationResponse = {
  ApplicationUsersUpdate: ApplicationUsersUpdateResponse;
};

export type ApplicationUsersDeleteMutationResponse = {
  ApplicationUsersDelete: ApplicationUsersDeleteResponse;
};

export type ApplicationUsersDisableMutationResponse = {
  ApplicationUsersDisable: ApplicationUsersDisableResponse;
};

export type ApplicationUsersGetQueryResponse = {
  ApplicationUsersGet: ApplicationUsersGetResponse;
};

export type ApplicationUsersListByApplicationUserIdResponse = {
  ApplicationUsersListByApplicationUserId: ApplicationUsersListResponse;
};

export type ApplicationUsersListByUserIdResponse = {
  ApplicationUsersListByUserId: ApplicationUsersListResponse;
};

export type ApplicationUsersListByApplicationIdResponse = {
  ApplicationUsersListByApplicationId: ApplicationUsersListResponse;
};


export interface IApplicationUsers {
  applicationUserId: string;
  userId: string;
  applicationId: string;
  status: ApplicationUserStatus;
  createdAt: Date;
  updatedAt: Date;
}

export class ApplicationUsers implements IApplicationUsers {
  applicationUserId: string;
  userId: string;
  applicationId: string;
  status: ApplicationUserStatus;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<IApplicationUsers> = {}) {
    this.applicationUserId = data.applicationUserId ?? '';
    this.userId = data.userId ?? '';
    this.applicationId = data.applicationId ?? '';
    this.status = data.status ?? ApplicationUserStatus.Active;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
  }
}