// AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for ApplicationApiKeys
 */

import { ApplicationApiKeyStatus } from '../../core/enums/ApplicationApiKeyStatusEnum';
import { ApplicationApiKeyType } from '../../core/enums/ApplicationApiKeyTypeEnum';
import { Environment } from '../../core/enums/EnvironmentEnum';

// Response Types
export type ApplicationApiKeysCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationApiKeys;
};

export type ApplicationApiKeysUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationApiKeys;
};

export type ApplicationApiKeysDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationApiKeys;
};

export type ApplicationApiKeysDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationApiKeys;
};

export type ApplicationApiKeysGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationApiKeys;
};

export type ApplicationApiKeysListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: ApplicationApiKeys[];
  nextToken?: string;
};

export interface IApplicationApiKeys {
  applicationApiKeyId: string;
  applicationId: string;
  organizationId: string;
  environment: Environment;
  keyHash: string;
  keyPrefix: string;
  keyType: ApplicationApiKeyType;
  permissions?: string[];
  status: ApplicationApiKeyStatus;
  nextKeyHash?: string;
  activatesAt?: Date;
  expiresAt?: Date;
  revokedAt?: Date;
  lastUsedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
  ttl?: number;
}

export class ApplicationApiKeys implements IApplicationApiKeys {
  applicationApiKeyId: string;
  applicationId: string;
  organizationId: string;
  environment: Environment;
  keyHash: string;
  keyPrefix: string;
  keyType: ApplicationApiKeyType;
  permissions?: string[];
  status: ApplicationApiKeyStatus;
  nextKeyHash?: string;
  activatesAt?: Date;
  expiresAt?: Date;
  revokedAt?: Date;
  lastUsedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
  ttl?: number;

  constructor(data: Partial<IApplicationApiKeys> = {}) {
    this.applicationApiKeyId = data.applicationApiKeyId ?? '';
    this.applicationId = data.applicationId ?? '';
    this.organizationId = data.organizationId ?? '';
    this.environment = data.environment ?? Environment.Unknown;
    this.keyHash = data.keyHash ?? '';
    this.keyPrefix = data.keyPrefix ?? '';
    this.keyType = data.keyType ?? ApplicationApiKeyType.Unknown;
    this.permissions = data.permissions;
    this.status = data.status ?? ApplicationApiKeyStatus.Unknown;
    this.nextKeyHash = data.nextKeyHash;
    this.activatesAt = data.activatesAt;
    this.expiresAt = data.expiresAt;
    this.revokedAt = data.revokedAt;
    this.lastUsedAt = data.lastUsedAt;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
    this.ttl = data.ttl;
  }
}