// AUTO-GENERATED by orb-schema-generator v1.3.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for ApplicationGroups
 */

import { ApplicationGroupStatus } from '../../core/enums/ApplicationGroupStatusEnum';

// Input Types
export type ApplicationGroupsCreateInput = {
  applicationGroupId: string;
  applicationId: string;
  name: string;
  description?: string;
  status: ApplicationGroupStatus;
  memberCount?: number;
  createdAt: Date;
  updatedAt: Date;
};

export type ApplicationGroupsUpdateInput = {
  applicationGroupId?: string;
  applicationId?: string;
  name?: string;
  description?: string;
  status?: ApplicationGroupStatus;
  memberCount?: number;
  createdAt?: Date;
  updatedAt?: Date;
};

export type ApplicationGroupsQueryByApplicationGroupIdInput = {
  applicationGroupId: string;
};

export type ApplicationGroupsQueryByApplicationIdInput = {
  applicationId: string;
};


// Response Types
export type ApplicationGroupsCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationGroups;
};

export type ApplicationGroupsUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationGroups;
};

export type ApplicationGroupsDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationGroups;
};

export type ApplicationGroupsDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationGroups;
};

export type ApplicationGroupsGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationGroups;
};

export type ApplicationGroupsListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: ApplicationGroups[];
  nextToken?: string;
};


// GraphQL Response Wrappers
export type ApplicationGroupsCreateMutationResponse = {
  ApplicationGroupsCreate: ApplicationGroupsCreateResponse;
};

export type ApplicationGroupsUpdateMutationResponse = {
  ApplicationGroupsUpdate: ApplicationGroupsUpdateResponse;
};

export type ApplicationGroupsDeleteMutationResponse = {
  ApplicationGroupsDelete: ApplicationGroupsDeleteResponse;
};

export type ApplicationGroupsDisableMutationResponse = {
  ApplicationGroupsDisable: ApplicationGroupsDisableResponse;
};

export type ApplicationGroupsGetQueryResponse = {
  ApplicationGroupsGet: ApplicationGroupsGetResponse;
};

export type ApplicationGroupsListByApplicationGroupIdResponse = {
  ApplicationGroupsListByApplicationGroupId: ApplicationGroupsListResponse;
};

export type ApplicationGroupsListByApplicationIdResponse = {
  ApplicationGroupsListByApplicationId: ApplicationGroupsListResponse;
};


export interface IApplicationGroups {
  applicationGroupId: string;
  applicationId: string;
  name: string;
  description?: string;
  status: ApplicationGroupStatus;
  memberCount?: number;
  createdAt: Date;
  updatedAt: Date;
}

export class ApplicationGroups implements IApplicationGroups {
  applicationGroupId: string;
  applicationId: string;
  name: string;
  description?: string;
  status: ApplicationGroupStatus;
  memberCount?: number;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<IApplicationGroups> = {}) {
    this.applicationGroupId = data.applicationGroupId ?? '';
    this.applicationId = data.applicationId ?? '';
    this.name = data.name ?? '';
    this.description = data.description;
    this.status = data.status ?? ApplicationGroupStatus.Active;
    this.memberCount = data.memberCount;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
  }
}