// AUTO-GENERATED by orb-schema-generator v1.1.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for ApplicationGroupUsers
 */

import { ApplicationGroupUserStatus } from '../../core/enums/ApplicationGroupUserStatusEnum';

// Input Types
export type ApplicationGroupUsersCreateInput = {
  applicationGroupUserId: string;
  applicationGroupId: string;
  userId: string;
  applicationId: string;
  status: ApplicationGroupUserStatus;
  createdAt: Date;
  updatedAt: Date;
};

export type ApplicationGroupUsersUpdateInput = {
  applicationGroupUserId?: string;
  applicationGroupId?: string;
  userId?: string;
  applicationId?: string;
  status?: ApplicationGroupUserStatus;
  createdAt?: Date;
  updatedAt?: Date;
};

export type ApplicationGroupUsersQueryByApplicationGroupUserIdInput = {
  applicationGroupUserId: string;
};

export type ApplicationGroupUsersQueryByApplicationGroupIdInput = {
  applicationGroupId: string;
};

export type ApplicationGroupUsersQueryByUserIdInput = {
  userId: string;
};


// Response Types
export type ApplicationGroupUsersCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationGroupUsers;
};

export type ApplicationGroupUsersUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationGroupUsers;
};

export type ApplicationGroupUsersDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationGroupUsers;
};

export type ApplicationGroupUsersDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationGroupUsers;
};

export type ApplicationGroupUsersGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationGroupUsers;
};

export type ApplicationGroupUsersListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: ApplicationGroupUsers[];
  nextToken?: string;
};


// GraphQL Response Wrappers
export type ApplicationGroupUsersCreateMutationResponse = {
  ApplicationGroupUsersCreate: ApplicationGroupUsersCreateResponse;
};

export type ApplicationGroupUsersUpdateMutationResponse = {
  ApplicationGroupUsersUpdate: ApplicationGroupUsersUpdateResponse;
};

export type ApplicationGroupUsersDeleteMutationResponse = {
  ApplicationGroupUsersDelete: ApplicationGroupUsersDeleteResponse;
};

export type ApplicationGroupUsersDisableMutationResponse = {
  ApplicationGroupUsersDisable: ApplicationGroupUsersDisableResponse;
};

export type ApplicationGroupUsersGetQueryResponse = {
  ApplicationGroupUsersGet: ApplicationGroupUsersGetResponse;
};

export type ApplicationGroupUsersListByApplicationGroupUserIdResponse = {
  ApplicationGroupUsersListByApplicationGroupUserId: ApplicationGroupUsersListResponse;
};

export type ApplicationGroupUsersListByApplicationGroupIdResponse = {
  ApplicationGroupUsersListByApplicationGroupId: ApplicationGroupUsersListResponse;
};

export type ApplicationGroupUsersListByUserIdResponse = {
  ApplicationGroupUsersListByUserId: ApplicationGroupUsersListResponse;
};


export interface IApplicationGroupUsers {
  applicationGroupUserId: string;
  applicationGroupId: string;
  userId: string;
  applicationId: string;
  status: ApplicationGroupUserStatus;
  createdAt: Date;
  updatedAt: Date;
}

export class ApplicationGroupUsers implements IApplicationGroupUsers {
  applicationGroupUserId: string;
  applicationGroupId: string;
  userId: string;
  applicationId: string;
  status: ApplicationGroupUserStatus;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<IApplicationGroupUsers> = {}) {
    this.applicationGroupUserId = data.applicationGroupUserId ?? '';
    this.applicationGroupId = data.applicationGroupId ?? '';
    this.userId = data.userId ?? '';
    this.applicationId = data.applicationId ?? '';
    this.status = data.status ?? ApplicationGroupUserStatus.Active;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
  }
}