// AUTO-GENERATED by orb-schema-generator v3.2.7 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for ApplicationEnvironmentConfig
 */

import { Environment } from '../../core/enums/EnvironmentEnum';

// Response Types
export type ApplicationEnvironmentConfigCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationEnvironmentConfig;
};

export type ApplicationEnvironmentConfigUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationEnvironmentConfig;
};

export type ApplicationEnvironmentConfigDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationEnvironmentConfig;
};

export type ApplicationEnvironmentConfigDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationEnvironmentConfig;
};

export type ApplicationEnvironmentConfigGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationEnvironmentConfig;
};

export type ApplicationEnvironmentConfigListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: ApplicationEnvironmentConfig[];
  nextToken?: string;
};

export interface IApplicationEnvironmentConfig {
  applicationId: string;
  environment: Environment;
  organizationId: string;
  allowedOrigins?: string[];
  rateLimitPerMinute: number;
  rateLimitPerDay: number;
  webhookUrl?: string;
  webhookSecret?: string;
  webhookEvents?: string[];
  webhookEnabled?: boolean;
  webhookMaxRetries?: number;
  webhookRetryDelaySeconds?: number;
  featureFlags?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  createdAt: Date;
  updatedAt: Date;
}

export class ApplicationEnvironmentConfig implements IApplicationEnvironmentConfig {
  applicationId: string;
  environment: Environment;
  organizationId: string;
  allowedOrigins?: string[];
  rateLimitPerMinute: number;
  rateLimitPerDay: number;
  webhookUrl?: string;
  webhookSecret?: string;
  webhookEvents?: string[];
  webhookEnabled?: boolean;
  webhookMaxRetries?: number;
  webhookRetryDelaySeconds?: number;
  featureFlags?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<IApplicationEnvironmentConfig> = {}) {
    this.applicationId = data.applicationId ?? '';
    this.environment = data.environment ?? Environment.Unknown;
    this.organizationId = data.organizationId ?? '';
    this.allowedOrigins = data.allowedOrigins;
    this.rateLimitPerMinute = data.rateLimitPerMinute ?? 0;
    this.rateLimitPerDay = data.rateLimitPerDay ?? 0;
    this.webhookUrl = data.webhookUrl;
    this.webhookSecret = data.webhookSecret;
    this.webhookEvents = data.webhookEvents;
    this.webhookEnabled = data.webhookEnabled;
    this.webhookMaxRetries = data.webhookMaxRetries;
    this.webhookRetryDelaySeconds = data.webhookRetryDelaySeconds;
    this.featureFlags = data.featureFlags;
    this.metadata = data.metadata;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
  }
}