// AUTO-GENERATED by orb-schema-generator v3.2.7 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for ApplicationRoleStatus
 */


// Response Types
export type ApplicationRoleStatusCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationRoleStatus;
};

export type ApplicationRoleStatusUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationRoleStatus;
};

export type ApplicationRoleStatusDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationRoleStatus;
};

export type ApplicationRoleStatusDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationRoleStatus;
};

export type ApplicationRoleStatusGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ApplicationRoleStatus;
};

export type ApplicationRoleStatusListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: ApplicationRoleStatus[];
  nextToken?: string;
};

export interface IApplicationRoleStatus {
  value: string;
}

export class ApplicationRoleStatus implements IApplicationRoleStatus {
  value: string;

  constructor(data: Partial<IApplicationRoleStatus> = {}) {
    this.value = data.value ?? '';
  }
}