// AUTO-GENERATED by orb-schema-generator v0.19.1 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for Applications
 */

import { ApplicationStatus } from '../../core/enums/ApplicationStatusEnum';

// Input Types
export type ApplicationsCreateInput = {
  applicationId: string;
  name: string;
  organizationId: string;
  ownerId: string;
  status: ApplicationStatus;
  createdAt: Date;
  updatedAt: Date;
  apiKey: string;
  apiKeyNext?: string;
  environments: string[];
};

export type ApplicationsUpdateInput = {
  applicationId?: string;
  name?: string;
  organizationId?: string;
  ownerId?: string;
  status?: ApplicationStatus;
  createdAt?: Date;
  updatedAt?: Date;
  apiKey?: string;
  apiKeyNext?: string;
  environments?: string[];
};

export type ApplicationsQueryByApplicationIdInput = {
  applicationId: string;
};

export type ApplicationsQueryByOrganizationIdInput = {
  organizationId: string;
};


// Response Types
export type ApplicationsCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Applications;
};

export type ApplicationsUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Applications;
};

export type ApplicationsDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Applications;
};

export type ApplicationsDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Applications;
};

export type ApplicationsGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Applications;
};

export type ApplicationsListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: Applications[];
  nextToken?: string;
};


// GraphQL Response Wrappers
export type ApplicationsCreateMutationResponse = {
  ApplicationsCreate: ApplicationsCreateResponse;
};

export type ApplicationsUpdateMutationResponse = {
  ApplicationsUpdate: ApplicationsUpdateResponse;
};

export type ApplicationsDeleteMutationResponse = {
  ApplicationsDelete: ApplicationsDeleteResponse;
};

export type ApplicationsDisableMutationResponse = {
  ApplicationsDisable: ApplicationsDisableResponse;
};

export type ApplicationsGetQueryResponse = {
  ApplicationsGet: ApplicationsGetResponse;
};

export type ApplicationsListByApplicationIdResponse = {
  ApplicationsListByApplicationId: ApplicationsListResponse;
};

export type ApplicationsListByOrganizationIdResponse = {
  ApplicationsListByOrganizationId: ApplicationsListResponse;
};

export interface IApplications {
  applicationId: string;
  name: string;
  organizationId: string;
  ownerId: string;
  status: ApplicationStatus;
  createdAt: Date;
  updatedAt: Date;
  apiKey: string;
  apiKeyNext?: string;
  environments: string[];
}

export class Applications implements IApplications {
  applicationId: string;
  name: string;
  organizationId: string;
  ownerId: string;
  status: ApplicationStatus;
  createdAt: Date;
  updatedAt: Date;
  apiKey: string;
  apiKeyNext?: string;
  environments: string[];

  constructor(data: Partial<IApplications> = {}) {
    this.applicationId = data.applicationId ?? '';
    this.name = data.name ?? '';
    this.organizationId = data.organizationId ?? '';
    this.ownerId = data.ownerId ?? '';
    this.status = data.status ?? ApplicationStatus.Active;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
    this.apiKey = data.apiKey ?? '';
    this.apiKeyNext = data.apiKeyNext;
    this.environments = data.environments ?? [];
  }
}