// AUTO-GENERATED by orb-schema-generator v0.16.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for AuthError
 */


// Response Types
export type AuthErrorResponse = {
  StatusCode: number;
  Message: string;
  Data: AuthError | null;
};

export type AuthErrorCreateResponse = {
  StatusCode: number;
  Message: string;
  Data: AuthError | null;
};

export type AuthErrorUpdateResponse = {
  StatusCode: number;
  Message: string;
  Data: AuthError | null;
};

export type AuthErrorListResponse = {
  StatusCode: number;
  Message: string;
  Data: AuthError[] | null;
};

export interface IAuthError {
  code: string;
  message: string;
  description?: string;
  details?: Record<string, unknown>;
}

export class AuthError implements IAuthError {
  code: string;
  message: string;
  description?: string;
  details?: Record<string, unknown>;

  constructor(data: Partial<IAuthError> = {}) {
    this.code = data.code ?? '';
    this.message = data.message ?? '';
    this.description = data.description;
    this.details = data.details;
  }
}