// AUTO-GENERATED by orb-schema-generator v0.13.6 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for Auth
 */

import { MfaSetupDetails } from './MfaSetupDetailsModel';
import { Users } from './UsersModel';

// Response Types
export type AuthResponse = {
  StatusCode: number;
  Message: string;
  Data: Auth | null;
};

export type AuthCreateResponse = {
  StatusCode: number;
  Message: string;
  Data: Auth | null;
};

export type AuthUpdateResponse = {
  StatusCode: number;
  Message: string;
  Data: Auth | null;
};

export type AuthListResponse = {
  StatusCode: number;
  Message: string;
  Data: Auth[] | null;
};

export interface IAuth {
  statusCode: number;
  isSignedIn?: boolean;
  message?: string;
  user?: Users;
  needsMFA?: boolean;
  needsMFASetup?: boolean;
  mfaType?: string;
  mfaSetupDetails?: MfaSetupDetails;
}

export class Auth implements IAuth {
  statusCode: number;
  isSignedIn?: boolean;
  message?: string;
  user?: Users;
  needsMFA?: boolean;
  needsMFASetup?: boolean;
  mfaType?: string;
  mfaSetupDetails?: MfaSetupDetails;

  constructor(data: Partial<IAuth> = {}) {
    this.statusCode = data.statusCode ?? 0;
    this.isSignedIn = data.isSignedIn;
    this.message = data.message;
    this.user = data.user;
    this.needsMFA = data.needsMFA;
    this.needsMFASetup = data.needsMFASetup;
    this.mfaType = data.mfaType;
    this.mfaSetupDetails = data.mfaSetupDetails;
  }
}