// AUTO-GENERATED by orb-schema-generator v1.1.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for AuthError
 */


// Response Types
export type AuthErrorCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: AuthError;
};

export type AuthErrorUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: AuthError;
};

export type AuthErrorDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: AuthError;
};

export type AuthErrorDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: AuthError;
};

export type AuthErrorGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: AuthError;
};

export type AuthErrorListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: AuthError[];
  nextToken?: string;
};

export interface IAuthError {
  code: string;
  message: string;
  description?: string;
  details?: Record<string, unknown>;
}

export class AuthError implements IAuthError {
  code: string;
  message: string;
  description?: string;
  details?: Record<string, unknown>;

  constructor(data: Partial<IAuthError> = {}) {
    this.code = data.code ?? '';
    this.message = data.message ?? '';
    this.description = data.description;
    this.details = data.details;
  }
}