// AUTO-GENERATED by orb-schema-generator v0.18.1 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for CheckEmailExists
 */


// Response Types
export type CheckEmailExistsResponse = {
  StatusCode: number;
  Message: string;
  Data: CheckEmailExists | null;
};

export type CheckEmailExistsCreateResponse = {
  StatusCode: number;
  Message: string;
  Data: CheckEmailExists | null;
};

export type CheckEmailExistsUpdateResponse = {
  StatusCode: number;
  Message: string;
  Data: CheckEmailExists | null;
};

export type CheckEmailExistsListResponse = {
  StatusCode: number;
  Message: string;
  Data: CheckEmailExists[] | null;
};

export interface ICheckEmailExists {
  email: string;
  exists?: boolean;
  cognitoStatus?: string;
  cognitoSub?: string;
}

export class CheckEmailExists implements ICheckEmailExists {
  email: string;
  exists?: boolean;
  cognitoStatus?: string;
  cognitoSub?: string;

  constructor(data: Partial<ICheckEmailExists> = {}) {
    this.email = data.email ?? '';
    this.exists = data.exists;
    this.cognitoStatus = data.cognitoStatus;
    this.cognitoSub = data.cognitoSub;
  }
}