// AUTO-GENERATED by orb-schema-generator v1.3.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for CheckEmailExists
 */


// Response Types
export type CheckEmailExistsCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: CheckEmailExists;
};

export type CheckEmailExistsUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: CheckEmailExists;
};

export type CheckEmailExistsDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: CheckEmailExists;
};

export type CheckEmailExistsDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: CheckEmailExists;
};

export type CheckEmailExistsGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: CheckEmailExists;
};

export type CheckEmailExistsListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: CheckEmailExists[];
  nextToken?: string;
};

export interface ICheckEmailExists {
  email: string;
  exists?: boolean;
  cognitoStatus?: string;
  cognitoSub?: string;
}

export class CheckEmailExists implements ICheckEmailExists {
  email: string;
  exists?: boolean;
  cognitoStatus?: string;
  cognitoSub?: string;

  constructor(data: Partial<ICheckEmailExists> = {}) {
    this.email = data.email ?? '';
    this.exists = data.exists;
    this.cognitoStatus = data.cognitoStatus;
    this.cognitoSub = data.cognitoSub;
  }
}