// AUTO-GENERATED by orb-schema-generator v1.3.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for CreateUserFromCognito
 */


// Response Types
export type CreateUserFromCognitoCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: CreateUserFromCognito;
};

export type CreateUserFromCognitoUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: CreateUserFromCognito;
};

export type CreateUserFromCognitoDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: CreateUserFromCognito;
};

export type CreateUserFromCognitoDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: CreateUserFromCognito;
};

export type CreateUserFromCognitoGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: CreateUserFromCognito;
};

export type CreateUserFromCognitoListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: CreateUserFromCognito[];
  nextToken?: string;
};

export interface ICreateUserFromCognito {
  cognitoSub: string;
  userId?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  status?: string;
  emailVerified?: boolean;
  phoneVerified?: boolean;
  mfaEnabled?: boolean;
  mfaSetupComplete?: boolean;
  groups?: string[];
  createdAt?: Date;
  updatedAt?: Date;
}

export class CreateUserFromCognito implements ICreateUserFromCognito {
  cognitoSub: string;
  userId?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  status?: string;
  emailVerified?: boolean;
  phoneVerified?: boolean;
  mfaEnabled?: boolean;
  mfaSetupComplete?: boolean;
  groups?: string[];
  createdAt?: Date;
  updatedAt?: Date;

  constructor(data: Partial<ICreateUserFromCognito> = {}) {
    this.cognitoSub = data.cognitoSub ?? '';
    this.userId = data.userId;
    this.email = data.email;
    this.firstName = data.firstName;
    this.lastName = data.lastName;
    this.status = data.status;
    this.emailVerified = data.emailVerified;
    this.phoneVerified = data.phoneVerified;
    this.mfaEnabled = data.mfaEnabled;
    this.mfaSetupComplete = data.mfaSetupComplete;
    this.groups = data.groups;
    this.createdAt = data.createdAt;
    this.updatedAt = data.updatedAt;
  }
}