// AUTO-GENERATED by orb-schema-generator v3.2.7 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for EnvironmentConfigurationStatus
 */


// Response Types
export type EnvironmentConfigurationStatusCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: EnvironmentConfigurationStatus;
};

export type EnvironmentConfigurationStatusUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: EnvironmentConfigurationStatus;
};

export type EnvironmentConfigurationStatusDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: EnvironmentConfigurationStatus;
};

export type EnvironmentConfigurationStatusDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: EnvironmentConfigurationStatus;
};

export type EnvironmentConfigurationStatusGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: EnvironmentConfigurationStatus;
};

export type EnvironmentConfigurationStatusListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: EnvironmentConfigurationStatus[];
  nextToken?: string;
};

export interface IEnvironmentConfigurationStatus {
  value: string;
}

export class EnvironmentConfigurationStatus implements IEnvironmentConfigurationStatus {
  value: string;

  constructor(data: Partial<IEnvironmentConfigurationStatus> = {}) {
    this.value = data.value ?? '';
  }
}