// AUTO-GENERATED by orb-schema-generator v1.3.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for GetApplicationUsers
 */


// Response Types
export type GetApplicationUsersCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: GetApplicationUsers;
};

export type GetApplicationUsersUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: GetApplicationUsers;
};

export type GetApplicationUsersDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: GetApplicationUsers;
};

export type GetApplicationUsersDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: GetApplicationUsers;
};

export type GetApplicationUsersGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: GetApplicationUsers;
};

export type GetApplicationUsersListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: GetApplicationUsers[];
  nextToken?: string;
};

export interface IGetApplicationUsers {
  organizationIds?: string[];
  applicationIds?: string[];
  environment?: string;
  limit?: number;
  nextToken?: string;
  users: string[];
}

export class GetApplicationUsers implements IGetApplicationUsers {
  organizationIds?: string[];
  applicationIds?: string[];
  environment?: string;
  limit?: number;
  nextToken?: string;
  users: string[];

  constructor(data: Partial<IGetApplicationUsers> = {}) {
    this.organizationIds = data.organizationIds;
    this.applicationIds = data.applicationIds;
    this.environment = data.environment;
    this.limit = data.limit;
    this.nextToken = data.nextToken;
    this.users = data.users ?? [];
  }
}