// AUTO-GENERATED by orb-schema-generator v0.13.5 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for MfaSetupDetails
 */


// Response Types
export interface MfaSetupDetailsResponse {
  StatusCode: number;
  Message: string;
  Data: MfaSetupDetails | null;
}

export interface MfaSetupDetailsCreateResponse {
  StatusCode: number;
  Message: string;
  Data: MfaSetupDetails | null;
}

export interface MfaSetupDetailsUpdateResponse {
  StatusCode: number;
  Message: string;
  Data: MfaSetupDetails | null;
}

export interface MfaSetupDetailsListResponse {
  StatusCode: number;
  Message: string;
  Data: MfaSetupDetails[] | null;
}

export interface IMfaSetupDetails {
  qrCode: string;
  secretKey: string;
  setupUri?: string;
}

export class MfaSetupDetails implements IMfaSetupDetails {
  qrCode: string;
  secretKey: string;
  setupUri?: string;

  constructor(data: Partial<IMfaSetupDetails> = {}) {
    this.qrCode = data.qrCode ?? '';
    this.secretKey = data.secretKey ?? '';
    this.setupUri = data.setupUri;
  }
}