// AUTO-GENERATED by orb-schema-generator v0.17.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for MfaSetupDetails
 */


// Response Types
export type MfaSetupDetailsResponse = {
  StatusCode: number;
  Message: string;
  Data: MfaSetupDetails | null;
};

export type MfaSetupDetailsCreateResponse = {
  StatusCode: number;
  Message: string;
  Data: MfaSetupDetails | null;
};

export type MfaSetupDetailsUpdateResponse = {
  StatusCode: number;
  Message: string;
  Data: MfaSetupDetails | null;
};

export type MfaSetupDetailsListResponse = {
  StatusCode: number;
  Message: string;
  Data: MfaSetupDetails[] | null;
};

export interface IMfaSetupDetails {
  qrCode: string;
  secretKey: string;
  setupUri?: string;
}

export class MfaSetupDetails implements IMfaSetupDetails {
  qrCode: string;
  secretKey: string;
  setupUri?: string;

  constructor(data: Partial<IMfaSetupDetails> = {}) {
    this.qrCode = data.qrCode ?? '';
    this.secretKey = data.secretKey ?? '';
    this.setupUri = data.setupUri;
  }
}