// AUTO-GENERATED by orb-schema-generator v0.13.5 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for Notifications
 */

import { NotificationStatus } from '../../core/enums/NotificationStatusEnum';
import { NotificationType } from '../../core/enums/NotificationTypeEnum';

// Input Types
export interface NotificationsCreateInput {
  notificationId: string;
  recipientUserId: string;
  senderUserId?: string;
  type: NotificationType;
  status: NotificationStatus;
  title: string;
  message: string;
  metadata?: Record<string, any>;
  expiresAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface NotificationsUpdateInput {
  notificationId?: string;
  recipientUserId?: string;
  senderUserId?: string;
  type?: NotificationType;
  status?: NotificationStatus;
  title?: string;
  message?: string;
  metadata?: Record<string, any>;
  expiresAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface NotificationsQueryByNotificationIdInput {
  notificationId: string;
}

export interface NotificationsQueryByRecipientUserIdInput {
  recipientUserId: string;
}

export interface NotificationsQueryByTypeInput {
  type: string;
}


// Response Types
export interface NotificationsResponse {
  StatusCode: number;
  Message: string;
  Data: Notifications | null;
}

export interface NotificationsCreateResponse {
  StatusCode: number;
  Message: string;
  Data: Notifications | null;
}

export interface NotificationsUpdateResponse {
  StatusCode: number;
  Message: string;
  Data: Notifications | null;
}

export interface NotificationsListResponse {
  StatusCode: number;
  Message: string;
  Data: Notifications[] | null;
}


// GraphQL Response Wrappers
export interface NotificationsCreateMutationResponse {
  NotificationsCreate: NotificationsCreateResponse;
}

export interface NotificationsUpdateMutationResponse {
  NotificationsUpdate: NotificationsUpdateResponse;
}

export interface NotificationsDeleteMutationResponse {
  NotificationsDelete: NotificationsResponse;
}

export interface NotificationsQueryByNotificationIdResponse {
  NotificationsQueryByNotificationId: NotificationsResponse;
}

export interface NotificationsQueryByRecipientUserIdResponse {
  NotificationsQueryByRecipientUserId: NotificationsListResponse;
}

export interface NotificationsQueryByTypeResponse {
  NotificationsQueryByType: NotificationsListResponse;
}

export interface INotifications {
  notificationId: string;
  recipientUserId: string;
  senderUserId?: string;
  type: NotificationType;
  status: NotificationStatus;
  title: string;
  message: string;
  metadata?: Record<string, any>;
  expiresAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export class Notifications implements INotifications {
  notificationId: string;
  recipientUserId: string;
  senderUserId?: string;
  type: NotificationType;
  status: NotificationStatus;
  title: string;
  message: string;
  metadata?: Record<string, any>;
  expiresAt?: Date;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<INotifications> = {}) {
    this.notificationId = data.notificationId ?? '';
    this.recipientUserId = data.recipientUserId ?? '';
    this.senderUserId = data.senderUserId;
    this.type = data.type ?? NotificationType.APPLICATION_TRANSFER_REQUEST;
    this.status = data.status ?? NotificationStatus.PENDING;
    this.title = data.title ?? '';
    this.message = data.message ?? '';
    this.metadata = data.metadata;
    this.expiresAt = data.expiresAt;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
  }
}