// AUTO-GENERATED by orb-schema-generator v0.19.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for Notifications
 */

import { NotificationStatus } from '../../core/enums/NotificationStatusEnum';
import { NotificationType } from '../../core/enums/NotificationTypeEnum';

// Input Types
export type NotificationsCreateInput = {
  notificationId: string;
  recipientUserId: string;
  senderUserId?: string;
  type: NotificationType;
  status: NotificationStatus;
  title: string;
  message: string;
  metadata?: Record<string, unknown>;
  expiresAt?: Date;
  createdAt: Date;
  updatedAt: Date;
};

export type NotificationsUpdateInput = {
  notificationId?: string;
  recipientUserId?: string;
  senderUserId?: string;
  type?: NotificationType;
  status?: NotificationStatus;
  title?: string;
  message?: string;
  metadata?: Record<string, unknown>;
  expiresAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
};

export type NotificationsQueryByNotificationIdInput = {
  notificationId: string;
};

export type NotificationsQueryByRecipientUserIdInput = {
  recipientUserId: string;
};

export type NotificationsQueryByTypeInput = {
  type: string;
};


// Response Types
export type NotificationsCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Notifications;
};

export type NotificationsUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Notifications;
};

export type NotificationsDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Notifications;
};

export type NotificationsDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Notifications;
};

export type NotificationsGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Notifications;
};

export type NotificationsListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: Notifications[];
  nextToken?: string;
};


// GraphQL Response Wrappers
export type NotificationsCreateMutationResponse = {
  NotificationsCreate: NotificationsCreateResponse;
};

export type NotificationsUpdateMutationResponse = {
  NotificationsUpdate: NotificationsUpdateResponse;
};

export type NotificationsDeleteMutationResponse = {
  NotificationsDelete: NotificationsDeleteResponse;
};

export type NotificationsDisableMutationResponse = {
  NotificationsDisable: NotificationsDisableResponse;
};

export type NotificationsGetQueryResponse = {
  NotificationsGet: NotificationsGetResponse;
};

export type NotificationsListByNotificationIdResponse = {
  NotificationsListByNotificationId: NotificationsListResponse;
};

export type NotificationsListByRecipientUserIdResponse = {
  NotificationsListByRecipientUserId: NotificationsListResponse;
};

export type NotificationsListByTypeResponse = {
  NotificationsListByType: NotificationsListResponse;
};

export interface INotifications {
  notificationId: string;
  recipientUserId: string;
  senderUserId?: string;
  type: NotificationType;
  status: NotificationStatus;
  title: string;
  message: string;
  metadata?: Record<string, unknown>;
  expiresAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export class Notifications implements INotifications {
  notificationId: string;
  recipientUserId: string;
  senderUserId?: string;
  type: NotificationType;
  status: NotificationStatus;
  title: string;
  message: string;
  metadata?: Record<string, unknown>;
  expiresAt?: Date;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<INotifications> = {}) {
    this.notificationId = data.notificationId ?? '';
    this.recipientUserId = data.recipientUserId ?? '';
    this.senderUserId = data.senderUserId;
    this.type = data.type ?? NotificationType.ApplicationTransferRequest;
    this.status = data.status ?? NotificationStatus.Pending;
    this.title = data.title ?? '';
    this.message = data.message ?? '';
    this.metadata = data.metadata;
    this.expiresAt = data.expiresAt;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
  }
}