// AUTO-GENERATED by orb-schema-generator v3.2.7 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for NotificationType
 */


// Response Types
export type NotificationTypeCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: NotificationType;
};

export type NotificationTypeUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: NotificationType;
};

export type NotificationTypeDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: NotificationType;
};

export type NotificationTypeDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: NotificationType;
};

export type NotificationTypeGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: NotificationType;
};

export type NotificationTypeListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: NotificationType[];
  nextToken?: string;
};

export interface INotificationType {
  value: string;
}

export class NotificationType implements INotificationType {
  value: string;

  constructor(data: Partial<INotificationType> = {}) {
    this.value = data.value ?? '';
  }
}