// AUTO-GENERATED by orb-schema-generator v0.13.5 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for Notifications
 */

import { NotificationStatus } from '../../core/enums/NotificationStatusEnum';
import { NotificationType } from '../../core/enums/NotificationTypeEnum';

// Input Types
export type NotificationsCreateInput = {
  notificationId: string;
  recipientUserId: string;
  senderUserId?: string;
  type: NotificationType;
  status: NotificationStatus;
  title: string;
  message: string;
  metadata?: Record<string, any>;
  expiresAt?: Date;
  createdAt: Date;
  updatedAt: Date;
};

export type NotificationsUpdateInput = {
  notificationId?: string;
  recipientUserId?: string;
  senderUserId?: string;
  type?: NotificationType;
  status?: NotificationStatus;
  title?: string;
  message?: string;
  metadata?: Record<string, any>;
  expiresAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
};

export type NotificationsQueryByNotificationIdInput = {
  notificationId: string;
};

export type NotificationsQueryByRecipientUserIdInput = {
  recipientUserId: string;
};

export type NotificationsQueryByTypeInput = {
  type: string;
};


// Response Types
export type NotificationsResponse = {
  StatusCode: number;
  Message: string;
  Data: Notifications | null;
};

export type NotificationsCreateResponse = {
  StatusCode: number;
  Message: string;
  Data: Notifications | null;
};

export type NotificationsUpdateResponse = {
  StatusCode: number;
  Message: string;
  Data: Notifications | null;
};

export type NotificationsListResponse = {
  StatusCode: number;
  Message: string;
  Data: Notifications[] | null;
};


// GraphQL Response Wrappers
export type NotificationsCreateMutationResponse = {
  NotificationsCreate: NotificationsCreateResponse;
};

export type NotificationsUpdateMutationResponse = {
  NotificationsUpdate: NotificationsUpdateResponse;
};

export type NotificationsDeleteMutationResponse = {
  NotificationsDelete: NotificationsResponse;
};

export type NotificationsQueryByNotificationIdResponse = {
  NotificationsQueryByNotificationId: NotificationsResponse;
};

export type NotificationsQueryByRecipientUserIdResponse = {
  NotificationsQueryByRecipientUserId: NotificationsListResponse;
};

export type NotificationsQueryByTypeResponse = {
  NotificationsQueryByType: NotificationsListResponse;
};

export interface INotifications {
  notificationId: string;
  recipientUserId: string;
  senderUserId?: string;
  type: NotificationType;
  status: NotificationStatus;
  title: string;
  message: string;
  metadata?: Record<string, any>;
  expiresAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export class Notifications implements INotifications {
  notificationId: string;
  recipientUserId: string;
  senderUserId?: string;
  type: NotificationType;
  status: NotificationStatus;
  title: string;
  message: string;
  metadata?: Record<string, any>;
  expiresAt?: Date;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<INotifications> = {}) {
    this.notificationId = data.notificationId ?? '';
    this.recipientUserId = data.recipientUserId ?? '';
    this.senderUserId = data.senderUserId;
    this.type = data.type ?? NotificationType.APPLICATION_TRANSFER_REQUEST;
    this.status = data.status ?? NotificationStatus.PENDING;
    this.title = data.title ?? '';
    this.message = data.message ?? '';
    this.metadata = data.metadata;
    this.expiresAt = data.expiresAt;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
  }
}