// AUTO-GENERATED by orb-schema-generator v0.18.1 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for Organizations
 */

import { OrganizationStatus } from '../../core/enums/OrganizationStatusEnum';

// Input Types
export type OrganizationsCreateInput = {
  organizationId: string;
  name: string;
  description?: string;
  ownerId: string;
  status: OrganizationStatus;
  createdAt: Date;
  updatedAt: Date;
  kmsKeyId?: string;
  kmsKeyArn?: string;
  kmsAlias?: string;
};

export type OrganizationsUpdateInput = {
  organizationId?: string;
  name?: string;
  description?: string;
  ownerId?: string;
  status?: OrganizationStatus;
  createdAt?: Date;
  updatedAt?: Date;
  kmsKeyId?: string;
  kmsKeyArn?: string;
  kmsAlias?: string;
};

export type OrganizationsQueryByOrganizationIdInput = {
  organizationId: string;
};

export type OrganizationsQueryByOwnerIdInput = {
  ownerId: string;
};

export type OrganizationsQueryByStatusInput = {
  status: string;
};


// Response Types
export type OrganizationsResponse = {
  StatusCode: number;
  Message: string;
  Data: Organizations | null;
};

export type OrganizationsCreateResponse = {
  StatusCode: number;
  Message: string;
  Data: Organizations | null;
};

export type OrganizationsUpdateResponse = {
  StatusCode: number;
  Message: string;
  Data: Organizations | null;
};

export type OrganizationsListResponse = {
  StatusCode: number;
  Message: string;
  Data: Organizations[] | null;
};


// GraphQL Response Wrappers
export type OrganizationsCreateMutationResponse = {
  OrganizationsCreate: OrganizationsCreateResponse;
};

export type OrganizationsUpdateMutationResponse = {
  OrganizationsUpdate: OrganizationsUpdateResponse;
};

export type OrganizationsDeleteMutationResponse = {
  OrganizationsDelete: OrganizationsResponse;
};

export type OrganizationsQueryByOrganizationIdResponse = {
  OrganizationsQueryByOrganizationId: OrganizationsResponse;
};

export type OrganizationsQueryByOwnerIdResponse = {
  OrganizationsQueryByOwnerId: OrganizationsListResponse;
};

export type OrganizationsQueryByStatusResponse = {
  OrganizationsQueryByStatus: OrganizationsListResponse;
};

export interface IOrganizations {
  organizationId: string;
  name: string;
  description?: string;
  ownerId: string;
  status: OrganizationStatus;
  createdAt: Date;
  updatedAt: Date;
  kmsKeyId?: string;
  kmsKeyArn?: string;
  kmsAlias?: string;
}

export class Organizations implements IOrganizations {
  organizationId: string;
  name: string;
  description?: string;
  ownerId: string;
  status: OrganizationStatus;
  createdAt: Date;
  updatedAt: Date;
  kmsKeyId?: string;
  kmsKeyArn?: string;
  kmsAlias?: string;

  constructor(data: Partial<IOrganizations> = {}) {
    this.organizationId = data.organizationId ?? '';
    this.name = data.name ?? '';
    this.description = data.description;
    this.ownerId = data.ownerId ?? '';
    this.status = data.status ?? OrganizationStatus.Unknown;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
    this.kmsKeyId = data.kmsKeyId;
    this.kmsKeyArn = data.kmsKeyArn;
    this.kmsAlias = data.kmsAlias;
  }
}