// AUTO-GENERATED by orb-schema-generator v0.13.5 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for Organizations
 */

import { OrganizationStatus } from '../../core/enums/OrganizationStatusEnum';

// Input Types
export interface OrganizationsCreateInput {
  organizationId: string;
  name: string;
  description?: string;
  ownerId: string;
  status: OrganizationStatus;
  createdAt: Date;
  updatedAt: Date;
  kmsKeyId?: string;
  kmsKeyArn?: string;
  kmsAlias?: string;
}

export interface OrganizationsUpdateInput {
  organizationId?: string;
  name?: string;
  description?: string;
  ownerId?: string;
  status?: OrganizationStatus;
  createdAt?: Date;
  updatedAt?: Date;
  kmsKeyId?: string;
  kmsKeyArn?: string;
  kmsAlias?: string;
}

export interface OrganizationsQueryByOrganizationIdInput {
  organizationId: string;
}

export interface OrganizationsQueryByOwnerIdInput {
  ownerId: string;
}

export interface OrganizationsQueryByStatusInput {
  status: string;
}


// Response Types
export interface OrganizationsResponse {
  StatusCode: number;
  Message: string;
  Data: Organizations | null;
}

export interface OrganizationsCreateResponse {
  StatusCode: number;
  Message: string;
  Data: Organizations | null;
}

export interface OrganizationsUpdateResponse {
  StatusCode: number;
  Message: string;
  Data: Organizations | null;
}

export interface OrganizationsListResponse {
  StatusCode: number;
  Message: string;
  Data: Organizations[] | null;
}


// GraphQL Response Wrappers
export interface OrganizationsCreateMutationResponse {
  OrganizationsCreate: OrganizationsCreateResponse;
}

export interface OrganizationsUpdateMutationResponse {
  OrganizationsUpdate: OrganizationsUpdateResponse;
}

export interface OrganizationsDeleteMutationResponse {
  OrganizationsDelete: OrganizationsResponse;
}

export interface OrganizationsQueryByOrganizationIdResponse {
  OrganizationsQueryByOrganizationId: OrganizationsResponse;
}

export interface OrganizationsQueryByOwnerIdResponse {
  OrganizationsQueryByOwnerId: OrganizationsListResponse;
}

export interface OrganizationsQueryByStatusResponse {
  OrganizationsQueryByStatus: OrganizationsListResponse;
}

export interface IOrganizations {
  organizationId: string;
  name: string;
  description?: string;
  ownerId: string;
  status: OrganizationStatus;
  createdAt: Date;
  updatedAt: Date;
  kmsKeyId?: string;
  kmsKeyArn?: string;
  kmsAlias?: string;
}

export class Organizations implements IOrganizations {
  organizationId: string;
  name: string;
  description?: string;
  ownerId: string;
  status: OrganizationStatus;
  createdAt: Date;
  updatedAt: Date;
  kmsKeyId?: string;
  kmsKeyArn?: string;
  kmsAlias?: string;

  constructor(data: Partial<IOrganizations> = {}) {
    this.organizationId = data.organizationId ?? '';
    this.name = data.name ?? '';
    this.description = data.description;
    this.ownerId = data.ownerId ?? '';
    this.status = data.status ?? OrganizationStatus.Unknown;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
    this.kmsKeyId = data.kmsKeyId;
    this.kmsKeyArn = data.kmsKeyArn;
    this.kmsAlias = data.kmsAlias;
  }
}