// AUTO-GENERATED by orb-schema-generator v3.2.7 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for Organizations
 */

import { OrganizationStatus } from '../../core/enums/OrganizationStatusEnum';

// Response Types
export type OrganizationsCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Organizations;
};

export type OrganizationsUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Organizations;
};

export type OrganizationsDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Organizations;
};

export type OrganizationsDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Organizations;
};

export type OrganizationsGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Organizations;
};

export type OrganizationsListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: Organizations[];
  nextToken?: string;
};

export interface IOrganizations {
  organizationId: string;
  name: string;
  description?: string;
  ownerId: string;
  status: OrganizationStatus;
  createdAt: Date;
  updatedAt: Date;
  kmsKeyId?: string;
  kmsKeyArn?: string;
  kmsAlias?: string;
  applicationCount?: number;
}

export class Organizations implements IOrganizations {
  organizationId: string;
  name: string;
  description?: string;
  ownerId: string;
  status: OrganizationStatus;
  createdAt: Date;
  updatedAt: Date;
  kmsKeyId?: string;
  kmsKeyArn?: string;
  kmsAlias?: string;
  applicationCount?: number;

  constructor(data: Partial<IOrganizations> = {}) {
    this.organizationId = data.organizationId ?? '';
    this.name = data.name ?? '';
    this.description = data.description;
    this.ownerId = data.ownerId ?? '';
    this.status = data.status ?? OrganizationStatus.Unknown;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
    this.kmsKeyId = data.kmsKeyId;
    this.kmsKeyArn = data.kmsKeyArn;
    this.kmsAlias = data.kmsAlias;
    this.applicationCount = data.applicationCount;
  }
}