// AUTO-GENERATED by orb-schema-generator v0.13.5 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for OrganizationUsers
 */

import { OrganizationUserRole } from '../../core/enums/OrganizationUserRoleEnum';
import { OrganizationUserStatus } from '../../core/enums/OrganizationUserStatusEnum';

// Input Types
export type OrganizationUsersCreateInput = {
  userId: string;
  organizationId: string;
  role: OrganizationUserRole;
  status: OrganizationUserStatus;
  invitedBy?: string;
  invitedAt?: Date;
  joinedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
};

export type OrganizationUsersUpdateInput = {
  userId?: string;
  organizationId?: string;
  role?: OrganizationUserRole;
  status?: OrganizationUserStatus;
  invitedBy?: string;
  invitedAt?: Date;
  joinedAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
};

export type OrganizationUsersQueryByUserIdInput = {
  userId: string;
};

export type OrganizationUsersQueryByOrganizationIdInput = {
  organizationId: string;
};

export type OrganizationUsersQueryByBothInput = {
  userId: string;
  organizationId: string;
};

export type OrganizationUsersQueryByOrganizationIdInput = {
  organizationId: string;
};

export type OrganizationUsersQueryByUserIdInput = {
  userId: string;
};


// Response Types
export type OrganizationUsersResponse = {
  StatusCode: number;
  Message: string;
  Data: OrganizationUsers | null;
};

export type OrganizationUsersCreateResponse = {
  StatusCode: number;
  Message: string;
  Data: OrganizationUsers | null;
};

export type OrganizationUsersUpdateResponse = {
  StatusCode: number;
  Message: string;
  Data: OrganizationUsers | null;
};

export type OrganizationUsersListResponse = {
  StatusCode: number;
  Message: string;
  Data: OrganizationUsers[] | null;
};


// GraphQL Response Wrappers
export type OrganizationUsersCreateMutationResponse = {
  OrganizationUsersCreate: OrganizationUsersCreateResponse;
};

export type OrganizationUsersUpdateMutationResponse = {
  OrganizationUsersUpdate: OrganizationUsersUpdateResponse;
};

export type OrganizationUsersDeleteMutationResponse = {
  OrganizationUsersDelete: OrganizationUsersResponse;
};

export type OrganizationUsersQueryByUserIdResponse = {
  OrganizationUsersQueryByUserId: OrganizationUsersResponse;
};

export type OrganizationUsersQueryByOrganizationIdResponse = {
  OrganizationUsersQueryByOrganizationId: OrganizationUsersListResponse;
};

export type OrganizationUsersQueryByUserIdResponse = {
  OrganizationUsersQueryByUserId: OrganizationUsersListResponse;
};

export interface IOrganizationUsers {
  userId: string;
  organizationId: string;
  role: OrganizationUserRole;
  status: OrganizationUserStatus;
  invitedBy?: string;
  invitedAt?: Date;
  joinedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export class OrganizationUsers implements IOrganizationUsers {
  userId: string;
  organizationId: string;
  role: OrganizationUserRole;
  status: OrganizationUserStatus;
  invitedBy?: string;
  invitedAt?: Date;
  joinedAt?: Date;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<IOrganizationUsers> = {}) {
    this.userId = data.userId ?? '';
    this.organizationId = data.organizationId ?? '';
    this.role = data.role ?? OrganizationUserRole.UNKNOWN;
    this.status = data.status ?? OrganizationUserStatus.UNKNOWN;
    this.invitedBy = data.invitedBy;
    this.invitedAt = data.invitedAt;
    this.joinedAt = data.joinedAt;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
  }
}