// AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for OrganizationStatus
 */


// Response Types
export type OrganizationStatusCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OrganizationStatus;
};

export type OrganizationStatusUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OrganizationStatus;
};

export type OrganizationStatusDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OrganizationStatus;
};

export type OrganizationStatusDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OrganizationStatus;
};

export type OrganizationStatusGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OrganizationStatus;
};

export type OrganizationStatusListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: OrganizationStatus[];
  nextToken?: string;
};

export interface IOrganizationStatus {
  value: string;
}

export class OrganizationStatus implements IOrganizationStatus {
  value: string;

  constructor(data: Partial<IOrganizationStatus> = {}) {
    this.value = data.value ?? '';
  }
}