// AUTO-GENERATED by orb-schema-generator v2.0.3 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for OrganizationUsers
 */

import { OrganizationUserRole } from '../../core/enums/OrganizationUserRoleEnum';
import { OrganizationUserStatus } from '../../core/enums/OrganizationUserStatusEnum';

// Input Types
export type OrganizationUsersCreateInput = {
  userId: string;
  organizationId: string;
  role: OrganizationUserRole;
  status: OrganizationUserStatus;
  invitedBy?: string;
  invitedAt?: Date;
  joinedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
};

export type OrganizationUsersUpdateInput = {
  userId?: string;
  organizationId?: string;
  role?: OrganizationUserRole;
  status?: OrganizationUserStatus;
  invitedBy?: string;
  invitedAt?: Date;
  joinedAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
};

export type OrganizationUsersQueryByUserIdInput = {
  userId: string;
};

export type OrganizationUsersQueryByOrganizationIdInput = {
  organizationId: string;
};

export type OrganizationUsersQueryByBothInput = {
  userId: string;
  organizationId: string;
};


// Response Types
export type OrganizationUsersCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OrganizationUsers;
};

export type OrganizationUsersUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OrganizationUsers;
};

export type OrganizationUsersDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OrganizationUsers;
};

export type OrganizationUsersDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OrganizationUsers;
};

export type OrganizationUsersGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OrganizationUsers;
};

export type OrganizationUsersListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: OrganizationUsers[];
  nextToken?: string;
};


// GraphQL Response Wrappers
export type OrganizationUsersCreateMutationResponse = {
  OrganizationUsersCreate: OrganizationUsersCreateResponse;
};

export type OrganizationUsersUpdateMutationResponse = {
  OrganizationUsersUpdate: OrganizationUsersUpdateResponse;
};

export type OrganizationUsersDeleteMutationResponse = {
  OrganizationUsersDelete: OrganizationUsersDeleteResponse;
};

export type OrganizationUsersDisableMutationResponse = {
  OrganizationUsersDisable: OrganizationUsersDisableResponse;
};

export type OrganizationUsersGetQueryResponse = {
  OrganizationUsersGet: OrganizationUsersGetResponse;
};

export type OrganizationUsersListByUserIdResponse = {
  OrganizationUsersListByUserId: OrganizationUsersListResponse;
};

export type OrganizationUsersListByOrganizationIdResponse = {
  OrganizationUsersListByOrganizationId: OrganizationUsersListResponse;
};


export interface IOrganizationUsers {
  userId: string;
  organizationId: string;
  role: OrganizationUserRole;
  status: OrganizationUserStatus;
  invitedBy?: string;
  invitedAt?: Date;
  joinedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export class OrganizationUsers implements IOrganizationUsers {
  userId: string;
  organizationId: string;
  role: OrganizationUserRole;
  status: OrganizationUserStatus;
  invitedBy?: string;
  invitedAt?: Date;
  joinedAt?: Date;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<IOrganizationUsers> = {}) {
    this.userId = data.userId ?? '';
    this.organizationId = data.organizationId ?? '';
    this.role = data.role ?? OrganizationUserRole.Unknown;
    this.status = data.status ?? OrganizationUserStatus.Unknown;
    this.invitedBy = data.invitedBy;
    this.invitedAt = data.invitedAt;
    this.joinedAt = data.joinedAt;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
  }
}