// AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for OwnershipTransferRequests
 */

import { OwnershipTransferStatus } from '../../core/enums/OwnershipTransferStatusEnum';

// Response Types
export type OwnershipTransferRequestsCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OwnershipTransferRequests;
};

export type OwnershipTransferRequestsUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OwnershipTransferRequests;
};

export type OwnershipTransferRequestsDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OwnershipTransferRequests;
};

export type OwnershipTransferRequestsDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OwnershipTransferRequests;
};

export type OwnershipTransferRequestsGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OwnershipTransferRequests;
};

export type OwnershipTransferRequestsListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: OwnershipTransferRequests[];
  nextToken?: string;
};

export interface IOwnershipTransferRequests {
  transferId: string;
  organizationId: string;
  currentOwnerId: string;
  newOwnerId: string;
  status: OwnershipTransferStatus;
  reason?: string;
  expiresAt: string;
  completedAt?: string;
  cancelledAt?: string;
  createdAt: string;
  updatedAt: string;
}

export class OwnershipTransferRequests implements IOwnershipTransferRequests {
  transferId: string;
  organizationId: string;
  currentOwnerId: string;
  newOwnerId: string;
  status: OwnershipTransferStatus;
  reason?: string;
  expiresAt: string;
  completedAt?: string;
  cancelledAt?: string;
  createdAt: string;
  updatedAt: string;

  constructor(data: Partial<IOwnershipTransferRequests> = {}) {
    this.transferId = data.transferId ?? '';
    this.organizationId = data.organizationId ?? '';
    this.currentOwnerId = data.currentOwnerId ?? '';
    this.newOwnerId = data.newOwnerId ?? '';
    this.status = data.status ?? OwnershipTransferStatus.Unknown;
    this.reason = data.reason;
    this.expiresAt = data.expiresAt ?? '';
    this.completedAt = data.completedAt;
    this.cancelledAt = data.cancelledAt;
    this.createdAt = data.createdAt ?? '';
    this.updatedAt = data.updatedAt ?? '';
  }
}