// AUTO-GENERATED by orb-schema-generator v0.19.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for OwnershipTransferRequests
 */

import { OwnershipTransferStatus } from '../../core/enums/OwnershipTransferStatusEnum';

// Input Types
export type OwnershipTransferRequestsCreateInput = {
  transferId: string;
  organizationId: string;
  currentOwnerId: string;
  newOwnerId: string;
  status: OwnershipTransferStatus;
  reason?: string;
  expiresAt: string;
  completedAt?: string;
  cancelledAt?: string;
  createdAt: string;
  updatedAt: string;
};

export type OwnershipTransferRequestsUpdateInput = {
  transferId?: string;
  organizationId?: string;
  currentOwnerId?: string;
  newOwnerId?: string;
  status?: OwnershipTransferStatus;
  reason?: string;
  expiresAt?: string;
  completedAt?: string;
  cancelledAt?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type OwnershipTransferRequestsQueryByTransferIdInput = {
  transferId: string;
};

export type OwnershipTransferRequestsQueryByCurrentOwnerIdInput = {
  currentOwnerId: string;
};

export type OwnershipTransferRequestsQueryByNewOwnerIdInput = {
  newOwnerId: string;
};

export type OwnershipTransferRequestsQueryByStatusInput = {
  status: string;
};

export type OwnershipTransferRequestsQueryByStatusInput = {
  status: string;
};


// Response Types
export type OwnershipTransferRequestsCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OwnershipTransferRequests;
};

export type OwnershipTransferRequestsUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OwnershipTransferRequests;
};

export type OwnershipTransferRequestsDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OwnershipTransferRequests;
};

export type OwnershipTransferRequestsDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OwnershipTransferRequests;
};

export type OwnershipTransferRequestsGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: OwnershipTransferRequests;
};

export type OwnershipTransferRequestsListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: OwnershipTransferRequests[];
  nextToken?: string;
};


// GraphQL Response Wrappers
export type OwnershipTransferRequestsCreateMutationResponse = {
  OwnershipTransferRequestsCreate: OwnershipTransferRequestsCreateResponse;
};

export type OwnershipTransferRequestsUpdateMutationResponse = {
  OwnershipTransferRequestsUpdate: OwnershipTransferRequestsUpdateResponse;
};

export type OwnershipTransferRequestsDeleteMutationResponse = {
  OwnershipTransferRequestsDelete: OwnershipTransferRequestsDeleteResponse;
};

export type OwnershipTransferRequestsDisableMutationResponse = {
  OwnershipTransferRequestsDisable: OwnershipTransferRequestsDisableResponse;
};

export type OwnershipTransferRequestsGetQueryResponse = {
  OwnershipTransferRequestsGet: OwnershipTransferRequestsGetResponse;
};

export type OwnershipTransferRequestsListByTransferIdResponse = {
  OwnershipTransferRequestsListByTransferId: OwnershipTransferRequestsListResponse;
};

export type OwnershipTransferRequestsListByCurrentOwnerIdResponse = {
  OwnershipTransferRequestsListByCurrentOwnerId: OwnershipTransferRequestsListResponse;
};

export type OwnershipTransferRequestsListByNewOwnerIdResponse = {
  OwnershipTransferRequestsListByNewOwnerId: OwnershipTransferRequestsListResponse;
};

export type OwnershipTransferRequestsListByStatusResponse = {
  OwnershipTransferRequestsListByStatus: OwnershipTransferRequestsListResponse;
};

export type OwnershipTransferRequestsListByStatusResponse = {
  OwnershipTransferRequestsListByStatus: OwnershipTransferRequestsListResponse;
};

export interface IOwnershipTransferRequests {
  transferId: string;
  organizationId: string;
  currentOwnerId: string;
  newOwnerId: string;
  status: OwnershipTransferStatus;
  reason?: string;
  expiresAt: string;
  completedAt?: string;
  cancelledAt?: string;
  createdAt: string;
  updatedAt: string;
}

export class OwnershipTransferRequests implements IOwnershipTransferRequests {
  transferId: string;
  organizationId: string;
  currentOwnerId: string;
  newOwnerId: string;
  status: OwnershipTransferStatus;
  reason?: string;
  expiresAt: string;
  completedAt?: string;
  cancelledAt?: string;
  createdAt: string;
  updatedAt: string;

  constructor(data: Partial<IOwnershipTransferRequests> = {}) {
    this.transferId = data.transferId ?? '';
    this.organizationId = data.organizationId ?? '';
    this.currentOwnerId = data.currentOwnerId ?? '';
    this.newOwnerId = data.newOwnerId ?? '';
    this.status = data.status ?? OwnershipTransferStatus.Unknown;
    this.reason = data.reason;
    this.expiresAt = data.expiresAt ?? '';
    this.completedAt = data.completedAt;
    this.cancelledAt = data.cancelledAt;
    this.createdAt = data.createdAt ?? '';
    this.updatedAt = data.updatedAt ?? '';
  }
}