// AUTO-GENERATED by orb-schema-generator v0.13.5 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for OwnershipTransferRequests
 */

import { OwnershipTransferStatus } from '../../core/enums/OwnershipTransferStatusEnum';

// Input Types
export interface OwnershipTransferRequestsCreateInput {
  transferId: string;
  organizationId: string;
  currentOwnerId: string;
  newOwnerId: string;
  status: OwnershipTransferStatus;
  reason?: string;
  expiresAt: string;
  completedAt?: string;
  cancelledAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface OwnershipTransferRequestsUpdateInput {
  transferId?: string;
  organizationId?: string;
  currentOwnerId?: string;
  newOwnerId?: string;
  status?: OwnershipTransferStatus;
  reason?: string;
  expiresAt?: string;
  completedAt?: string;
  cancelledAt?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface OwnershipTransferRequestsQueryByTransferIdInput {
  transferId: string;
}

export interface OwnershipTransferRequestsQueryByCurrentOwnerIdInput {
  currentOwnerId: string;
}

export interface OwnershipTransferRequestsQueryByNewOwnerIdInput {
  newOwnerId: string;
}

export interface OwnershipTransferRequestsQueryByStatusInput {
  status: string;
}

export interface OwnershipTransferRequestsQueryByStatusInput {
  status: string;
}


// Response Types
export interface OwnershipTransferRequestsResponse {
  StatusCode: number;
  Message: string;
  Data: OwnershipTransferRequests | null;
}

export interface OwnershipTransferRequestsCreateResponse {
  StatusCode: number;
  Message: string;
  Data: OwnershipTransferRequests | null;
}

export interface OwnershipTransferRequestsUpdateResponse {
  StatusCode: number;
  Message: string;
  Data: OwnershipTransferRequests | null;
}

export interface OwnershipTransferRequestsListResponse {
  StatusCode: number;
  Message: string;
  Data: OwnershipTransferRequests[] | null;
}


// GraphQL Response Wrappers
export interface OwnershipTransferRequestsCreateMutationResponse {
  OwnershipTransferRequestsCreate: OwnershipTransferRequestsCreateResponse;
}

export interface OwnershipTransferRequestsUpdateMutationResponse {
  OwnershipTransferRequestsUpdate: OwnershipTransferRequestsUpdateResponse;
}

export interface OwnershipTransferRequestsDeleteMutationResponse {
  OwnershipTransferRequestsDelete: OwnershipTransferRequestsResponse;
}

export interface OwnershipTransferRequestsQueryByTransferIdResponse {
  OwnershipTransferRequestsQueryByTransferId: OwnershipTransferRequestsResponse;
}

export interface OwnershipTransferRequestsQueryByCurrentOwnerIdResponse {
  OwnershipTransferRequestsQueryByCurrentOwnerId: OwnershipTransferRequestsListResponse;
}

export interface OwnershipTransferRequestsQueryByNewOwnerIdResponse {
  OwnershipTransferRequestsQueryByNewOwnerId: OwnershipTransferRequestsListResponse;
}

export interface OwnershipTransferRequestsQueryByStatusResponse {
  OwnershipTransferRequestsQueryByStatus: OwnershipTransferRequestsListResponse;
}

export interface OwnershipTransferRequestsQueryByStatusResponse {
  OwnershipTransferRequestsQueryByStatus: OwnershipTransferRequestsListResponse;
}

export interface IOwnershipTransferRequests {
  transferId: string;
  organizationId: string;
  currentOwnerId: string;
  newOwnerId: string;
  status: OwnershipTransferStatus;
  reason?: string;
  expiresAt: string;
  completedAt?: string;
  cancelledAt?: string;
  createdAt: string;
  updatedAt: string;
}

export class OwnershipTransferRequests implements IOwnershipTransferRequests {
  transferId: string;
  organizationId: string;
  currentOwnerId: string;
  newOwnerId: string;
  status: OwnershipTransferStatus;
  reason?: string;
  expiresAt: string;
  completedAt?: string;
  cancelledAt?: string;
  createdAt: string;
  updatedAt: string;

  constructor(data: Partial<IOwnershipTransferRequests> = {}) {
    this.transferId = data.transferId ?? '';
    this.organizationId = data.organizationId ?? '';
    this.currentOwnerId = data.currentOwnerId ?? '';
    this.newOwnerId = data.newOwnerId ?? '';
    this.status = data.status ?? OwnershipTransferStatus.UNKNOWN;
    this.reason = data.reason;
    this.expiresAt = data.expiresAt ?? '';
    this.completedAt = data.completedAt;
    this.cancelledAt = data.cancelledAt;
    this.createdAt = data.createdAt ?? '';
    this.updatedAt = data.updatedAt ?? '';
  }
}