// AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for PrivacyRequestType
 */


// Response Types
export type PrivacyRequestTypeCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: PrivacyRequestType;
};

export type PrivacyRequestTypeUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: PrivacyRequestType;
};

export type PrivacyRequestTypeDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: PrivacyRequestType;
};

export type PrivacyRequestTypeDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: PrivacyRequestType;
};

export type PrivacyRequestTypeGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: PrivacyRequestType;
};

export type PrivacyRequestTypeListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: PrivacyRequestType[];
  nextToken?: string;
};

export interface IPrivacyRequestType {
  value: string;
}

export class PrivacyRequestType implements IPrivacyRequestType {
  value: string;

  constructor(data: Partial<IPrivacyRequestType> = {}) {
    this.value = data.value ?? '';
  }
}