// AUTO-GENERATED by orb-schema-generator v1.0.1 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for PrivacyRequests
 */

import { LegalBasis } from '../../core/enums/LegalBasisEnum';
import { PrivacyRequestStatus } from '../../core/enums/PrivacyRequestStatusEnum';
import { PrivacyRequestType } from '../../core/enums/PrivacyRequestTypeEnum';

// Input Types
export type PrivacyRequestsCreateInput = {
  requestId: string;
  organizationId: string;
  requestType: PrivacyRequestType;
  status: PrivacyRequestStatus;
  dataSubjectEmail: string;
  dataSubjectName?: string;
  legalBasis: LegalBasis;
  description?: string;
  receivedAt: Date;
  deadline: Date;
  completedAt?: Date;
  assignedTo?: string;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
};

export type PrivacyRequestsUpdateInput = {
  requestId?: string;
  organizationId?: string;
  requestType?: PrivacyRequestType;
  status?: PrivacyRequestStatus;
  dataSubjectEmail?: string;
  dataSubjectName?: string;
  legalBasis?: LegalBasis;
  description?: string;
  receivedAt?: Date;
  deadline?: Date;
  completedAt?: Date;
  assignedTo?: string;
  notes?: string;
  createdAt?: Date;
  updatedAt?: Date;
};

export type PrivacyRequestsQueryByRequestIdInput = {
  requestId: string;
};

export type PrivacyRequestsQueryByRequestTypeInput = {
  requestType: string;
};

export type PrivacyRequestsQueryByDataSubjectEmailInput = {
  dataSubjectEmail: string;
};

export type PrivacyRequestsQueryByOrganizationIdInput = {
  organizationId: string;
};

export type PrivacyRequestsQueryByStatusInput = {
  status: string;
};


// Response Types
export type PrivacyRequestsCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: PrivacyRequests;
};

export type PrivacyRequestsUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: PrivacyRequests;
};

export type PrivacyRequestsDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: PrivacyRequests;
};

export type PrivacyRequestsDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: PrivacyRequests;
};

export type PrivacyRequestsGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: PrivacyRequests;
};

export type PrivacyRequestsListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: PrivacyRequests[];
  nextToken?: string;
};


// GraphQL Response Wrappers
export type PrivacyRequestsCreateMutationResponse = {
  PrivacyRequestsCreate: PrivacyRequestsCreateResponse;
};

export type PrivacyRequestsUpdateMutationResponse = {
  PrivacyRequestsUpdate: PrivacyRequestsUpdateResponse;
};

export type PrivacyRequestsDeleteMutationResponse = {
  PrivacyRequestsDelete: PrivacyRequestsDeleteResponse;
};

export type PrivacyRequestsDisableMutationResponse = {
  PrivacyRequestsDisable: PrivacyRequestsDisableResponse;
};

export type PrivacyRequestsGetQueryResponse = {
  PrivacyRequestsGet: PrivacyRequestsGetResponse;
};

export type PrivacyRequestsListByRequestIdResponse = {
  PrivacyRequestsListByRequestId: PrivacyRequestsListResponse;
};

export type PrivacyRequestsListByRequestTypeResponse = {
  PrivacyRequestsListByRequestType: PrivacyRequestsListResponse;
};

export type PrivacyRequestsListByDataSubjectEmailResponse = {
  PrivacyRequestsListByDataSubjectEmail: PrivacyRequestsListResponse;
};

export type PrivacyRequestsListByOrganizationIdResponse = {
  PrivacyRequestsListByOrganizationId: PrivacyRequestsListResponse;
};

export type PrivacyRequestsListByStatusResponse = {
  PrivacyRequestsListByStatus: PrivacyRequestsListResponse;
};


export interface IPrivacyRequests {
  requestId: string;
  organizationId: string;
  requestType: PrivacyRequestType;
  status: PrivacyRequestStatus;
  dataSubjectEmail: string;
  dataSubjectName?: string;
  legalBasis: LegalBasis;
  description?: string;
  receivedAt: Date;
  deadline: Date;
  completedAt?: Date;
  assignedTo?: string;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

export class PrivacyRequests implements IPrivacyRequests {
  requestId: string;
  organizationId: string;
  requestType: PrivacyRequestType;
  status: PrivacyRequestStatus;
  dataSubjectEmail: string;
  dataSubjectName?: string;
  legalBasis: LegalBasis;
  description?: string;
  receivedAt: Date;
  deadline: Date;
  completedAt?: Date;
  assignedTo?: string;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<IPrivacyRequests> = {}) {
    this.requestId = data.requestId ?? '';
    this.organizationId = data.organizationId ?? '';
    this.requestType = data.requestType ?? PrivacyRequestType.Unknown;
    this.status = data.status ?? PrivacyRequestStatus.Unknown;
    this.dataSubjectEmail = data.dataSubjectEmail ?? '';
    this.dataSubjectName = data.dataSubjectName;
    this.legalBasis = data.legalBasis ?? LegalBasis.Unknown;
    this.description = data.description;
    this.receivedAt = data.receivedAt ?? new Date();
    this.deadline = data.deadline ?? new Date();
    this.completedAt = data.completedAt;
    this.assignedTo = data.assignedTo;
    this.notes = data.notes;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
  }
}