// AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for PrivacyRequests
 */

import { LegalBasis } from '../../core/enums/LegalBasisEnum';
import { PrivacyRequestStatus } from '../../core/enums/PrivacyRequestStatusEnum';
import { PrivacyRequestType } from '../../core/enums/PrivacyRequestTypeEnum';

// Response Types
export type PrivacyRequestsCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: PrivacyRequests;
};

export type PrivacyRequestsUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: PrivacyRequests;
};

export type PrivacyRequestsDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: PrivacyRequests;
};

export type PrivacyRequestsDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: PrivacyRequests;
};

export type PrivacyRequestsGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: PrivacyRequests;
};

export type PrivacyRequestsListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: PrivacyRequests[];
  nextToken?: string;
};

export interface IPrivacyRequests {
  requestId: string;
  organizationId: string;
  requestType: PrivacyRequestType;
  status: PrivacyRequestStatus;
  dataSubjectEmail: string;
  dataSubjectName?: string;
  legalBasis: LegalBasis;
  description?: string;
  receivedAt: Date;
  deadline: Date;
  completedAt?: Date;
  assignedTo?: string;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

export class PrivacyRequests implements IPrivacyRequests {
  requestId: string;
  organizationId: string;
  requestType: PrivacyRequestType;
  status: PrivacyRequestStatus;
  dataSubjectEmail: string;
  dataSubjectName?: string;
  legalBasis: LegalBasis;
  description?: string;
  receivedAt: Date;
  deadline: Date;
  completedAt?: Date;
  assignedTo?: string;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<IPrivacyRequests> = {}) {
    this.requestId = data.requestId ?? '';
    this.organizationId = data.organizationId ?? '';
    this.requestType = data.requestType ?? PrivacyRequestType.Unknown;
    this.status = data.status ?? PrivacyRequestStatus.Unknown;
    this.dataSubjectEmail = data.dataSubjectEmail ?? '';
    this.dataSubjectName = data.dataSubjectName;
    this.legalBasis = data.legalBasis ?? LegalBasis.Unknown;
    this.description = data.description;
    this.receivedAt = data.receivedAt ?? new Date();
    this.deadline = data.deadline ?? new Date();
    this.completedAt = data.completedAt;
    this.assignedTo = data.assignedTo;
    this.notes = data.notes;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
  }
}