// AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for ProfileSetupStep
 */


// Response Types
export type ProfileSetupStepCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ProfileSetupStep;
};

export type ProfileSetupStepUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ProfileSetupStep;
};

export type ProfileSetupStepDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ProfileSetupStep;
};

export type ProfileSetupStepDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ProfileSetupStep;
};

export type ProfileSetupStepGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: ProfileSetupStep;
};

export type ProfileSetupStepListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: ProfileSetupStep[];
  nextToken?: string;
};

export interface IProfileSetupStep {
  value: string;
}

export class ProfileSetupStep implements IProfileSetupStep {
  value: string;

  constructor(data: Partial<IProfileSetupStep> = {}) {
    this.value = data.value ?? '';
  }
}