// AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for RecoveryAction
 */


// Response Types
export type RecoveryActionCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: RecoveryAction;
};

export type RecoveryActionUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: RecoveryAction;
};

export type RecoveryActionDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: RecoveryAction;
};

export type RecoveryActionDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: RecoveryAction;
};

export type RecoveryActionGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: RecoveryAction;
};

export type RecoveryActionListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: RecoveryAction[];
  nextToken?: string;
};

export interface IRecoveryAction {
  value: string;
}

export class RecoveryAction implements IRecoveryAction {
  value: string;

  constructor(data: Partial<IRecoveryAction> = {}) {
    this.value = data.value ?? '';
  }
}