// AUTO-GENERATED by orb-schema-generator v1.0.1 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for Roles
 */

import { RoleStatus } from '../../core/enums/RoleStatusEnum';
import { RoleType } from '../../core/enums/RoleTypeEnum';

// Input Types
export type RolesCreateInput = {
  roleId: string;
  userId?: string;
  roleType: RoleType;
  status: RoleStatus;
  createdAt: Date;
  updatedAt: Date;
};

export type RolesUpdateInput = {
  roleId?: string;
  userId?: string;
  roleType?: RoleType;
  status?: RoleStatus;
  createdAt?: Date;
  updatedAt?: Date;
};

export type RolesQueryByRoleIdInput = {
  roleId: string;
};

export type RolesQueryByUserIdInput = {
  userId: string;
};


// Response Types
export type RolesCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Roles;
};

export type RolesUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Roles;
};

export type RolesDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Roles;
};

export type RolesDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Roles;
};

export type RolesGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Roles;
};

export type RolesListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: Roles[];
  nextToken?: string;
};


// GraphQL Response Wrappers
export type RolesCreateMutationResponse = {
  RolesCreate: RolesCreateResponse;
};

export type RolesUpdateMutationResponse = {
  RolesUpdate: RolesUpdateResponse;
};

export type RolesDeleteMutationResponse = {
  RolesDelete: RolesDeleteResponse;
};

export type RolesDisableMutationResponse = {
  RolesDisable: RolesDisableResponse;
};

export type RolesGetQueryResponse = {
  RolesGet: RolesGetResponse;
};

export type RolesListByRoleIdResponse = {
  RolesListByRoleId: RolesListResponse;
};

export type RolesListByUserIdResponse = {
  RolesListByUserId: RolesListResponse;
};


export interface IRoles {
  roleId: string;
  userId?: string;
  roleType: RoleType;
  status: RoleStatus;
  createdAt: Date;
  updatedAt: Date;
}

export class Roles implements IRoles {
  roleId: string;
  userId?: string;
  roleType: RoleType;
  status: RoleStatus;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<IRoles> = {}) {
    this.roleId = data.roleId ?? '';
    this.userId = data.userId;
    this.roleType = data.roleType ?? RoleType.Unknown;
    this.status = data.status ?? RoleStatus.Unknown;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
  }
}