// AUTO-GENERATED by orb-schema-generator v0.17.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for Roles
 */

import { RoleStatus } from '../../core/enums/RoleStatusEnum';
import { RoleType } from '../../core/enums/RoleTypeEnum';

// Input Types
export type RolesCreateInput = {
  roleId: string;
  userId?: string;
  roleType: RoleType;
  status: RoleStatus;
  createdAt: Date;
  updatedAt: Date;
};

export type RolesUpdateInput = {
  roleId?: string;
  userId?: string;
  roleType?: RoleType;
  status?: RoleStatus;
  createdAt?: Date;
  updatedAt?: Date;
};

export type RolesQueryByRoleIdInput = {
  roleId: string;
};

export type RolesQueryByUserIdInput = {
  userId: string;
};


// Response Types
export type RolesResponse = {
  StatusCode: number;
  Message: string;
  Data: Roles | null;
};

export type RolesCreateResponse = {
  StatusCode: number;
  Message: string;
  Data: Roles | null;
};

export type RolesUpdateResponse = {
  StatusCode: number;
  Message: string;
  Data: Roles | null;
};

export type RolesListResponse = {
  StatusCode: number;
  Message: string;
  Data: Roles[] | null;
};


// GraphQL Response Wrappers
export type RolesCreateMutationResponse = {
  RolesCreate: RolesCreateResponse;
};

export type RolesUpdateMutationResponse = {
  RolesUpdate: RolesUpdateResponse;
};

export type RolesDeleteMutationResponse = {
  RolesDelete: RolesResponse;
};

export type RolesQueryByRoleIdResponse = {
  RolesQueryByRoleId: RolesResponse;
};

export type RolesQueryByUserIdResponse = {
  RolesQueryByUserId: RolesListResponse;
};

export interface IRoles {
  roleId: string;
  userId?: string;
  roleType: RoleType;
  status: RoleStatus;
  createdAt: Date;
  updatedAt: Date;
}

export class Roles implements IRoles {
  roleId: string;
  userId?: string;
  roleType: RoleType;
  status: RoleStatus;
  createdAt: Date;
  updatedAt: Date;

  constructor(data: Partial<IRoles> = {}) {
    this.roleId = data.roleId ?? '';
    this.userId = data.userId;
    this.roleType = data.roleType ?? RoleType.Unknown;
    this.status = data.status ?? RoleStatus.Unknown;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
  }
}