// AUTO-GENERATED by orb-schema-generator v3.2.7 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for SchemaType
 */


// Response Types
export type SchemaTypeCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: SchemaType;
};

export type SchemaTypeUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: SchemaType;
};

export type SchemaTypeDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: SchemaType;
};

export type SchemaTypeDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: SchemaType;
};

export type SchemaTypeGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: SchemaType;
};

export type SchemaTypeListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: SchemaType[];
  nextToken?: string;
};

export interface ISchemaType {
  value: string;
}

export class SchemaType implements ISchemaType {
  value: string;

  constructor(data: Partial<ISchemaType> = {}) {
    this.value = data.value ?? '';
  }
}