// AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for SmsRateLimit
 */


// Response Types
export type SmsRateLimitCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: SmsRateLimit;
};

export type SmsRateLimitUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: SmsRateLimit;
};

export type SmsRateLimitDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: SmsRateLimit;
};

export type SmsRateLimitDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: SmsRateLimit;
};

export type SmsRateLimitGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: SmsRateLimit;
};

export type SmsRateLimitListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: SmsRateLimit[];
  nextToken?: string;
};

export interface ISmsRateLimit {
  phoneNumber: string;
  requestCount: number;
  firstRequestTime: Date;
  ttl: number;
}

export class SmsRateLimit implements ISmsRateLimit {
  phoneNumber: string;
  requestCount: number;
  firstRequestTime: Date;
  ttl: number;

  constructor(data: Partial<ISmsRateLimit> = {}) {
    this.phoneNumber = data.phoneNumber ?? '';
    this.requestCount = data.requestCount ?? 0;
    this.firstRequestTime = data.firstRequestTime ?? new Date();
    this.ttl = data.ttl ?? 0;
  }
}