// AUTO-GENERATED by orb-schema-generator v3.2.10 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for UserGroup
 */


// Response Types
export type UserGroupCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: UserGroup;
};

export type UserGroupUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: UserGroup;
};

export type UserGroupDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: UserGroup;
};

export type UserGroupDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: UserGroup;
};

export type UserGroupGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: UserGroup;
};

export type UserGroupListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: UserGroup[];
  nextToken?: string;
};

export interface IUserGroup {
  value: string;
}

export class UserGroup implements IUserGroup {
  value: string;

  constructor(data: Partial<IUserGroup> = {}) {
    this.value = data.value ?? '';
  }
}