// AUTO-GENERATED by orb-schema-generator v1.1.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for Users
 */

import { UserStatus } from '../../core/enums/UserStatusEnum';

// Input Types
export type UsersCreateInput = {
  userId: string;
  cognitoId: string;
  cognitoSub: string;
  email: string;
  firstName: string;
  lastName: string;
  status: UserStatus;
  createdAt: Date;
  updatedAt: Date;
  phoneNumber?: string;
  groups?: string[];
  emailVerified?: boolean;
  phoneVerified?: boolean;
  mfaEnabled?: boolean;
  mfaSetupComplete?: boolean;
};

export type UsersUpdateInput = {
  userId?: string;
  cognitoId?: string;
  cognitoSub?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  status?: UserStatus;
  createdAt?: Date;
  updatedAt?: Date;
  phoneNumber?: string;
  groups?: string[];
  emailVerified?: boolean;
  phoneVerified?: boolean;
  mfaEnabled?: boolean;
  mfaSetupComplete?: boolean;
};

export type UsersQueryByUserIdInput = {
  userId: string;
};

export type UsersQueryByEmailInput = {
  email: string;
};

export type UsersQueryByCognitoIdInput = {
  cognitoId: string;
};

export type UsersQueryByCognitoSubInput = {
  cognitoSub: string;
};


// Response Types
export type UsersCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Users;
};

export type UsersUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Users;
};

export type UsersDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Users;
};

export type UsersDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Users;
};

export type UsersGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: Users;
};

export type UsersListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: Users[];
  nextToken?: string;
};


// GraphQL Response Wrappers
export type UsersCreateMutationResponse = {
  UsersCreate: UsersCreateResponse;
};

export type UsersUpdateMutationResponse = {
  UsersUpdate: UsersUpdateResponse;
};

export type UsersDeleteMutationResponse = {
  UsersDelete: UsersDeleteResponse;
};

export type UsersDisableMutationResponse = {
  UsersDisable: UsersDisableResponse;
};

export type UsersGetQueryResponse = {
  UsersGet: UsersGetResponse;
};

export type UsersListByUserIdResponse = {
  UsersListByUserId: UsersListResponse;
};

export type UsersListByEmailResponse = {
  UsersListByEmail: UsersListResponse;
};

export type UsersListByCognitoIdResponse = {
  UsersListByCognitoId: UsersListResponse;
};

export type UsersListByCognitoSubResponse = {
  UsersListByCognitoSub: UsersListResponse;
};


export interface IUsers {
  userId: string;
  cognitoId: string;
  cognitoSub: string;
  email: string;
  firstName: string;
  lastName: string;
  status: UserStatus;
  createdAt: Date;
  updatedAt: Date;
  phoneNumber?: string;
  groups?: string[];
  emailVerified?: boolean;
  phoneVerified?: boolean;
  mfaEnabled?: boolean;
  mfaSetupComplete?: boolean;
}

export class Users implements IUsers {
  userId: string;
  cognitoId: string;
  cognitoSub: string;
  email: string;
  firstName: string;
  lastName: string;
  status: UserStatus;
  createdAt: Date;
  updatedAt: Date;
  phoneNumber?: string;
  groups?: string[];
  emailVerified?: boolean;
  phoneVerified?: boolean;
  mfaEnabled?: boolean;
  mfaSetupComplete?: boolean;

  constructor(data: Partial<IUsers> = {}) {
    this.userId = data.userId ?? '';
    this.cognitoId = data.cognitoId ?? '';
    this.cognitoSub = data.cognitoSub ?? '';
    this.email = data.email ?? '';
    this.firstName = data.firstName ?? '';
    this.lastName = data.lastName ?? '';
    this.status = data.status ?? UserStatus.Unknown;
    this.createdAt = data.createdAt ?? new Date();
    this.updatedAt = data.updatedAt ?? new Date();
    this.phoneNumber = data.phoneNumber;
    this.groups = data.groups;
    this.emailVerified = data.emailVerified;
    this.phoneVerified = data.phoneVerified;
    this.mfaEnabled = data.mfaEnabled;
    this.mfaSetupComplete = data.mfaSetupComplete;
  }
}