// AUTO-GENERATED by orb-schema-generator v3.2.7 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Generated TypeScript models for UserWithRoles
 */


// Response Types
export type UserWithRolesCreateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: UserWithRoles;
};

export type UserWithRolesUpdateResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: UserWithRoles;
};

export type UserWithRolesDeleteResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: UserWithRoles;
};

export type UserWithRolesDisableResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: UserWithRoles;
};

export type UserWithRolesGetResponse = {
  code: number;
  success: boolean;
  message?: string;
  item?: UserWithRoles;
};

export type UserWithRolesListResponse = {
  code: number;
  success: boolean;
  message?: string;
  items?: UserWithRoles[];
  nextToken?: string;
};

export interface IUserWithRoles {
  userId: string;
  firstName: string;
  lastName: string;
  status: string;
  roleAssignments: string[];
}

export class UserWithRoles implements IUserWithRoles {
  userId: string;
  firstName: string;
  lastName: string;
  status: string;
  roleAssignments: string[];

  constructor(data: Partial<IUserWithRoles> = {}) {
    this.userId = data.userId ?? '';
    this.firstName = data.firstName ?? '';
    this.lastName = data.lastName ?? '';
    this.status = data.status ?? '';
    this.roleAssignments = data.roleAssignments ?? [];
  }
}