// AUTO-GENERATED by orb-schema-generator v2.0.3 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Application API key status
 */

export enum ApplicationApiKeyStatus {
  /** Unknown status */
  Unknown = "UNKNOWN",
  /** Active API key */
  Active = "ACTIVE",
  /** Key is being rotated (both old and new keys valid) */
  Rotating = "ROTATING",
  /** Key has been revoked and is no longer valid */
  Revoked = "REVOKED",
  /** Key has expired and is no longer valid */
  Expired = "EXPIRED",
}

/**
 * Convert ApplicationApiKeyStatus to JSON string value
 */
export function applicationapikeystatusToJson(value: ApplicationApiKeyStatus): string {
  return value as string;
}

/**
 * Create ApplicationApiKeyStatus from JSON string value
 */
export function applicationapikeystatusFromJson(json: string): ApplicationApiKeyStatus {
  const values = Object.values(ApplicationApiKeyStatus);
  const found = values.find((v) => v === json);
  if (found !== undefined) {
    return found as ApplicationApiKeyStatus;
  }
  throw new Error(`Unknown ApplicationApiKeyStatus value: ${json}`);
}