// AUTO-GENERATED by orb-schema-generator v1.3.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Application group status
 */

export enum ApplicationGroupStatus {
  /** Unknown status */
  Unknown = "UNKNOWN",
  /** Active group */
  Active = "ACTIVE",
  /** Deleted group */
  Deleted = "DELETED",
}

/**
 * Convert ApplicationGroupStatus to JSON string value
 */
export function applicationgroupstatusToJson(value: ApplicationGroupStatus): string {
  return value as string;
}

/**
 * Create ApplicationGroupStatus from JSON string value
 */
export function applicationgroupstatusFromJson(json: string): ApplicationGroupStatus {
  const values = Object.values(ApplicationGroupStatus);
  const found = values.find((v) => v === json);
  if (found !== undefined) {
    return found as ApplicationGroupStatus;
  }
  throw new Error(`Unknown ApplicationGroupStatus value: ${json}`);
}