// AUTO-GENERATED by orb-schema-generator v1.1.0 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Application group role assignment status
 */

export enum ApplicationGroupRoleStatus {
  /** Unknown status */
  Unknown = "UNKNOWN",
  /** Active role assignment */
  Active = "ACTIVE",
  /** Deleted role assignment */
  Deleted = "DELETED",
}

/**
 * Convert ApplicationGroupRoleStatus to JSON string value
 */
export function applicationgrouprolestatusToJson(value: ApplicationGroupRoleStatus): string {
  return value as string;
}

/**
 * Create ApplicationGroupRoleStatus from JSON string value
 */
export function applicationgrouprolestatusFromJson(json: string): ApplicationGroupRoleStatus {
  const values = Object.values(ApplicationGroupRoleStatus);
  const found = values.find((v) => v === json);
  if (found !== undefined) {
    return found as ApplicationGroupRoleStatus;
  }
  throw new Error(`Unknown ApplicationGroupRoleStatus value: ${json}`);
}