// AUTO-GENERATED by orb-schema-generator v0.13.3 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Status of a notification
 */

export enum NotificationStatus {
  /** Notification is pending delivery or action */
  Pending = "PENDING",
  /** Notification has been read */
  Read = "READ",
  /** Notification was dismissed by user */
  Dismissed = "DISMISSED",
  /** Notification has expired */
  Expired = "EXPIRED",
}

/**
 * Convert NotificationStatus to JSON string value
 */
export function notificationstatusToJson(value: NotificationStatus): string {
  return value as string;
}

/**
 * Create NotificationStatus from JSON string value
 */
export function notificationstatusFromJson(json: string): NotificationStatus {
  const values = Object.values(NotificationStatus);
  const found = values.find((v) => v === json);
  if (found !== undefined) {
    return found as NotificationStatus;
  }
  throw new Error(`Unknown NotificationStatus value: ${json}`);
}