// AUTO-GENERATED by orb-schema-generator v0.18.2 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Status of an ownership transfer request
 */

export enum OwnershipTransferStatus {
  /** Payment validation is required before transfer */
  PaymentValidationRequired = "PAYMENT_VALIDATION_REQUIRED",
  /** Payment is being processed */
  PaymentInProgress = "PAYMENT_IN_PROGRESS",
  /** Payment has been validated */
  PaymentValidated = "PAYMENT_VALIDATED",
  /** Transfer has been completed */
  Completed = "COMPLETED",
  /** Transfer request has expired */
  Expired = "EXPIRED",
  /** Transfer was cancelled */
  Cancelled = "CANCELLED",
}

/**
 * Convert OwnershipTransferStatus to JSON string value
 */
export function ownershiptransferstatusToJson(value: OwnershipTransferStatus): string {
  return value as string;
}

/**
 * Create OwnershipTransferStatus from JSON string value
 */
export function ownershiptransferstatusFromJson(json: string): OwnershipTransferStatus {
  const values = Object.values(OwnershipTransferStatus);
  const found = values.find((v) => v === json);
  if (found !== undefined) {
    return found as OwnershipTransferStatus;
  }
  throw new Error(`Unknown OwnershipTransferStatus value: ${json}`);
}