// AUTO-GENERATED by orb-schema-generator v1.0.1 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * Types of schemas supported by the schema generator
 */

export enum SchemaType {
  /** Standard schema type */
  Standard = "STANDARD",
  /** DynamoDB table schema */
  Dynamodb = "DYNAMODB",
  /** PostgreSQL database schema */
  Postgres = "POSTGRES",
  /** MySQL database schema */
  Mysql = "MYSQL",
  /** Microsoft SQL Server schema */
  Mssql = "MSSQL",
  /** SQLite database schema */
  Sqlite = "SQLITE",
  /** AWS Lambda function schema */
  Lambda = "LAMBDA",
  /** Secured AWS Lambda function schema */
  LambdaSecured = "LAMBDA_SECURED",
  /** GraphQL schema */
  Graphql = "GRAPHQL",
  /** Registry/enum schema */
  Registry = "REGISTRY",
  /** Graph database schema */
  Graph = "GRAPH",
  /** REST API schema */
  Rest = "REST",
  /** Elasticsearch schema */
  Elasticsearch = "ELASTICSEARCH",
}

/**
 * Convert SchemaType to JSON string value
 */
export function schematypeToJson(value: SchemaType): string {
  return value as string;
}

/**
 * Create SchemaType from JSON string value
 */
export function schematypeFromJson(json: string): SchemaType {
  const values = Object.values(SchemaType);
  const found = values.find((v) => v === json);
  if (found !== undefined) {
    return found as SchemaType;
  }
  throw new Error(`Unknown SchemaType value: ${json}`);
}