// AUTO-GENERATED by orb-schema-generator v0.18.1 - DO NOT EDIT
// Regenerate with: orb-schema generate
/**
 * User group types for Cognito authentication
 */

export enum UserGroup {
  /** Standard user */
  User = "USER",
  /** Customer user */
  Customer = "CUSTOMER",
  /** Employee user */
  Employee = "EMPLOYEE",
  /** Owner user */
  Owner = "OWNER",
}

/**
 * Convert UserGroup to JSON string value
 */
export function usergroupToJson(value: UserGroup): string {
  return value as string;
}

/**
 * Create UserGroup from JSON string value
 */
export function usergroupFromJson(json: string): UserGroup {
  const values = Object.values(UserGroup);
  const found = values.find((v) => v === json);
  if (found !== undefined) {
    return found as UserGroup;
  }
  throw new Error(`Unknown UserGroup value: ${json}`);
}