# file: backend/src/layers/organization_security_layer.yml
# author: AI Assistant
# created: 2025-07-03
# description: Organization Security Lambda Layer - just the layer, no monitoring infrastructure

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Organization Security Lambda Layer - reusable security functions and RBAC utilities'

Parameters:
  CustomerId:
    Type: String
    Default: 'orb'
    Description: Customer identifier for resource naming
  ProjectId:
    Type: String
    Default: 'integration-hub'
    Description: Project identifier for resource naming
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]
    Description: Deployment environment

Resources:
  # Organization Security Lambda Layer
  OrganizationSecurityLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub '${CustomerId}-${ProjectId}-organization-security-layer-${Environment}'
      Description: 'Organization security middleware with audit logging and RBAC utilities'
      Content:
        S3Bucket: !Sub '${CustomerId}-${ProjectId}-build-artifacts-${Environment}'
        S3Key: 'layers/organization-security-layer.zip'
      CompatibleRuntimes:
        - python3.13
      CompatibleArchitectures:
        - x86_64
        - arm64
      LicenseInfo: MIT

Outputs:
  OrganizationSecurityLayerArn:
    Description: 'ARN of the Organization Security Lambda Layer'
    Value: !Ref OrganizationSecurityLayer
    Export:
      Name: !Sub '${CustomerId}-${ProjectId}-organization-security-layer-arn-${Environment}'
  
  OrganizationSecurityLayerVersion:
    Description: 'Version of the Organization Security Lambda Layer'
    Value: !GetAtt OrganizationSecurityLayer.Version
    Export:
      Name: !Sub '${CustomerId}-${ProjectId}-organization-security-layer-version-${Environment}'