// AUTO-GENERATED by e2e-test-generator v0.1.0 - DO NOT EDIT
// Regenerate with: python -m tools.e2e_generator generate

/**
 * Test fixtures for E2E tests
 */

import { Page } from '@playwright/test';

export interface TestUser {
  username: string;
  password: string;
  email: string;
  role: 'OWNER' | 'EMPLOYEE' | 'CUSTOMER';
}

/**
 * Create a test user with specific role
 */
export async function createTestUser(page: Page, role: TestUser['role']): Promise<TestUser> {
  const timestamp = Date.now();
  const user: TestUser = {
    username: `test-user-${timestamp}`,
    password: `TestPass123!`,
    email: `test-${timestamp}@example.com`,
    role
  };

  // Use GraphQL mutation to create user
  const response = await page.request.post('/graphql', {
    data: {
      query: `
        mutation CreateUser($input: UserCreateInput!) {
          UserCreate(input: $input) {
            success
            item {
              userId
              email
            }
          }
        }
      `,
      variables: {
        input: {
          email: user.email,
          username: user.username,
          role: user.role
        }
      }
    }
  });

  const result = await response.json();
  if (!result.data?.UserCreate?.success) {
    throw new Error('Failed to create test user');
  }

  return user;
}

/**
 * Clean up test data after tests
 */
export async function cleanupTestData(page: Page): Promise<void> {
  // Delete test resources created during tests
  // This is a placeholder - implement based on your cleanup strategy
  console.log('Cleaning up test data...');
}

/**
 * Create prerequisite resources for tests
 */
export async function createPrerequisites(page: Page, resourceType: string): Promise<any> {
  // Create dependent resources (e.g., organization before application)
  // This is a placeholder - implement based on your resource dependencies
  console.log(`Creating prerequisites for ${resourceType}...`);
  return {};
}