#!/usr/bin/env python3
# AUTO-GENERATED by orb-schema-generator v0.13.0 - DO NOT EDIT
# Regenerate with: orb-schema generate
import os
import aws_cdk as cdk
from lib.backend_stack import BackendStackStack

app = cdk.App()

env_name = app.node.try_get_context("environment") or "dev"

BackendStackStack(
    app,
    f"BackendStackStack-{env_name}",
    env=cdk.Environment(
        account=os.environ.get("CDK_DEFAULT_ACCOUNT"),
        region=os.environ.get("CDK_DEFAULT_REGION"),
    ),
    tags={
        "Environment": env_name,
        "ManagedBy": "CDK",
    },
)

app.synth()