version: '1'
hash: "sha256:0dfaa68ad75858cbdf8fae661bebdf7696a655f21a55852ff5c996ca8eccd48d"
name: ApplicationStatus
description: Application status
items:
  UNKNOWN:
    value: UNKNOWN
    description: Unknown status
  ACTIVE:
    value: ACTIVE
    description: Active application
  INACTIVE:
    value: INACTIVE
    description: Inactive application
  PENDING:
    value: PENDING
    description: Pending activation
  DELETED:
    value: DELETED
    description: Deleted application
model:
  attributes:
  - name: value
    type: string
    description: Registry item value
    required: true
appsync: {}
