name: deploy-layers

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: environment

jobs:
  deploy-layers:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:

    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Python environment
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Fetch AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Build Organization Security Layer
    - name: Build Organization Security Layer
      run: |
        pip install --upgrade pip
        pip install pipenv --user
        
        echo "Building Organization Security Layer"
        chmod +x build_organization_security_layer.sh
        bash build_organization_security_layer.sh

      working-directory: backend/src/layers/organization_security

    # Build Stripe Layer
    - name: Build Stripe Layer
      run: |
        pip install --upgrade pip
        pip install pipenv --user
        
        echo "Building Stripe Layer"
        chmod +x build_stripe_layer.sh
        bash build_stripe_layer.sh

      working-directory: backend/src/layers/stripe

    # Deploy Consolidated Layers
    - name: Deploy Consolidated Layers
      run: |
        sam build \
        --template layers.yml
        
        sam package \
        --template-file layers.yml \
        --s3-bucket orb-integration-hub-build-artifacts \
        --output-template-file layers-packaged.yml
        
        sam deploy \
        --template-file layers-packaged.yml \
        --s3-bucket orb-integration-hub-build-artifacts \
        --stack-name orb-integration-hub-layers \
        --capabilities CAPABILITY_NAMED_IAM \
        --no-fail-on-empty-changeset
        
        aws s3 cp layers-packaged.yml \
        s3://orb-integration-hub-build-templates/layers-packaged.yml

      working-directory: infrastructure/cloudformation
