name: deploy-organization-security-layer

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: environment

jobs:
  deploy-organization-security-layer:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:

    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Python environment
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    # Fetch AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Build Layer
    - name: Build Organization Security Layer
      run: |
        pip install --upgrade pip
        pip install pipenv --user
        
        echo "Building Organization Security Layer"
        chmod +x build_organization_security_layer.sh
        bash build_organization_security_layer.sh

      working-directory: backend/src/layers/organization_security

    # Deploy Layer
    - name: Deploy Organization Security Layer
      run: |
        sam build \
        --template organization_security_layer.yml
        
        sam package \
        --template-file organization_security_layer.yml \
        --s3-bucket orb-integration-hub-build-artifacts \
        --output-template-file organization_security_layer-packaged.yml
        
        sam deploy \
        --template-file organization_security_layer-packaged.yml \
        --s3-bucket orb-integration-hub-build-artifacts \
        --stack-name orb-integration-hub-organization-security-layer \
        --capabilities CAPABILITY_NAMED_IAM \
        --no-fail-on-empty-changeset
        
        aws s3 cp organization_security_layer-packaged.yml \
        s3://orb-integration-hub-build-templates/organization_security_layer-packaged.yml

      working-directory: backend/src/layers
